### ISSUE TITLE
Error in generating the CPG 

### ISSUE THREAD

**Issue by GiuliCler** [joernio/joern#1045]
When generating the CPG for a project using c2cpg.sh (`c2cpg.sh -o <outputname> <project folder>`) I have this error:
```ERROR C2Cpg: Failed to generate CPG.
java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.file.FileChannelLinesSpliterator.readLine(FileChannelLinesSpliterator.java:176) ~[?:?]
        at java.nio.file.FileChannelLinesSpliterator.forEachRemaining(FileChannelLinesSpliterator.java:116) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257) ~[?:?]
        at java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:605) ~[?:?]
        at better.files.File.lineCount(File.scala:295) ~[com.github.pathikrit.better-files_2.13-3.9.1.jar:3.9.1]
        at io.joern.c2cpg.passes.AstCreationPass.$anonfun$runOnPart$1(AstCreationPass.scala:58) ~[io.joern.c2cpg-1.1.554.jar:1.1.554]
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17) ~[org.scala-lang.scala-library-2.13.8.jar:?]
        at io.joern.c2cpg.utils.TimeUtils$.time(TimeUtils.scala:11) ~[io.joern.c2cpg-1.1.554.jar:1.1.554]
        at io.joern.c2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:54) ~[io.joern.c2cpg-1.1.554.jar:1.1.554]
        at io.joern.c2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:23) ~[io.joern.c2cpg-1.1.554.jar:1.1.554]
        at io.shiftleft.passes.ConcurrentWriterCpgPass.$anonfun$createApplySerializeAndStore$2(ParallelCpgPass.scala:239) ~[io.shiftleft.codepropertygraph_2.13-1.3.501.jar:1.3.501]
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678) ~[org.scala-lang.scala-library-2.13.8.jar:?]
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467) ~[org.scala-lang.scala-library-2.13.8.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
        at java.nio.file.FileChannelLinesSpliterator.readLine(FileChannelLinesSpliterator.java:174) ~[?:?]```

Any suggestion is well appreaciated.
Thank you in advance

**Comment by max-leuthaeuser** [comment]
Thanks for reporting this issue! The linked PR should fix this.
