### ISSUE TITLE
Can joern-cli parse a single java source code?

### ISSUE THREAD

**Issue by HJX-zhanS** [joernio/joern#1917]
When I use `joern-parse.bat D:\MyCode\temp\test\0ed0fc508c197e3cd9a8c3fee60bc3ca-1.3_bug.java`, I get an error:

```
java.nio.file.NotDirectoryException: D:\MyCode\temp\test\0ed0fc508c197e3cd9a8c3fee60bc3ca-1.3_bug.java
        at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:84)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:523)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472)
        at java.base/java.nio.file.Files.list(Files.java:3699)
        at better.files.File.list(File.scala:747)
        at better.files.File.children(File.scala:749)
        at io.joern.javasrc2cpg.util.SourceRootFinder$.statePreSrc(SourceRootFinder.scala:19)
        at io.joern.javasrc2cpg.util.SourceRootFinder$.listBottomLevelSubdirectories(SourceRootFinder.scala:85)
        at io.joern.javasrc2cpg.util.SourceRootFinder$.getSourceRoots(SourceRootFinder.scala:95)
        at io.joern.javasrc2cpg.JavaSrc2Cpg.getSourcesFromDir(JavaSrc2Cpg.scala:98)
        at io.joern.javasrc2cpg.JavaSrc2Cpg.$anonfun$createCpg$1(JavaSrc2Cpg.scala:38)
        at io.joern.javasrc2cpg.JavaSrc2Cpg.$anonfun$createCpg$1$adapted(JavaSrc2Cpg.scala:34)
        at io.joern.x2cpg.X2Cpg$.$anonfun$withNewEmptyCpg$2(X2Cpg.scala:190)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.Try$.apply(Try.scala:210)
        at io.joern.x2cpg.X2Cpg$.$anonfun$withNewEmptyCpg$1(X2Cpg.scala:190)
        at scala.util.Try$.apply(Try.scala:210)
        at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg(X2Cpg.scala:187)
        at io.joern.javasrc2cpg.JavaSrc2Cpg.createCpg(JavaSrc2Cpg.scala:34)
        at io.joern.javasrc2cpg.JavaSrc2Cpg.createCpg(JavaSrc2Cpg.scala:27)
        at io.joern.x2cpg.X2CpgFrontend.$anonfun$run$1(X2Cpg.scala:74)
        at io.joern.x2cpg.X2Cpg$.withErrorsToConsole(X2Cpg.scala:204)
        at io.joern.x2cpg.X2CpgFrontend.run(X2Cpg.scala:73)
        at io.joern.x2cpg.X2CpgFrontend.run$(X2Cpg.scala:72)
        at io.joern.javasrc2cpg.JavaSrc2Cpg.run(JavaSrc2Cpg.scala:27)
        at io.joern.javasrc2cpg.Main$.run(Main.scala:55)
        at io.joern.javasrc2cpg.Main$.run(Main.scala:53)
        at io.joern.x2cpg.X2CpgMain.delayedEndpoint$io$joern$x2cpg$X2CpgMain$1(X2Cpg.scala:47)
        at io.joern.x2cpg.X2CpgMain$delayedInit$body.apply(X2Cpg.scala:36)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at io.joern.x2cpg.X2CpgMain.main(X2Cpg.scala:36)
        at io.joern.javasrc2cpg.Main.main(Main.scala)
```

Can joern-cli parse a single java source code?

**Comment by mpollmeier** [comment]
Yes I'm afraid you'll need to pass the surrounding directory to joern-parse - our javasrc frontend requires it to be that way. Not sure about the reasoning for this.
@johannescoetzee may know more..?

**Comment by HJX-zhanS** [comment]
> Yes I'm afraid you'll need to pass the surrounding directory to joern-parse - our javasrc frontend requires it to be that way. Not sure about the reasoning for this. @johannescoetzee may know more..?

Thanks, in my scene, there is only one .java file in the folder, like `test\0ed0fc508c197e3cd9a8c3fee60bc3ca-1.3_bug.java`. If I set the target path to `test`, the joern-parse.bat can work normally. However, if I use the path of the .java file, like `test\0ed0fc508c197e3cd9a8c3fee60bc3ca-1.3_bug.java`, I encounter the above problems.
