### ISSUE TITLE
next and hasNext not a member of List[A] anymore?

### ISSUE THREAD

**Issue by VainlyStrain** [joernio/joern#1989]
I've noticed that some of my queries don't compile anymore with the latest version of joern, because `hasNext` and `next` seem to be undefined on data structures, like List[String]. Has there been an intentional removal causing this? The queries compiled fine a few months ago.

Here is an example causing an error:
```
var ret0 = cpg.call.code("mySecretFunction").map(
    node => (
        node.argument(2).ast.isLiteral.filterNot(
            _.astChildren.hasNext
        ).code.l,
        node.argument(3).ast.isIdentifier.filterNot(
            _.astChildren.hasNext
        ).code.l
    )
).filter(node => node._1.hasNext && node._2.hasNext).map(   // <-- these lines cause an error
    node => (
        node._1.next.replace("\"", ""),  // <-- these lines cause an error
        node._2.next  // <--
    )
).dedup.l
```

The errors look like this:
```
(synthetic)/ammonite/predef/CodePredef.sc:305: value next is not a member of List[String]
            node._1.next.replace("\"", ""),
```
and `value next is not a member of List[String]` for the first line.

**Comment by mpollmeier** [comment]
thanks for reporting, yes that'll be my change - I'll TAL and see how we best handle this

**Comment by mpollmeier** [comment]
hmm, actually no I can't reproduce this. can you share a more complete example?
here's what I tried:

test-script-list-next.sc
```scala
@main def exec() = {
  importCode("/path/to/HelloShiftLeft/src")

  var ret0 = cpg.call.code("mySecretFunction").map(
      node => (
          node.argument(2).ast.isLiteral.filterNot(
              _.astChildren.hasNext
          ).code.l,
          node.argument(3).ast.isIdentifier.filterNot(
              _.astChildren.hasNext
          ).code.l
      )
  ).filter(node => node._1.hasNext && node._2.hasNext).map(   // <-- these lines cause an error
      node => (
          node._1.next.replace("\"", ""),  // <-- these lines cause an error
          node._2.next  // <--
      )
  ).dedup.l
}
```

and then
```bash
./joern --script test-script-list-next.sc
```

compiles and runs just fine with latest joern from the repo (i.e. `git pull && sbt clean stage`)

**Comment by VainlyStrain** [comment]
Hi!

Interestingly, the code compiles fine when directly pasted into the joern shell. However, it seems to fail when used as --import. Unfortunately, I have to redact some parts of the exact queries, because it would disclose an ongoing, not yet published research, but I am quite certain that the error is not caused in the redacted part. The base structure is as follows:

file: helper.sc
```
def SECRET_METHODS(onlyMethods: Boolean) = {
    var ret0 = cpg.call.code(".*secretMethod.*").where(
        _.argument.argumentIndex(2)
    ).whereNot(
        _.argument.argumentIndexGte(3)
    ).map(
        node => (
            node.argument(1).ast.isLiteral.filterNot(
                _.astChildren.hasNext
            ).code.l,
            node.argument(2).ast.isIdentifier.nameNot("exclusionRegex").filterNot(
                _.astChildren.hasNext
            ).code.l
        )
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
        node => (
            node._1.next.replace("\"", ""),
            node._2.next
        )
    ).dedup.l

    var ret1 = cpg.call.code(".*secretSecondMethod.*").where(
        _.argument.argumentIndex(3)
    ).whereNot(
        _.argument.argumentIndexGte(4)
    ).map(
        node => (
            node.argument(2).ast.isLiteral.filterNot(
                _.astChildren.hasNext
            ).code.l,
            node.argument(3).ast.isIdentifier.nameNot("exclusionRegex").filterNot(
                _.astChildren.hasNext
            ).code.l
        )
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
        node => (
            node._1.next.replace("\"", ""),
            node._2.next
        )
    ).dedup.l
    
    if (onlyMethods) {
        ret0 = ret0.filter(node => cpg.method.name(node._2).hasNext).dedup.l
    }

    var ret = ret0 ::: ret1
    ret = ret.dedup.l
    ret
}
```

file: main.sc
```
@main def exec(cpgFile: String, pFile: String, rFile: String, sFile:String) = {
    var t1 = System.nanoTime
    importCpg(cpgFile)
    run.ossdataflow
    var t2 = System.nanoTime
    
    var prepare: List[(String, String)] = List()
    prepare = prepare ::: SECRET_METHODS(true)
    prepare |> pFile
    var pReg = prepare.l.map(_._2).mkString("|")

    var results: List[Any] = List()
    // main analysis here, should be unrelated, as it doesn't contain any patterns mentioned in the error
    // ...
}
```

I then call joern like this:
```
/usr/local/bin/joern --script path/to/main.sc --params cpgFile=path/to/cpg.bin,pFile=outP.txt,rFile=outR.txt,sFile=outS.json --import path/to/helper.sc
```

When I open the joern shell, and paste in each part of the code manually, everything works as expected. However, the above command throws exceptions concerning next and hasNext.

```
Compiling (synthetic)/ammonite/predef/CodePredef.sc[39m
(synthetic)/ammonite/predef/CodePredef.sc:261: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                             ^
(synthetic)/ammonite/predef/CodePredef.sc:261: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                                                ^
(synthetic)/ammonite/predef/CodePredef.sc:283: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                             ^
(synthetic)/ammonite/predef/CodePredef.sc:283: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                                                ^
(synthetic)/ammonite/predef/CodePredef.sc:303: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                             ^
(synthetic)/ammonite/predef/CodePredef.sc:303: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                                                ^
(synthetic)/ammonite/predef/CodePredef.sc:351: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                             ^
(synthetic)/ammonite/predef/CodePredef.sc:351: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                                                ^
(synthetic)/ammonite/predef/CodePredef.sc:369: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                             ^
(synthetic)/ammonite/predef/CodePredef.sc:369: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                                                ^
(synthetic)/ammonite/predef/CodePredef.sc:400: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                             ^
(synthetic)/ammonite/predef/CodePredef.sc:400: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                                                ^
(synthetic)/ammonite/predef/CodePredef.sc:420: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                             ^
(synthetic)/ammonite/predef/CodePredef.sc:420: value hasNext is not a member of List[String]
    ).filter(node => node._1.hasNext && node._2.hasNext).map(
                                                ^
Exception in thread "main" java.lang.AssertionError: script failed: Compilation Failed
	at io.joern.console.ScriptExecution.runScript(BridgeBase.scala:253)
	at io.joern.console.ScriptExecution.runScript$(BridgeBase.scala:231)
	at io.joern.joerncli.console.AmmoniteBridge$.runScript(AmmoniteBridge.scala:5)
	at io.joern.console.BridgeBase.runAmmonite(BridgeBase.scala:166)
	at io.joern.console.BridgeBase.runAmmonite$(BridgeBase.scala:147)
	at io.joern.joerncli.console.AmmoniteBridge$.runAmmonite(AmmoniteBridge.scala:5)
	at io.joern.joerncli.console.AmmoniteBridge$.delayedEndpoint$io$joern$joerncli$console$AmmoniteBridge$1(AmmoniteBridge.scala:7)
	at io.joern.joerncli.console.AmmoniteBridge$delayedInit$body.apply(AmmoniteBridge.scala:5)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.joern.joerncli.console.AmmoniteBridge$.main(AmmoniteBridge.scala:5)
	at io.joern.joerncli.console.AmmoniteBridge.main(AmmoniteBridge.scala)
```

System specs:
OS: Fedora Linux 36
Processor Architecture: x86-64
Scala Version: 2.13.10
Joern version: 1.1.1272 (installed as release using joern-install.sh)

**Comment by mpollmeier** [comment]
I can now reproduce it. if i use `--import` with my script above (rather than `--script`) i get the same error.  
will have a look on the best way forward. 
Thank you!

**Comment by mpollmeier** [comment]
I gave this some thought, and IMO the best way forward is to change your script. 
Let me explain: the error is `value next is not a member of List[String]` - in other words, there is no function `.next` on a `List`. This is true and was always true, so why did it work before? 
The reason it worked before is that Scala automatically applied an (implicit) conversion from `List` to `Traversal`, because you're trying to invoke `.next`. `Traversal` has that function, so scala tries to make ends meet and automatically converts your List to a Traversal. While that may be convenient, it's not really what you intended, and can lead to surprises in less-straightforward situations. 

To adapt your script in the most simple way you can replace `.hasNext` with `.nonEmpty` and `.next` with `.head`, which are the semantic equivalents from `List`. 

I'd propose to go one step further though and refactor the following parts for better expressiveness and readability:

```scala
// old:
node.argument(1).ast.isLiteral.filterNot(
    _.astChildren.hasNext
).code.l

// change to:
node.argument(1).ast.isLiteral.whereNot(_.astChildren).code.l
```
and
```scala
// old:
.filter(node => node._1.hasNext && node._2.hasNext).map(
        node => (
            node._1.next.replace("\"", ""),
            node._2.next
        )

// change to:
.collect { 
  case (arg1 :: _, arg2 :: _) => 
    (arg1.replace("\"", ""), arg2)
}
```
Some context: 
* `.collect` is like a combined `map` and `filter`
* `arg1 :: _` is a pattern match and decomposition of a List. May sound complicated, but all it really means is: match on a List if it has at least one entry and make that value available under the name `arg1`, and don't care about the tail of the list (hence `_`)
