### ISSUE TITLE
joern --script --param error

### ISSUE THREAD

**Issue by INT2ECALL** [joernio/joern#2022]
Joern print this error when I run a script with a parameter:
```
C:\Users\admin\Desktop>joern --script C:\Users\admin\Desktop\test.sc --params cpgFile=cpg.bin
Error: Option --params failed when given 'cpgFile'. Expected a key=value pair
Try --help for more information.
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627)
        at scala.None$.get(Option.scala:626)
        at io.joern.console.BridgeBase.parseConfig(BridgeBase.scala:141)
        at io.joern.console.BridgeBase.parseConfig$(BridgeBase.scala:37)
        at io.joern.joerncli.console.AmmoniteBridge$.parseConfig(AmmoniteBridge.scala:5)
        at io.joern.joerncli.console.AmmoniteBridge$.delayedEndpoint$io$joern$joerncli$console$AmmoniteBridge$1(AmmoniteBridge.scala:7)
        at io.joern.joerncli.console.AmmoniteBridge$delayedInit$body.apply(AmmoniteBridge.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at io.joern.joerncli.console.AmmoniteBridge$.main(AmmoniteBridge.scala:5)
        at io.joern.joerncli.console.AmmoniteBridge.main(AmmoniteBridge.scala)
```

Here are my script content:
```
import io.shiftleft.semanticcpg.language._

@main def exec(cpgFile: String) = {
   importCpg(cpgFile)
   cpg.method.name.l 
}
```
How to solve this problem?

**Comment by max-leuthaeuser** [comment]
I guess you are using the Windows Powershell?
With that, the syntax becomes:
`> joern --script C:\Users\admin\Desktop\test.sc --params "cpgFile = cpg.bin"`
