### ISSUE TITLE
docker build failing

### ISSUE THREAD

**Issue by irwincong** [joernio/joern#2117]
When using `docker build . -t joern:latest` from 08b9ab629a0eb20882e169562ac9a03893fd3635

```
...
#8 127.0 [info] resolving key references (19531 settings) ...
#8 132.9 [info] set current project to joern (in build file:/joern/)
#8 133.7 downloading https://github.com/max-leuthaeuser/astgen/releases/download/v2.4.0/astgen-linux
#8 133.7 ERROR: Failed to install composer with error code 127
#8 133.7 /joern/joern-cli/frontends/php2cpg/bin/installdeps.sh: line 5: php: not found
#8 133.7 /joern/joern-cli/frontends/php2cpg/bin/installdeps.sh: line 6: php: not found
#8 133.7 /joern/joern-cli/frontends/php2cpg/bin/installdeps.sh: line 7: php: not found
#8 133.7 /joern/joern-cli/frontends/php2cpg/bin/installdeps.sh: line 16: php: not found
#8 133.7 rm: can't remove 'composer-setup.php': No such file or directory
...
#8 213.9 [error] ## Exception when compiling 32 sources to /joern/dataflowengineoss/target/scala-2.13/classes
#8 213.9 [error] java.lang.IllegalArgumentException: error: release version 8 not supported
#8 213.9 [error] jdk.compiler/com.sun.tools.javac.main.Arguments.reportDiag(Arguments.java:891)
#8 213.9 [error] jdk.compiler/com.sun.tools.javac.main.Arguments.handleReleaseOptions(Arguments.java:311)
#8 213.9 [error] jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:350)
#8 213.9 [error] jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
#8 213.9 [error] jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
#8 213.9 [error] jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:119)
#8 213.9 [error] jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
#8 213.9 [error] sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:345)
#8 213.9 [error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$12(AnalyzingJavaCompiler.scala:172)
#8 213.9 [error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
#8 213.9 [error] sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:262)
#8 213.9 [error] sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:161)
#8 213.9 [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2(MixedAnalyzingCompiler.scala:103)
#8 213.9 [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2$adapted(MixedAnalyzingCompiler.scala:91)
#8 213.9 [error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
#8 213.9 [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:91)
#8 213.9 [error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
#8 213.9 [error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
#8 213.9 [error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
#8 213.9 [error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:198)
#8 213.9 [error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
#8 213.9 [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
#8 213.9 [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
#8 213.9 [error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
#8 213.9 [error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
#8 213.9 [error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
#8 213.9 [error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
#8 213.9 [error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
#8 213.9 [error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
#8 213.9 [error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
#8 213.9 [error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
#8 213.9 [error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
#8 213.9 [error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
#8 213.9 [error] sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
#8 213.9 [error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
#8 213.9 [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
#8 213.9 [error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
#8 213.9 [error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
#8 213.9 [error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
#8 213.9 [error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2363)
#8 213.9 [error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2313)
#8 213.9 [error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
#8 213.9 [error] sbt.internal.io.Retry$.apply(Retry.scala:46)
#8 213.9 [error] sbt.internal.io.Retry$.apply(Retry.scala:28)
#8 213.9 [error] sbt.internal.io.Retry$.apply(Retry.scala:23)
#8 213.9 [error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
#8 213.9 [error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2311)
#8 213.9 [error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
#8 213.9 [error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
#8 213.9 [error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
#8 213.9 [error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
#8 213.9 [error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
#8 213.9 [error] sbt.Execute.work(Execute.scala:291)
#8 213.9 [error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
#8 213.9 [error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
#8 213.9 [error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
#8 213.9 [error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#8 213.9 [error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
#8 213.9 [error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#8 213.9 [error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
#8 213.9 [error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
#8 213.9 [error] java.base/java.lang.Thread.run(Thread.java:829)
#8 213.9 [error]
#8 214.1 [warn] /joern/joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/TestCpg.scala:19:39: parameter value codeFile in method codeFilePreProcessing is never used
#8 214.1 [warn]   protected def codeFilePreProcessing(codeFile: Path): Unit = {}
#8 214.1 [warn]                                       ^
#8 214.1 [warn] You have no main class in your project. No start script will be generated.
#8 214.1 [warn] You have no main class in your project. No start script will be generated.
#8 214.4 [warn] /joern/joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala:176:7: possible missing interpolator: detected an interpolated expression
#8 214.4 [warn]       """
#8 214.4 [warn]       ^
#8 218.5 [warn] two warnings found
#8 218.5 [info] done compiling
#8 218.6 [warn] You have no main class in your project. No start script will be generated.
#8 218.6 [warn] You have no main class in your project. No start script will be generated.
#8 235.6 [error] java.lang.IllegalArgumentException: error: release version 8 not supported
#8 235.6 [error] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.reportDiag(Arguments.java:891)
#8 235.6 [error] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.handleReleaseOptions(Arguments.java:311)
#8 235.6 [error] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:350)
#8 235.6 [error] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
#8 235.6 [error] 	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
#8 235.6 [error] 	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:119)
#8 235.6 [error] 	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
#8 235.6 [error] 	at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:345)
#8 235.6 [error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$12(AnalyzingJavaCompiler.scala:172)
#8 235.6 [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
#8 235.6 [error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:262)
#8 235.6 [error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:161)
#8 235.6 [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2(MixedAnalyzingCompiler.scala:103)
#8 235.6 [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2$adapted(MixedAnalyzingCompiler.scala:91)
#8 235.6 [error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
#8 235.6 [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:91)
#8 235.6 [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
#8 235.6 [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
#8 235.6 [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
#8 235.6 [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:198)
#8 235.6 [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
#8 235.6 [error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
#8 235.6 [error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
#8 235.6 [error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
#8 235.6 [error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
#8 235.6 [error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
#8 235.6 [error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
#8 235.6 [error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
#8 235.6 [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
#8 235.6 [error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2363)
#8 235.6 [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2313)
#8 235.6 [error] 	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
#8 235.6 [error] 	at sbt.internal.io.Retry$.apply(Retry.scala:46)
#8 235.6 [error] 	at sbt.internal.io.Retry$.apply(Retry.scala:28)
#8 235.6 [error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
#8 235.6 [error] 	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
#8 235.6 [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2311)
#8 235.6 [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
#8 235.6 [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
#8 235.6 [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
#8 235.6 [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
#8 235.6 [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
#8 235.6 [error] 	at sbt.Execute.work(Execute.scala:291)
#8 235.6 [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
#8 235.6 [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
#8 235.7 [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
#8 235.7 [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#8 235.7 [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
#8 235.7 [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#8 235.7 [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
#8 235.7 [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
#8 235.7 [error] 	at java.base/java.lang.Thread.run(Thread.java:829)
#8 235.7 [error] (dataflowengineoss / Compile / compileIncremental) java.lang.IllegalArgumentException: error: release version 8 not supported
#8 235.7 [error] Total time: 102 s (01:42), completed Dec 19, 2022, 9:52:55 PM
------
executor failed running [/bin/sh -c git clone https://github.com/ShiftLeftSecurity/joern.git && cd joern && sbt stage]: exit code: 1
```

I have not yet tried in a linux vm. It looks like the Dockerfile was last updated to support JRE11 in https://github.com/joernio/joern/pull/616 to match what is run in CI/CD, and release workflows seem to all be passing. Should these `build.sbt` files be updated?

https://github.com/joernio/joern/blob/d17d7c521eb029cb2541cdc05023b111e8e26a4f/dataflowengineoss/build.sbt#L21
https://github.com/joernio/joern/blob/ef04526cb714dc85d137c5e29519a1db7ac25812/benchmarks/build.sbt#L18

**Comment by itsacoderepo** [comment]
Not solving the java issue but adds php and updates sbt https://github.com/joernio/joern/pull/2121
