### ISSUE TITLE
joern --script --param error

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#2286]
**To Reproduce**
Main.sc
```scala
@main def main(name: String) = {
  println(name)
}
```
and powershell
```shell
 ./joern --script C:\Users\admin\Documents\idea_projects\joern\Main.sc --params "name = test"  
```

**Errors**
```shell
Exception in thread "main" java.lang.AssertionError: script failed: Missing argument: --name <str>
Unknown arguments: "--name " " test"
Expected Signature: main
  --name <str>
```

**Desktop (please complete the following information):**
 - Win 11
 - Joern up to date
 - powershell

**Additional context**
Refer to https://github.com/joernio/joern/issues/2022#issue-1464294109

**Comment by max-leuthaeuser** [comment]
```
.\joern --script C:\Path\To\Main.sc --params "name= test"
executing C:\Path\To\Main.sc with params=Map(name ->  test)
Compiling (synthetic)/ammonite/predef/CodePredef.sc
Compiling C:\Path\To\Main.sc
 test
script finished successfully
()
```

Notice the `"name= test"` (no whitespace after `name`).

**Comment by yzn12345** [comment]
> ```
> .\joern --script C:\Path\To\Main.sc --params "name= test"
> executing C:\Path\To\Main.sc with params=Map(name ->  test)
> Compiling (synthetic)/ammonite/predef/CodePredef.sc
> Compiling C:\Path\To\Main.sc
>  test
> script finished successfully
> ()
> ```
> 
> Notice the `"name= test"` (no whitespace after `name`).
> 
> Either some whitespace parsing in a newer Powershell has been changed or its from an update to some dependency we are using for CLI argument handling.

Another question, is there a way to fix this？
when I run the following:
```shell
./joern --script C:\Users\admin\Documents\idea_projects\joern\taint_rules\Main.sc --params "path= C:\\Users\\admin\\Documents\\idea_projects\\joern\\testing_code,name= sql222" 
```
I will get:
```shell
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2:  C:\\Users\\admin\\Documents\\idea_projects\\joern\\testing_code

```
Thank you!

**Comment by max-leuthaeuser** [comment]
Looks like a different thing not related to CLI argument handling.
Where does this path end up? Could you paste the whole stack trace?

**Comment by yzn12345** [comment]
In the .sc file, this line works okay
```shell
  importCode(
    inputPath = "C:\\Users\\admin\\Documents\\idea_projects\\joern\\testing_code",
    projectName = "test"
  )
```
But if I pass the args to the main like this:
```shell
./joern --script C:\Users\admin\Documents\idea_projects\joern\taint_rules\Main.sc --params "path= C:\\Users\\admin\\Documents\\idea_projects\\joern\\testing_code" 
```
and the main is
```shell
@main def main(path: String) = {
   importCode(inputPath = path, projectName = "test")
}
```
then the whole error stack will be like:
```shell
Exception in thread "main" java.lang.AssertionError: script errored: 
        at io.joern.console.ScriptExecution.runScript(BridgeBase.scala:253)
        at io.joern.console.ScriptExecution.runScript$(BridgeBase.scala:229)
        at io.joern.joerncli.console.AmmoniteBridge$.runScript(AmmoniteBridge.scala:5)
        at io.joern.console.BridgeBase.runAmmonite(BridgeBase.scala:166)
        at io.joern.console.BridgeBase.runAmmonite$(BridgeBase.scala:147)
        at io.joern.joerncli.console.AmmoniteBridge$.runAmmonite(AmmoniteBridge.scala:5)
        at io.joern.joerncli.console.AmmoniteBridge$.delayedEndpoint$io$joern$joerncli$console$AmmoniteBridge$1(AmmoniteBridge.scala:7)
        at io.joern.joerncli.console.AmmoniteBridge$delayedInit$body.apply(AmmoniteBridge.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at io.joern.joerncli.console.AmmoniteBridge$.main(AmmoniteBridge.scala:5)
        at io.joern.joerncli.console.AmmoniteBridge.main(AmmoniteBridge.scala)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2:  C:\\Users\\admin\\Documents\\idea_projects\\joern\\testing_code
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at better.files.File$.apply(File.scala:1355)
        at io.joern.console.cpgcreation.ImportCode.checkInputPath(ImportCode.scala:21)
        at mainargs.Invoker$.$anonfun$runMains$1(Invoker.scala:87)
        at mainargs.Result.flatMap(Result.scala:13)
        at mainargs.Result.flatMap$(Result.scala:12)
        at mainargs.Result$Success.flatMap(Result.scala:23)
        at mainargs.Invoker$.groupArgs$1(Invoker.scala:87)
        at mainargs.Invoker$.runMains(Invoker.scala:91)
        at ammonite.main.Scripts$.$anonfun$runScript$5(Scripts.scala:105)
        at ammonite.util.Util$.withContextClassloader(Util.scala:24)
        at ammonite.main.Scripts$.$anonfun$runScript$4(Scripts.scala:81)
        at ammonite.util.Res$Success.flatMap(Res.scala:62)
        at ammonite.main.Scripts$.$anonfun$runScript$2(Scripts.scala:48)
        at ammonite.util.Res$Success.flatMap(Res.scala:62)
        at ammonite.main.Scripts$.$anonfun$runScript$1(Scripts.scala:27)
        at ammonite.util.Res$Success.flatMap(Res.scala:62)
        at ammonite.main.Scripts$.runScript(Scripts.scala:23)
        at ammonite.Main.runScript(Main.scala:252)
        at io.joern.console.ScriptExecution.runScript(BridgeBase.scala:245)
        ... 19 more

```
I think this is due to some windows path parsing issue but don't know how to fix it. Appreciate it.

**Comment by max-leuthaeuser** [comment]
This worked here:
`.\joern --script C:\Path\To\Main.sc --params """path=C:\\Path\\To\\testing_code"""`
