### ISSUE TITLE
Recently, the new sootup came out, and I found that it was not compatible with the recent joern.

### ISSUE THREAD

**Issue by 75ACOL** [joernio/joern#2350]
Have you considered compatibility?

**Comment by 75ACOL** [comment]
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 8294
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)

**Comment by DavidBakerEffendi** [comment]
Could you explain how to reproduce this issue? What did you run to generate that issue?

**Comment by 75ACOL** [comment]
I use sootup to generate Jimple, and then use Jimple2Cpg to generate cpg. An error is reported.

**Comment by DavidBakerEffendi** [comment]
From [what I see in the documentation](https://soot-oss.github.io/SootUp/jimple/), the Jimple language is unchanged. But to be honest, the `jimple2cpg` frontend is mostly aimed at ingesting JVM bytecode, using Soot to convert this to Jimple, and then using the Jimple objects to create the CPG.
