### ISSUE TITLE
[Bug] kotlin2cpg NPE

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#2430]
**Describe the bug**

Sorry can't share the source

```
2023-03-28 17:27:03.455 INFO shutdown finished
java.lang.NullPointerException
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astsForBlock(KtPsiToAst.scala:415)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astsForBlock$(KtPsiToAst.scala:405)
	at io.joern.kotlin2cpg.passes.AstCreator.astsForBlock(AstCreator.scala:24)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.$anonfun$secondaryCtorAsts$1(KtPsiToAst.scala:169)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.secondaryCtorAsts(KtPsiToAst.scala:152)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.secondaryCtorAsts$(KtPsiToAst.scala:149)
	at io.joern.kotlin2cpg.passes.AstCreator.secondaryCtorAsts(AstCreator.scala:24)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astsForClassOrObject(KtPsiToAst.scala:291)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astsForClassOrObject$(KtPsiToAst.scala:199)
	at io.joern.kotlin2cpg.passes.AstCreator.astsForClassOrObject(AstCreator.scala:24)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astsForDeclaration(KtPsiToAst.scala:89)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astsForDeclaration$(KtPsiToAst.scala:87)
	at io.joern.kotlin2cpg.passes.AstCreator.astsForDeclaration(AstCreator.scala:24)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.$anonfun$astForFile$6(KtPsiToAst.scala:49)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.convert.JavaCollectionWrappers$JListWrapper.flatMap(JavaCollectionWrappers.scala:103)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astForFile(KtPsiToAst.scala:49)
	at io.joern.kotlin2cpg.passes.KtPsiToAst.astForFile$(KtPsiToAst.scala:24)
	at io.joern.kotlin2cpg.passes.AstCreator.astForFile(AstCreator.scala:24)
	at io.joern.kotlin2cpg.passes.AstCreator.createAst(AstCreator.scala:48)
	at io.joern.kotlin2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:20)
	at io.joern.kotlin2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:11)
	at io.shiftleft.passes.ConcurrentWriterCpgPass.$anonfun$createApplySerializeAndStore$1(ParallelCpgPass.scala:95)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by itsacoderepo** [comment]
Closing because it is fixed, re-open if not
