### ISSUE TITLE
[Bug] Unable to import cpg generated by go2cpg

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#2446]
**Describe the bug**

I generated cpg for a go project using https://github.com/AppThreat/cpggen. This doesn't seem to be importing on joern correctly.

```
You have provided a legacy proto CPG. Attempting conversion.
Error converting legacy CPG: Failed to insert a node. proto:
key: 1
type: UNKNOWN_ENUM_VALUE_NodeType_36
property {
  name: VALUE
  value {
    string_value: ""
  }
}

Exception in thread "main" java.lang.AssertionError: script errored:
	at io.joern.console.ScriptExecution.runScript(BridgeBase.scala:242)
	at io.joern.console.ScriptExecution.runScript$(BridgeBase.scala:223)
	at io.joern.joerncli.console.AmmoniteBridge$.runScript(AmmoniteBridge.scala:5)
	at io.joern.console.BridgeBase.runAmmonite(BridgeBase.scala:166)
	at io.joern.console.BridgeBase.runAmmonite$(BridgeBase.scala:147)
	at io.joern.joerncli.console.AmmoniteBridge$.runAmmonite(AmmoniteBridge.scala:5)
	at io.joern.joerncli.console.AmmoniteBridge$.delayedEndpoint$io$joern$joerncli$console$AmmoniteBridge$1(AmmoniteBridge.scala:7)
	at io.joern.joerncli.console.AmmoniteBridge$delayedInit$body.apply(AmmoniteBridge.scala:5)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.joern.joerncli.console.AmmoniteBridge$.main(AmmoniteBridge.scala:5)
	at io.joern.joerncli.console.AmmoniteBridge.main(AmmoniteBridge.scala)
```

**To Reproduce**

Use cpggen container image to generate a cpg for a go project. Example invocation below

https://github.com/AppThreat/cpggen/blob/main/.github/workflows/repotests.yml#L92

**Expected behavior**
Same CPG spec is to be used with CPG being compatible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS
 - Joern Version 
 - Java version

**Additional context**

**Comment by itsacoderepo** [comment]
Closing, because the open source front end is just started.
