### ISSUE TITLE
[Bug] Possible Race Condition in joern-slice leading to overflowdb errors

### ISSUE THREAD

**Issue by pr0me** [joernio/joern#2463]
When importing and slicing code with `joern-slice`, sometimes a `overflowdb.SchemaViolationException` is thrown.
This was observed for multiple TypeScript projects.
As mentioned in #2439, this seems to be occurring non-deterministically.
During testing, an error occurred in ca. 1 out of 20 runs.

**To Reproduce**
1. Extract the attached example project and run
```
joern-slice -m Usages ./example/ -o ./
```
[example.zip](https://github.com/joernio/joern/files/11158323/example.zip)

2. If CPG creation succeeds, `rm example.json` and repeat step 1. 
3. Observe the following error:
```java
Exception in thread "main" overflowdb.SchemaViolationException: OUT edge with label AST to an adjacent METHOD_RETURN is mandatory, but not defined for this METHOD node with id=590
	at io.shiftleft.codepropertygraph.generated.nodes.MethodDb.methodReturn(Method.scala:645)

```

<details><summary>Full Stack Trace</summary>
<p>

```java
[+] Applying default overlays
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Temporary CPG has been successfully generated at /tmp/joern-slice2972118312677447146.bin
Exception in thread "main" overflowdb.SchemaViolationException: OUT edge with label AST to an adjacent METHOD_RETURN is mandatory, but not defined for this METHOD node with id=590
	at io.shiftleft.codepropertygraph.generated.nodes.MethodDb.methodReturn(Method.scala:645)
	at io.shiftleft.codepropertygraph.generated.nodes.Method.methodReturn(Method.scala:204)
	at io.shiftleft.codepropertygraph.generated.traversal.MethodTraversalExtGen$.$anonfun$methodReturn$1(Method.scala:35)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at scala.collection.IterableOps.headOption(Iterable.scala:231)
	at scala.collection.IterableOps.headOption$(Iterable.scala:229)
	at overflowdb.traversal.Traversal.headOption(Traversal.scala:16)
	at io.joern.joerncli.slicing.UsageSlicing$.$anonfun$trackUsage$6(UsageSlicing.scala:166)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
	at scala.collection.IterableOps.headOption(Iterable.scala:231)
	at scala.collection.IterableOps.headOption$(Iterable.scala:229)
	at overflowdb.traversal.Traversal.headOption(Traversal.scala:16)
	at io.joern.joerncli.slicing.UsageSlicing$.exprToObservedCall$1(UsageSlicing.scala:165)
	at io.joern.joerncli.slicing.UsageSlicing$.$anonfun$trackUsage$14(UsageSlicing.scala:181)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
	at scala.collection.immutable.List.prependedAll(List.scala:155)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
	at overflowdb.traversal.Traversal.toList(Traversal.scala:16)
	at io.joern.joerncli.slicing.UsageSlicing$.partitionInvolvementInCalls$1(UsageSlicing.scala:181)
	at io.joern.joerncli.slicing.UsageSlicing$.trackUsage(UsageSlicing.scala:209)
	at io.joern.joerncli.slicing.UsageSlicing$.$anonfun$calculateUsageSlice$3(UsageSlicing.scala:45)
	at scala.collection.parallel.AugmentedIterableIterator.flatmap2combiner(RemainsIterator.scala:123)
	at scala.collection.parallel.AugmentedIterableIterator.flatmap2combiner$(RemainsIterator.scala:121)
	at scala.collection.parallel.immutable.ParVector$ParVectorIterator.flatmap2combiner(ParVector.scala:70)
	at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1038)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1034)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$19.next(Iterator.scala:966)
	at scala.collection.Iterator$$anon$19.next(Iterator.scala:964)
	at scala.collection.Iterator$$anon$7.next(Iterator.scala:528)
	at overflowdb.traversal.Traversal.next(Traversal.scala:22)
	at io.shiftleft.codepropertygraph.generated.nodes.MethodDb.methodReturn(Method.scala:640)
	... 43 more

```

</p>
</details> 

More rarely, the following error is observed:
```java
Exception in thread "main" java.lang.NullPointerException
	at overflowdb.NodeDb.startIndex(NodeDb.java:664)
	at overflowdb.NodeDb.createAdjacentNodeIteratorByOffSet(NodeDb.java:595)
	at io.shiftleft.codepropertygraph.generated.nodes.MethodDb.astOut(Method.scala:638)
	at io.shiftleft.codepropertygraph.generated.nodes.MethodDb.methodReturn(Method.scala:640)
	at io.shiftleft.codepropertygraph.generated.nodes.Method.methodReturn(Method.scala:204)
	at io.shiftleft.codepropertygraph.generated.traversal.MethodTraversalExtGen$.$anonfun$methodReturn$1(Method.scala:35)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at scala.collection.IterableOps.headOption(Iterable.scala:231)
	at scala.collection.IterableOps.headOption$(Iterable.scala:229)
	at overflowdb.traversal.Traversal.headOption(Traversal.scala:16)
	at io.joern.joerncli.slicing.UsageSlicing$.$anonfun$trackUsage$6(UsageSlicing.scala:166)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
	at scala.collection.IterableOps.headOption(Iterable.scala:231)
	at scala.collection.IterableOps.headOption$(Iterable.scala:229)
	at overflowdb.traversal.Traversal.headOption(Traversal.scala:16)
	at io.joern.joerncli.slicing.UsageSlicing$.exprToObservedCall$1(UsageSlicing.scala:165)
	at io.joern.joerncli.slicing.UsageSlicing$.$anonfun$trackUsage$14(UsageSlicing.scala:181)

[...]
```

**Expected behavior**
CPG creation should always succeed and must not fail non-deterministically.

**Desktop (please complete the following information):**
 - OS: Linux 5.15.0-1030-gcp 37-Ubuntu
 - Joern Version: 1.1.1563
 - javac 11.0.18

**Comment by mpollmeier** [comment]
hmm, doesn't look like I can reproduce this
```scala
1.to(10).foreach { i =>
  importCode("example/nightfallai_nightfall-nodejs-sdk")
  println(s"---------------- test run $i completed: cpg=$cpg -------------------")
}
```

Tested on linux with java11 and joern 1.1.1564

**Comment by pr0me** [comment]
Working on something more reproducible right now. Maybe it happens more often on a different project, right now I'm also having a hard time reproducing it, sorry for the inconvenience.

**Comment by pr0me** [comment]
Okay, I might've messed up my command while reproducing, it's probably specific to `joern-slice`.
(Note the 
```java
[...])

But even there I only seem to run into the error every 20 tries or so.

**Comment by max-leuthaeuser** [comment]
joern-slice had some PRs recently. Maybe there is something wrong.

**Comment by DavidBakerEffendi** [comment]
I have been able to produce this and this is thrown at the following line in the slice extractor:
```scala
x.callee(resolver).methodReturn.typeFullName.headOption
```
It alleges that the callee does not have an AST edge between the method and the method return, but the dot AST is:
![graphviz](https://user-images.githubusercontent.com/28294550/231386075-1e4397e8-bdf4-46d8-88d6-7c83c92f5d70.png)

One common thread is that this happens at field access calls that are all prefixed by `await` e.g. here are all the `.code` and locations from the example above.
```
config.queueName @ RedisPersister.ts#Some(32)
//   await lpush(config.queueName, JSON.stringify(data));
config.queueName @ RedisPersister.ts#Some(19)
//   while (result = await lpop(config.queueName)) {
config.latestKeyName @ RedisPersister.ts#Some(38)
//   const result = await get(config.latestKeyName);
```
Additionally, I have confirmed via `x.callee(resolver).out("AST").map(_.label()).l` that before the crash, there is in fact a method return present: `List(METHOD_PARAMETER_IN, METHOD_PARAMETER_IN, BLOCK, METHOD_RETURN, METHOD_PARAMETER_OUT, METHOD_PARAMETER_OUT)`

I am not sure where to go from here besides handling this with a `try-catch` but I can't see an obvious reason why it happens unless ODB is struggling to handle concurrent queries in this instance - where everything is within a fork-join pool.

**Comment by max-leuthaeuser** [comment]
I think the underlying issue is the usage of `.par` here: https://github.com/joernio/joern/blob/2e8ba2df3a1fbfa59477b453dc35c0dba3e4c42a/joern-cli/src/main/scala/io/joern/joerncli/slicing/UsageSlicing.scala#L44 which might break some assumptions with parallel access of ODB. 
May @bbrehm has an idea if that's the case.
