### ISSUE TITLE
[Bug] NullPointerException in XTypeRecovery pass

### ISSUE THREAD

**Issue by pr0me** [joernio/joern#2512]
On certain TypeScript projects, importing the code in joern leads to a `java.lang.NullPointerException` when applying TypeRecovery passes in `io.joern.x2cpg.passes.frontend.XTypeRecovery`, resulting in early termination and no CPG being generated.

**To Reproduce**
1. Open joern and `importCode` the attached example 
[example.zip](https://github.com/joernio/joern/files/11238969/example.zip)

2. Observe the following error:
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
  java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.$anonfun$run$4(XTypeRecovery.scala:118)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.$anonfun$run$4$adapted(XTypeRecovery.scala:118)
  scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
[...]
```

<details><summary>Full Stack Trace:</summary>
<p>

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
  java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.$anonfun$run$4(XTypeRecovery.scala:118)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.$anonfun$run$4$adapted(XTypeRecovery.scala:118)
  scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
  scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:733)
  scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:724)
  overflowdb.traversal.Traversal.reduceLeft(Traversal.scala:16)
  scala.collection.IterableOnceOps.reduce(IterableOnce.scala:698)
  scala.collection.IterableOnceOps.reduce$(IterableOnce.scala:698)
  overflowdb.traversal.Traversal.reduce(Traversal.scala:16)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.run(XTypeRecovery.scala:119)
  io.shiftleft.passes.CpgPass.runOnPart(CpgPass.scala:27)
  io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:134)
  io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:74)
  io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
  io.joern.x2cpg.passes.frontend.XTypeRecoveryPass.$anonfun$run$2(XTypeRecovery.scala:77)
  scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.scala:18)
  scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
  scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
  scala.collection.AbstractIterable.foreach(Iterable.scala:926)
  scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
  io.joern.x2cpg.passes.frontend.XTypeRecoveryPass.run(XTypeRecovery.scala:74)
  io.shiftleft.passes.CpgPass.runOnPart(CpgPass.scala:27)
  io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:134)
  io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:74)
  io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
  io.joern.console.cpgcreation.JsSrcCpgGenerator.$anonfun$applyPostProcessingPasses$1(JsSrcCpgGenerator.scala:24)
  io.joern.console.cpgcreation.JsSrcCpgGenerator.$anonfun$applyPostProcessingPasses$1$adapted(JsSrcCpgGenerator.scala:24)
  scala.collection.immutable.List.foreach(List.scala:333)
  io.joern.console.cpgcreation.JsSrcCpgGenerator.applyPostProcessingPasses(JsSrcCpgGenerator.scala:24)
  io.joern.console.cpgcreation.ImportCode.$anonfun$apply$6(ImportCode.scala:144)
  scala.Option.map(Option.scala:242)
  io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$apply(ImportCode.scala:140)
  io.joern.console.cpgcreation.ImportCode.apply(ImportCode.scala:40)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc:1)
java.lang.NullPointerException
  overflowdb.traversal.NodeTraversal$.$anonfun$in$2(NodeTraversal.scala:46)
  scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
  scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
  scala.collection.Iterator.isEmpty(Iterator.scala:459)
  scala.collection.Iterator.isEmpty$(Iterator.scala:459)
  scala.collection.AbstractIterator.isEmpty(Iterator.scala:1293)
  overflowdb.traversal.RepeatStepIterator.traverseOnWorklist(RepeatStep.scala:78)
  overflowdb.traversal.RepeatStepIterator.hasNext(RepeatStep.scala:69)
  scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:593)
  scala.collection.IterableOps.headOption(Iterable.scala:231)
  scala.collection.IterableOps.headOption$(Iterable.scala:229)
  overflowdb.traversal.Traversal.headOption(Traversal.scala:16)
  io.shiftleft.semanticcpg.language.nodemethods.MethodMethods$.definingTypeDecl$extension(MethodMethods.scala:55)
  io.shiftleft.semanticcpg.language.nodemethods.MethodMethods$.typeDecl$extension(MethodMethods.scala)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.$anonfun$isField$1(XTypeRecovery.scala:433)
  scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
  scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:961)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.isField(XTypeRecovery.scala:433)
  io.joern.jssrc2cpg.passes.RecoverForJavaScriptFile.super$isField(JavaScriptTypeRecovery.scala:147)
  io.joern.jssrc2cpg.passes.RecoverForJavaScriptFile.$anonfun$isField$1(JavaScriptTypeRecovery.scala:147)
  scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
  scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:961)
  io.joern.jssrc2cpg.passes.RecoverForJavaScriptFile.isField(JavaScriptTypeRecovery.scala:147)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit$$anonfun$associateTypes$2.applyOrElse(XTypeRecovery.scala:455)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit$$anonfun$associateTypes$2.applyOrElse(XTypeRecovery.scala:452)
  scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
  scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
  scala.Option.collect(Option.scala:462)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.associateTypes(XTypeRecovery.scala:452)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.visitCallAssignedToLiteral(XTypeRecovery.scala:697)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.visitAssignments(XTypeRecovery.scala:350)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.$anonfun$compute$1(XTypeRecovery.scala:276)
  scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
  scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
  overflowdb.traversal.Traversal.foreach(Traversal.scala:16)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.compute(XTypeRecovery.scala:276)
  io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.compute(XTypeRecovery.scala:170)
  java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
  java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:381)
  java.util.concurrent.ForkJoinTask.externalInterruptibleAwaitDone(ForkJoinTask.java:351)
  java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.$anonfun$run$4(XTypeRecovery.scala:118)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.$anonfun$run$4$adapted(XTypeRecovery.scala:118)
  scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
  scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:733)
  scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:724)
  overflowdb.traversal.Traversal.reduceLeft(Traversal.scala:16)
  scala.collection.IterableOnceOps.reduce(IterableOnce.scala:698)
  scala.collection.IterableOnceOps.reduce$(IterableOnce.scala:698)
  overflowdb.traversal.Traversal.reduce(Traversal.scala:16)
  io.joern.x2cpg.passes.frontend.XTypeRecovery.run(XTypeRecovery.scala:119)
  io.shiftleft.passes.CpgPass.runOnPart(CpgPass.scala:27)
  io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:134)
  io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:74)
  io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
  io.joern.x2cpg.passes.frontend.XTypeRecoveryPass.$anonfun$run$2(XTypeRecovery.scala:77)
  scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.scala:18)
  scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
  scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
  scala.collection.AbstractIterable.foreach(Iterable.scala:926)
  scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
  io.joern.x2cpg.passes.frontend.XTypeRecoveryPass.run(XTypeRecovery.scala:74)
  io.shiftleft.passes.CpgPass.runOnPart(CpgPass.scala:27)
  io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:134)
  io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:74)
  io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
  io.joern.console.cpgcreation.JsSrcCpgGenerator.$anonfun$applyPostProcessingPasses$1(JsSrcCpgGenerator.scala:24)
  io.joern.console.cpgcreation.JsSrcCpgGenerator.$anonfun$applyPostProcessingPasses$1$adapted(JsSrcCpgGenerator.scala:24)
  scala.collection.immutable.List.foreach(List.scala:333)
  io.joern.console.cpgcreation.JsSrcCpgGenerator.applyPostProcessingPasses(JsSrcCpgGenerator.scala:24)
  io.joern.console.cpgcreation.ImportCode.$anonfun$apply$6(ImportCode.scala:144)
  scala.Option.map(Option.scala:242)
  io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$apply(ImportCode.scala:140)
  io.joern.console.cpgcreation.ImportCode.apply(ImportCode.scala:40)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc:1)

```

</p>
</details> 

Sometimes, this error is accompanied by subsequent errors such as 
```
main ERROR An exception occurred processing Appender Console org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.NoSuchMethodError: 'java.util.Deque org.apache.logging.log4j.util.StackLocatorUtil.getCurrentStackTrace()'
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:163)
```

**Expected behavior**
The TypeRecovery pass should succeed and a complete CPG should be generated.

**Desktop (please complete the following information):**
- OS: Linux 5.15.0-1030-gcp 37-Ubuntu
- Joern Version: 1.1.1590
- javac 11.0.18

**Comment by max-leuthaeuser** [comment]
A fix is in master now and should prevent this issue here. Feel free to reopen if you encounter any unexpected behavior.
