### ISSUE TITLE
[Bug] Exception while querying v8 repo

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#2555]
**Describe the bug**

```
joern> def source=cpg.call("(ProcessNewScript|ParseProgram)").argument
defined function source

joern> def sink=cpg.method(".*unicode.*").parameter
defined function sink

joern> sink.reachableByFlows(source).p
2023-04-23 07:43:09.451 WARN Engine: SolveTask failed with exception:
java.util.concurrent.ExecutionException: java.util.NoSuchElementException: java.util.NoSuchElementException
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:581) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:993) ~[?:?]
	at io.joern.dataflowengineoss.queryengine.Engine.$anonfun$solveTasks$5(Engine.scala:99) ~[io.joern.dataflowengineoss-1.1.1556.jar:1.1.1556]
	at scala.util.Try$.apply(Try.scala:210) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at io.joern.dataflowengineoss.queryengine.Engine.runUntilAllTasksAreSolved$1(Engine.scala:99) ~[io.joern.dataflowengineoss-1.1.1556.jar:1.1.1556]
	at io.joern.dataflowengineoss.queryengine.Engine.solveTasks(Engine.scala:114) ~[io.joern.dataflowengineoss-1.1.1556.jar:1.1.1556]
	at io.joern.dataflowengineoss.queryengine.Engine.backwards(Engine.scala:53) ~[io.joern.dataflowengineoss-1.1.1556.jar:1.1.1556]
	at io.joern.dataflowengineoss.language.ExtendedCfgNode$.reachableByInternal$extension(ExtendedCfgNode.scala:84) ~[io.joern.dataflowengineoss-1.1.1556.jar:1.1.1556]
	at io.joern.dataflowengineoss.language.ExtendedCfgNode$.reachableByFlows$extension(ExtendedCfgNode.scala:48) ~[io.joern.dataflowengineoss-1.1.1556.jar:1.1.1556]
	at ammonite.$sess.cmd3$.<clinit>(cmd3.sc:1) ~[?:?]
	at ammonite.$sess.cmd3.$main(cmd3.sc) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$evalMain$1(Evaluator.scala:108) ~[com.lihaoyi.ammonite-runtime_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Util$.withContextClassloader(Util.scala:24) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.runtime.Evaluator$$anon$1.evalMain(Evaluator.scala:90) ~[com.lihaoyi.ammonite-runtime_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processLine$2(Evaluator.scala:127) ~[com.lihaoyi.ammonite-runtime_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Catching.map(Res.scala:117) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processLine$1(Evaluator.scala:121) ~[com.lihaoyi.ammonite-runtime_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.runtime.Evaluator$$anon$1.processLine(Evaluator.scala:120) ~[com.lihaoyi.ammonite-runtime_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.interp.Interpreter.$anonfun$evaluateLine$5(Interpreter.scala:307) ~[com.lihaoyi.ammonite-interp_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.interp.Interpreter.$anonfun$evaluateLine$2(Interpreter.scala:290) ~[com.lihaoyi.ammonite-interp_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Catching.flatMap(Res.scala:115) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.interp.Interpreter.evaluateLine(Interpreter.scala:289) ~[com.lihaoyi.ammonite-interp_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.interp.Interpreter.$anonfun$processLine$6(Interpreter.scala:277) ~[com.lihaoyi.ammonite-interp_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.interp.Interpreter.$anonfun$processLine$4(Interpreter.scala:260) ~[com.lihaoyi.ammonite-interp_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.interp.Interpreter.$anonfun$processLine$2(Interpreter.scala:253) ~[com.lihaoyi.ammonite-interp_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Catching.flatMap(Res.scala:115) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.interp.Interpreter.processLine(Interpreter.scala:252) ~[com.lihaoyi.ammonite-interp_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Repl.$anonfun$action$8(Repl.scala:199) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.repl.Repl.$anonfun$action$4(Repl.scala:186) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Scoped.$anonfun$flatMap$1(Signaller.scala:45) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Signaller.apply(Signaller.scala:28) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Scoped.flatMap(Signaller.scala:45) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Scoped.flatMap$(Signaller.scala:45) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Signaller.flatMap(Signaller.scala:16) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Repl.$anonfun$action$2(Repl.scala:178) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.util.Catching.flatMap(Res.scala:115) ~[com.lihaoyi.ammonite-util_2.13-2.5.8.jar:2.5.8]
	at ammonite.repl.Repl.action(Repl.scala:170) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Repl.loop$1(Repl.scala:212) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.repl.Repl.run(Repl.scala:227) ~[com.lihaoyi.ammonite-repl_2.13.8-2.5.8.jar:2.5.8]
	at ammonite.Main.$anonfun$run$1(Main.scala:236) ~[com.lihaoyi.ammonite_2.13.8-2.5.8.jar:2.5.8]
	at scala.Option.getOrElse(Option.scala:201) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at ammonite.Main.run(Main.scala:224) ~[com.lihaoyi.ammonite_2.13.8-2.5.8.jar:2.5.8]
	at io.joern.console.ScriptExecution.startInteractiveShell(BridgeBase.scala:213) ~[io.joern.console-1.1.1556.jar:1.1.1556]
	at io.joern.console.ScriptExecution.startInteractiveShell$(BridgeBase.scala:195) ~[io.joern.console-1.1.1556.jar:1.1.1556]
```

**To Reproduce**
1. Use https://github.com/v8/v8

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS
 - Joern Version 
 - Java version

**Additional context**

**Comment by itsacoderepo** [comment]
I can't reproduce it, can you share more details? 

![image](https://user-images.githubusercontent.com/5180740/233990941-6c48dcf1-fd33-47b9-9e28-eef16d6aec63.png)

**Comment by prabhu** [comment]
@itsacoderepo I am unable to generate cpg for the v8 repo with the latest joern. No idea what mistake I am making. I am even passing 128GB heap memory and tried passing from 80-128GB. It runs for hours and hours and gets killed eventually.

**Comment by mpollmeier** [comment]
The difference between Niko's and your results might result from how exactly you imported the code, which isn't specified in detail in the description. Niko's screenshot suggests that he ran something like `importCode("path/to/v8/src")` which made joern's heuristic choose the c2cpg frontend. You only shared the v8 repo url, so I assume you ran something like `importCode("path/to/v8")` which makes joern's heuristic choose the jssrc2cpg frontend. Could that be the root of the confusion?

If you want to force a frontend yourself, use e.g. `importCode.c("path")`
To see all options, <tab> is your friend:
![image](https://github.com/joernio/joern/assets/506752/3a3f8246-445b-4335-8a31-359c21b16be3)

**Comment by prabhu** [comment]
@mpollmeier Not as simple as that.

```
/home/almalinux/bin/joern/joern-cli/c2cpg.sh -J-Xmx128G -o /home/almalinux/work/sandbox/v8/src/cpg_out/src-c-cpg.bin.zip /home/almalinux/work/sandbox/v8/src
```

**Comment by mpollmeier** [comment]
we all get different results...
for me, the cpg generation and import into joern work just fine, but the reachableBy query doesn't find anything. Here's what I did:

```
sbt clean stage
joern-cli/frontends/c2cpg/c2cpg.sh -J-Xmx80g -o cpg.bin ~/tmp/cpgtesting/v8/src
./joern -J-Xmx50g

importCpg("cpg.bin")
def source=cpg.call("(ProcessNewScript|ParseProgram)").argument
def sink=cpg.method(".*unicode.*").parameter
sink.reachableByFlows(source).p
```

![image](https://github.com/joernio/joern/assets/506752/684a91bb-ce71-4616-bc0d-a5fcd3d50c39)

¯\_(ツ)_/¯
