### ISSUE TITLE
[Bug]joern-export fails for PDG in neo4jcsv format

### ISSUE THREAD

**Issue by jylsec** [joernio/joern#2571]
x42 is clone from https://github.com/ShiftLeftSecurity/x42.git, which is learned from Quickstart part
```
> joern-parse x42/c
> joern-export --repr pdg --format=neo4jcsv
Exception in thread "main" scala.MatchError: Pdg (of class scala.Enumeration$Val)
        at io.joern.joerncli.JoernExport$.exportWithOdbFormat(JoernExport.scala:138)
        at io.joern.joerncli.JoernExport$.exportCpg(JoernExport.scala:111)
        at io.joern.joerncli.JoernExport$.$anonfun$main$2(JoernExport.scala:67)
        at io.joern.joerncli.JoernExport$.$anonfun$main$2$adapted(JoernExport.scala:66)
        at scala.util.Using$.resource(Using.scala:261)
        at io.joern.joerncli.JoernExport$.$anonfun$main$1(JoernExport.scala:66)
        at io.joern.joerncli.JoernExport$.$anonfun$main$1$adapted(JoernExport.scala:61)
        at scala.Option.foreach(Option.scala:437)
        at io.joern.joerncli.JoernExport$.main(JoernExport.scala:61)
        at io.joern.joerncli.JoernExport.main(JoernExport.scala)
```

**Comment by mpollmeier** [comment]
This isn't a bug unfortunately - we simply don't currently support this combination (pdg, neo4jcsv) yet. Sorry, and yes the error message should be clear about that, I'll make a quick fix for that.
