### ISSUE TITLE
[Bug] Embedded JS Template (.ejs) Files break JSSRC Frontend

### ISSUE THREAD

**Issue by pr0me** [joernio/joern#2579]
**Describe the bug**
If `.ejs` files are present while importing a Javascript project in joern, the jssrc2cpg frontend breaks.  
Apparently it tries to import the files which involves some internal renaming / file extension assumptions, resulting in trying to open a non-existent file.  
Subsequently, no CPG is generated.

**To Reproduce**
1. run `importCode` in joern on the attached example. 
The example includes on `.js` file as language frontend inference will not work if _only_ `.ejs` files are present.
[example.zip](https://github.com/joernio/joern/files/11321623/example.zip)
2. Observe the following error:
```
WARN AstGenRunner$: 	- failed to parse '/path/to/example/bare-end.js': 'Unexpected token (26:7)'

java.io.FileNotFoundException: /path/to/example/bare-end.js (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at io.shiftleft.utils.IOUtils$.readLinesInFile(IOUtils.scala:77)
	at io.joern.jssrc2cpg.passes.AstCreationPass.$anonfun$finish$1(AstCreationPass.scala:38)
```
<details><summary>Full Stack Trace</summary>
<p>

```java
2023-04-25 12:28:25.647 WARN AstGenRunner$: 	- failed to parse '/home/pr0me/Documents/code/phd/paper-typeclassifier/type-inference-models/evaluation/lambdanet_ds/test_set/maquette/example/bare-end.js': 'Unexpected token (26:7)'
java.io.FileNotFoundException: /home/pr0me/Documents/code/phd/paper-typeclassifier/type-inference-models/evaluation/lambdanet_ds/test_set/maquette/example/bare-end.js (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at io.shiftleft.utils.IOUtils$.readLinesInFile(IOUtils.scala:77)
	at io.joern.jssrc2cpg.passes.AstCreationPass.$anonfun$finish$1(AstCreationPass.scala:38)
	at io.joern.jssrc2cpg.passes.AstCreationPass.$anonfun$finish$1$adapted(AstCreationPass.scala:35)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at io.joern.jssrc2cpg.passes.AstCreationPass.finish(AstCreationPass.scala:35)
	at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore(ParallelCpgPass.scala:116)
	at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
	at io.joern.jssrc2cpg.JsSrc2Cpg.$anonfun$createCpg$2(JsSrc2Cpg.scala:29)
	at io.joern.jssrc2cpg.JsSrc2Cpg.$anonfun$createCpg$2$adapted(JsSrc2Cpg.scala:24)
	at better.files.Dispose.apply(Dispose.scala:75)
	at better.files.Dispose.foreach(Dispose.scala:91)
	at better.files.File$.usingTemporaryDirectory(File.scala:1320)
	at io.joern.jssrc2cpg.JsSrc2Cpg.$anonfun$createCpg$1(JsSrc2Cpg.scala:24)
	at io.joern.jssrc2cpg.JsSrc2Cpg.$anonfun$createCpg$1$adapted(JsSrc2Cpg.scala:23)
	at io.joern.x2cpg.X2Cpg$.$anonfun$withNewEmptyCpg$2(X2Cpg.scala:193)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.Try$.apply(Try.scala:210)
	at io.joern.x2cpg.X2Cpg$.$anonfun$withNewEmptyCpg$1(X2Cpg.scala:193)
	at scala.util.Try$.apply(Try.scala:210)
	at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg(X2Cpg.scala:190)
	at io.joern.jssrc2cpg.JsSrc2Cpg.createCpg(JsSrc2Cpg.scala:23)
	at io.joern.jssrc2cpg.JsSrc2Cpg.createCpg(JsSrc2Cpg.scala:18)
	at io.joern.x2cpg.X2CpgFrontend.$anonfun$run$1(X2Cpg.scala:77)
	at io.joern.x2cpg.X2Cpg$.withErrorsToConsole(X2Cpg.scala:207)
	at io.joern.x2cpg.X2CpgFrontend.run(X2Cpg.scala:76)
	at io.joern.x2cpg.X2CpgFrontend.run$(X2Cpg.scala:75)
	at io.joern.jssrc2cpg.JsSrc2Cpg.run(JsSrc2Cpg.scala:18)
	at io.joern.jssrc2cpg.Main$.run(Main.scala:67)
	at io.joern.jssrc2cpg.Main$.run(Main.scala:62)
	at io.joern.x2cpg.X2CpgMain.main(X2Cpg.scala:48)
	at io.joern.jssrc2cpg.Main.main(Main.scala)
[+] Applying default overlays
Missing metaData block
Missing metaData block
Missing metaData block
2023-04-25 12:28:26.923 WARN ControlFlow: io.joern.x2cpg.layers.ControlFlow depends on List(base) but CPG only has Set() - skipping creation
Missing metaData block
2023-04-25 12:28:26.925 WARN TypeRelations: io.joern.x2cpg.layers.TypeRelations depends on List(base) but CPG only has Set() - skipping creation
Missing metaData block
2023-04-25 12:28:26.925 WARN CallGraph: io.joern.x2cpg.layers.CallGraph depends on List(typerel) but CPG only has Set() - skipping creation
Missing metaData block
2023-04-25 12:28:27.001 ERROR CpgPassBase: Pass io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass failed
overflowdb.SchemaViolationException: OUT edge with label REF to an adjacent METHOD is mandatory, but not defined for this METHOD_REF node with id=209
	at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:837) ~[io.shiftleft.codepropertygraph-domain-classes_2.13-1.3.598.jar:1.3.598]
	at io.shiftleft.codepropertygraph.generated.nodes.MethodRef.referencedMethod(MethodRef.scala:307) ~[io.shiftleft.codepropertygraph-domain-classes_2.13-1.3.598.jar:1.3.598]
	at io.shiftleft.codepropertygraph.generated.traversal.MethodRefTraversalExtGen$.$anonfun$referencedMethod$1(MethodRef.scala:14) ~[io.shiftleft.codepropertygraph-domain-classes_2.13-1.3.598.jar:1.3.598]
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$7.hasNext(Iterator.scala:516) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:470) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.mutable.Growable.addAll(Growable.scala:61) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.mutable.ArrayBuilder.addAll(ArrayBuilder.scala:66) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.toArray(IterableOnce.scala:1282) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.toArray$(IterableOnce.scala:1276) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1293) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.Array$.from(Array.scala:74) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:282) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:273) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.ClassTagIterableFactory$AnyIterableDelegate.from(Factory.scala:671) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableFactory$ToFactory.fromSpecific(Factory.scala:274) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.to(IterableOnce.scala:1246) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.to$(IterableOnce.scala:1246) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at overflowdb.traversal.Traversal.to(Traversal.scala:16) ~[io.shiftleft.overflowdb-traversal_2.13-1.171.jar:1.171]
	at overflowdb.traversal.Traversal.sortBy(Traversal.scala:286) ~[io.shiftleft.overflowdb-traversal_2.13-1.171.jar:1.171]
	at io.joern.dataflowengineoss.package$.identifiersFromCapturedScopes(package.scala:19) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at io.joern.dataflowengineoss.package$.$anonfun$identifierToFirstUsages$1(package.scala:14) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.immutable.List.prependedAll(List.scala:152) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.AbstractIterator.toList(Iterator.scala:1293) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at overflowdb.traversal.Traversal.l(Traversal.scala:27) ~[io.shiftleft.overflowdb-traversal_2.13-1.171.jar:1.171]
	at io.joern.dataflowengineoss.package$.identifierToFirstUsages(package.scala:14) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.$anonfun$addReachingDefEdges$22(DdgGenerator.scala:175) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.immutable.List.prependedAll(List.scala:152) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.AbstractIterator.toList(Iterator.scala:1293) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at overflowdb.traversal.Traversal.l(Traversal.scala:27) ~[io.shiftleft.overflowdb-traversal_2.13-1.171.jar:1.171]
	at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addEdgesToCapturedIdentifiersAndParameters$1(DdgGenerator.scala:174) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addReachingDefEdges(DdgGenerator.scala:208) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:33) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:14) ~[io.joern.dataflowengineoss-1.1.1628.jar:1.1.1628]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:147) ~[io.shiftleft.codepropertygraph_2.13-1.3.598.jar:1.3.598]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:145) ~[io.shiftleft.codepropertygraph_2.13-1.3.598.jar:1.3.598]
	at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) ~[?:?]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$19.next(Iterator.scala:966) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$19.next(Iterator.scala:964) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.Iterator$$anon$7.next(Iterator.scala:528) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at overflowdb.traversal.Traversal.next(Traversal.scala:22) ~[io.shiftleft.overflowdb-traversal_2.13-1.171.jar:1.171]
	at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:832) ~[io.shiftleft.codepropertygraph-domain-classes_2.13-1.3.598.jar:1.3.598]
	... 59 more

```

</p>
</details>

**Expected behavior**
I assume, `.ejs` could just be skipped.
Or internal renaming should make sure it's not trying actually open a file which does not exist.
A CPG should be generated in any case, based on valid .js and .ts files.

**Desktop (please complete the following information):**
- OS: Linux pop-os 6.0.12-76060006-generic 22.04
- Joern Version: 1.1.1628
- javac 11.0.17

**Comment by max-leuthaeuser** [comment]
Ah strange. I will have a look.

**Comment by max-leuthaeuser** [comment]
Works here without any issues. Make sure you have the latest astgen binaries.
`sbt clean` helps with that as it always removes them.

**Comment by pr0me** [comment]
Thanks for looking into it.  

Is `astgen` not part of the joern release?
I'm always running
```bash
git pull
sudo ./joern-install.sh --reinstall
```

**Comment by max-leuthaeuser** [comment]
It is and the latest version is in the final distribution.
Could you do a clean fresh git clone of the repo and a manual `sbt stage` and then run Joern with `./joern`?

**Comment by pr0me** [comment]
Strange, error still persists.
Clean clone, built locally (v1.1.1642), downloaded the .zip I attached after reopening the issue, still getting the error:
```
java.io.FileNotFoundException: /path/to/example/bare-end.ejs (No such file or directory)
```

(weirdly enough, it's not trying to open `/path/to/example/x/bare-end.ejs`)  

I have confirmed on a completely separate system that the error persists with a fresh install of joern.

**Comment by max-leuthaeuser** [comment]
You are running `./joern` in that folder and not `joern` by accident? Because the latter would be the one from your systems installation of joern.

**Comment by pr0me** [comment]
Yes, running the locally built version (uninstalled the system installation just to double check, too).

<details><summary>Full Stack Trace</summary>
<p>

```
Version: 1.1.1642
Type `help` or `browse(help)` to begin
      
joern> importCode("./example") 
Using generator for language: JSSRC: JsSrcCpgGenerator
Creating project `example1` for code at `./example`
=======================================================================================================
Invoking CPG generator in a separate process. Note that the new process will consume additional memory.
If you are importing a large codebase (and/or running into memory issues), please try the following:
1) exit joern
2) invoke the frontend: /home/pr0me/Documents/code/phd/joern/joern-cli/target/universal/stage/jssrc2cpg.sh -J-Xmx3936m ./example --output /home/pr0me/Documents/code/phd/joern/workspace/example1/cpg.bin.zip
3) start joern, import the cpg: `importCpg("path/to/cpg")`
=======================================================================================================

java.io.FileNotFoundException: /home/pr0me/Documents/code/phd/joern/example/bare-end.ejs (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at io.shiftleft.utils.IOUtils$.readLinesInFile(IOUtils.scala:77)
	at io.joern.jssrc2cpg.parser.BabelJsonParser$.readFile(BabelJsonParser.scala:35)
	at io.joern.jssrc2cpg.passes.AstCreationPass.$anonfun$runOnPart$1(AstCreationPass.scala:46)
	at io.joern.jssrc2cpg.utils.TimeUtils$.time(TimeUtils.scala:11)
	at io.joern.jssrc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:45)
	at io.joern.jssrc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:22)
	at io.shiftleft.passes.ConcurrentWriterCpgPass.$anonfun$createApplySerializeAndStore$1(ParallelCpgPass.scala:95)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: /home/pr0me/Documents/code/phd/joern/workspace/example1/cpg.bin.tmp
Code successfully imported. You can now query it using `cpg`.
For an overview of all imported code, type `workspace`.
Missing metaData block
Adding default overlays to base CPG
Missing metaData block
Missing metaData block
Missing metaData block
Missing metaData block
Missing metaData block
2023-04-27 14:20:37.586 WARN ControlFlow: io.joern.x2cpg.layers.ControlFlow depends on List(base) but CPG only has Set() - skipping creation
Missing metaData block
Missing metaData block
2023-04-27 14:20:37.589 WARN TypeRelations: io.joern.x2cpg.layers.TypeRelations depends on List(base) but CPG only has Set() - skipping creation
Missing metaData block
Missing metaData block
2023-04-27 14:20:37.589 WARN CallGraph: io.joern.x2cpg.layers.CallGraph depends on List(typerel) but CPG only has Set() - skipping creation
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
Missing metaData block
Missing metaData block
Missing metaData block
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
res0: Cpg = Cpg (Graph [0 nodes])
```

</p>
</details>

**Comment by max-leuthaeuser** [comment]
Still can't reproduce this.
Could you please run the frontend standalone with `export SL_LOGGING_LEVEL=debug` and post the full logs?

**Comment by max-leuthaeuser** [comment]
Nvm.. I was finally able to reproduce it on an older Linux machine here and this should fix it:
https://github.com/joernio/joern/pull/2600

**Comment by pr0me** [comment]
Yes, that works, thanks a lot Max!
