### ISSUE TITLE
[Bug] Usage of CRLF crashes jssrc2cpg

### ISSUE THREAD

**Issue by xavierpinho** [joernio/joern#2601]
**Describe the bug**
Trying to scan a file using CRLF (0x0d 0x0a) for newlines crashes jssrc2cpg.

**To Reproduce**
1. Scan the attached file via jssrc2cpg.sh: [example.zip](https://github.com/joernio/joern/files/11345139/example.zip)
2. Observe the following crash
```
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627) ~[org.scala-lang.scala-library-2.13.8.jar:?]
        at scala.None$.get(Option.scala:626) ~[org.scala-lang.scala-library-2.13.8.jar:?]
        at io.joern.jssrc2cpg.astcreation.AstCreatorHelper.getLineOfSource(AstCreatorHelper.scala:128) ~[io.joern.jssrc2cpg-1.1.1639.jar:1.1.1639]
        at io.joern.jssrc2cpg.astcreation.AstCreatorHelper.$anonfun$lineEnd$1(AstCreatorHelper.scala:120) ~[io.joern.jssrc2cpg-1.1.1639.jar:1.1.1639]
        at io.joern.jssrc2cpg.astcreation.AstCreatorHelper.$anonfun$lineEnd$1$adapted(AstCreatorHelper.scala:120) ~[io.joern.jssrc2cpg-1.1.1639.jar:1.1.1639]
        at scala.Option.map(Option.scala:242) ~[org.scala-lang.scala-library-2.13.8.jar:?]
        at io.joern.jssrc2cpg.astcreation.AstCreatorHelper.lineEnd(AstCreatorHelper.scala:120) ~[io.joern.jssrc2cpg-1.1.1639.jar:1.1.1639]
        at io.joern.jssrc2cpg.astcreation.AstCreatorHelper.lineEnd$(AstCreatorHelper.scala:120) ~[io.joern.jssrc2cpg-1.1.1639.jar:1.1.1639]
        at io.joern.jssrc2cpg.astcreation.AstCreator.lineEnd(AstCreator.scala:27) ~[io.joern.jssrc2cpg-1.1.1639.jar:1.1.1639]
        at io.joern.jssrc2cpg.astcreation.AstCreatorHelper.createBabelNodeInfo(AstCreatorHelper.scala:33) ~[io.joern.jssrc2cpg-1.1.1639.jar:1.1.1639]
```

**Expected behavior**

Handle CRLF-style newlines.

**Desktop (please complete the following information):**
 - OS: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
 - Joern Version 1.1.1639
 - javac 20

**Additional context**
Noticed that simply replacing CRLF by LF avoids this crash.

**Comment by max-leuthaeuser** [comment]
This might be a MacOS-specific problem.
We use https://github.com/joernio/joern/blob/230ba872f69365bee0302f2b312c4aa7d48de8f0/joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala#L44 while reading in files. 
I tested all combination of newlines on Linux and Windows already but maybe I missed that (got no Mac to reproduce this).

**Comment by max-leuthaeuser** [comment]
Uh yeah.. I never tested files that have both types of linebreaks in them. Then that's the root cause here.
