### ISSUE TITLE
[Bug] joern-slice DataFlow slice mode errors with a java app

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#2642]
**Describe the bug**

```
/home/almalinux/bin/joern/joern-cli/javasrc2cpg -J-Xmx128G -o /home/almalinux/work/sandbox/vuln-spring/cpg_out/vuln-spring-java-cpg.bin.zip /home/almalinux/work/sandbox/vuln-spring --fetch-dependencies --inference-jar-paths /home/almalinux/.m2
```

```
[00:01:27] INFO     ------------------------------
           INFO     Exception in thread "main" java.util.NoSuchElementException
                            at io.shiftleft.Implicits$JavaIteratorDeco$.onlyChecked$extension(Implicits.scala:43)
                            at io.shiftleft.semanticcpg.language.nodemethods.CfgNodeMethods$.walkUpContains$extension(CfgNodeMethods.scala:148)
                            at io.shiftleft.semanticcpg.language.nodemethods.CfgNodeMethods$.method$extension(CfgNodeMethods.scala:127)
                            at io.joern.joerncli.slicing.DataFlowSlicing$.$anonfun$calculateDataFlowSlice$1(DataFlowSlicing.scala:16)
                            at scala.collection.IterableOps.groupBy(Iterable.scala:560)
                            at scala.collection.IterableOps.groupBy$(Iterable.scala:555)
                            at overflowdb.traversal.Traversal.groupBy(Traversal.scala:16)
                            at io.joern.joerncli.slicing.DataFlowSlicing$.calculateDataFlowSlice(DataFlowSlicing.scala:16)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$2(JoernSlice.scala:47)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$2$adapted(JoernSlice.scala:45)
                            at scala.util.Using$.resource(Using.scala:261)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$1(JoernSlice.scala:45)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$1$adapted(JoernSlice.scala:41)
                            at scala.Option.foreach(Option.scala:437)
                            at io.joern.joerncli.JoernSlice$.main(JoernSlice.scala:41)
                            at io.joern.joerncli.JoernSlice.main(JoernSlice.scala)

           INFO     ------------------------------
           INFO     Command used /home/almalinux/bin/joern/joern-cli/joern-slice -m DataFlow --out /home/almalinux/work/sandbox/vuln-spring/cpg_out/vuln-spring-java-cpg.slices /home/almalinux/work/sandbox/vuln-spring/cpg_out/vuln-spring-java-cpg.bin.zip
                    Please report the above error to https://github.com/joernio/joern/issues
```

**To Reproduce**
Use https://github.com/HooliCorp/vuln-spring

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS - Linux
 - Joern Version - 1.1.1672
 - Java version

**Additional context**

**Comment by prabhu** [comment]
This particular error message is seen for many other queries in addition to joern slice. Must be a bug when dealing with type enriched cpg generated with --fetch-dependencies and jar path
