### ISSUE TITLE
[Bug][joern-slice] Error with jssrc

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#2676]
**Describe the bug**

https://github.com/HooliCorp/vulnerable-aws-koa-app

CPG generated using

/home/almalinux/bin/joern/joern-cli/jssrc2cpg.sh -J-Xmx128G -o /tmp/cpg_out/cpggenguzp4kfs-js-cpg.bin.zip /tmp/cpggenguzp4kfs

```
[22:04:14] WARNING  Slice operation has failed for /tmp/cpg_out/cpggenguzp4kfs-js-cpg.bin.zip
           INFO     ------------------------------
           INFO     Exception in thread "main" overflowdb.SchemaViolationException: OUT edge with label REF to an adjacent METHOD is mandatory, but not defined for this METHOD_REF node with id=309
                            at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:836)
                            at io.shiftleft.codepropertygraph.generated.nodes.MethodRef.referencedMethod(MethodRef.scala:324)
                            at io.shiftleft.codepropertygraph.generated.traversal.MethodRefTraversalExtGen$.$anonfun$referencedMethod$1(MethodRef.scala:14)
                            at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
                            at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
                            at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
                            at scala.collection.Iterator$$anon$7.hasNext(Iterator.scala:516)
                            at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:470)
                            at scala.collection.Iterator$ConcatIterator.advance$1(Iterator.scala:1175)
                            at scala.collection.Iterator$ConcatIterator.hasNext(Iterator.scala:1181)
                            at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:593)
                            at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:594)
                            at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:594)
                            at scala.collection.Iterator$$anon$8.hasNext(Iterator.scala:555)
                            at scala.collection.immutable.List.prependedAll(List.scala:155)
                            at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
                            at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
                            at overflowdb.traversal.Traversal.toList(Traversal.scala:16)
                            at io.joern.joerncli.slicing.UsageSlicing$.io$joern$joerncli$slicing$UsageSlicing$$getInCallsForReferencedIdentifiers(UsageSlicing.scala:210)
                            at io.joern.joerncli.slicing.UsageSlicing$.atLeastNCalls(UsageSlicing.scala:231)
                            at io.joern.joerncli.slicing.UsageSlicing$.$anonfun$calculateUsageSlice$2(UsageSlicing.scala:48)
                            at io.joern.joerncli.slicing.UsageSlicing$.$anonfun$calculateUsageSlice$2$adapted(UsageSlicing.scala:48)
                            at scala.collection.immutable.LazyList$.$anonfun$filterImpl$1(LazyList.scala:1014)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state$lzycompute(LazyList.scala:259)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state(LazyList.scala:252)
                            at scala.collection.immutable.LazyList.isEmpty(LazyList.scala:269)
                            at scala.collection.immutable.LazyList.$anonfun$mapImpl$1(LazyList.scala:516)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state$lzycompute(LazyList.scala:259)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state(LazyList.scala:252)
                            at scala.collection.immutable.LazyList.isEmpty(LazyList.scala:269)
                            at scala.collection.immutable.LazyList$.$anonfun$flatMapImpl$1(LazyList.scala:1048)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state$lzycompute(LazyList.scala:259)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state(LazyList.scala:252)
                            at scala.collection.immutable.LazyList$.$anonfun$flatMapImpl$2(LazyList.scala:1060)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state$lzycompute(LazyList.scala:259)
                            at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state(LazyList.scala:252)
                            at scala.collection.immutable.LazyList.isEmpty(LazyList.scala:269)
                            at scala.collection.immutable.LazyList$LazyIterator.hasNext(LazyList.scala:1250)
                            at scala.collection.IterableOps.groupBy(Iterable.scala:558)
                            at scala.collection.IterableOps.groupBy$(Iterable.scala:555)
                            at scala.collection.AbstractIterable.groupBy(Iterable.scala:926)
                            at io.joern.joerncli.slicing.UsageSlicing$.usageSlices$1(UsageSlicing.scala:51)
                            at io.joern.joerncli.slicing.UsageSlicing$.calculateUsageSlice(UsageSlicing.scala:61)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$2(JoernSlice.scala:48)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$2$adapted(JoernSlice.scala:45)
                            at scala.util.Using$.resource(Using.scala:261)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$1(JoernSlice.scala:45)
                            at io.joern.joerncli.JoernSlice$.$anonfun$main$1$adapted(JoernSlice.scala:41)
                            at scala.Option.foreach(Option.scala:437)
                            at io.joern.joerncli.JoernSlice$.main(JoernSlice.scala:41)
                            at io.joern.joerncli.JoernSlice.main(JoernSlice.scala)
                    Caused by: java.util.NoSuchElementException: next on empty iterator
                            at scala.collection.Iterator$$anon$19.next(Iterator.scala:966)
                            at scala.collection.Iterator$$anon$19.next(Iterator.scala:964)
                            at scala.collection.Iterator$$anon$7.next(Iterator.scala:528)
                            at overflowdb.traversal.Traversal.next(Traversal.scala:22)
                            at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:831)
                            ... 50 more

           INFO     ------------------------------
           INFO     Command used /home/almalinux/bin/joern/joern-cli/joern-slice -m Usages --out /tmp/cpg_out/cpggenguzp4kfs-js-cpg.slices.json /tmp/cpg_out/cpggenguzp4kfs-js-cpg.bin.zip
                    Please report the above error to https://github.com/joernio/joern/issues
```

**Desktop (please complete the following information):**
 - OS
 - Joern Version Latest
 - Java version

**Additional context**

**Comment by max-leuthaeuser** [comment]
@DavidBakerEffendi is this another instance of https://github.com/joernio/joern/pull/2493?

**Comment by DavidBakerEffendi** [comment]
@max-leuthaeuser Hmm, it is possible that this is a method ref generated by the type recovery, but that doesn't have a corresponding stub of sorts. If that is the case, then the fix for [this issue](https://github.com/joernio/joern/issues/2673) can have this one in mind.

**Comment by DavidBakerEffendi** [comment]
@max-leuthaeuser I think this is the case, on the latest Joern I can't reproduce, so it must have been fixed in the JS CPG generation? cc @prabhu

**Comment by prabhu** [comment]
@DavidBakerEffendi I can replicate with the latest joern. Any ideas how you are testing?

**Comment by DavidBakerEffendi** [comment]
@prabhu `./joern-slice /path/to/vulnerable-aws-koa-app -m Usages`

**Comment by prabhu** [comment]
@DavidBakerEffendi It works when specifying the directory but not when passing the cpg file.

**Comment by DavidBakerEffendi** [comment]
@prabhu That would make sense, those `METHOD_REF` nodes would be linked by the default passes. Are you generating the CPG purely from the AST pass?

**Comment by prabhu** [comment]
Using jssrc2cpg. Have shared the command in the ticket. How do we make slice work with cpg instead of the directory?

**Comment by DavidBakerEffendi** [comment]
@prabhu it does work on the CPG, when one specifies the directory, all it does is run `JoernParse`. The slicer needs the default overlays to work. Perhaps use `joern-parse` and specify JS if you want to force the JS frontend to run?

**Comment by prabhu** [comment]
This ticket can be closed
