### ISSUE TITLE
[Bug]Javasrc2cpg java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by akuseru** [joernio/joern#3073]
**Describe the bug**
```
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at overflowdb.misc.ArrayIter.hasNext(ArrayIter.scala:6)
        at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:477)
        at scala.collection.IterableOnceOps.size(IterableOnce.scala:846)
        at scala.collection.IterableOnceOps.size$(IterableOnce.scala:841)
        at scala.collection.AbstractIterator.size(Iterator.scala:1300)
        at io.joern.javasrc2cpg.passes.TypeInferencePass.isMatchingMethod(TypeInferencePass.scala:34)
        at io.joern.javasrc2cpg.passes.TypeInferencePass.$anonfun$2(TypeInferencePass.scala:68)
        at scala.collection.IterableOnceOps.find(IterableOnce.scala:634)
        at scala.collection.IterableOnceOps.find$(IterableOnce.scala:630)
        at scala.collection.AbstractIterator.find(Iterator.scala:1300)
        at io.joern.javasrc2cpg.passes.TypeInferencePass.getReplacementMethod$$anonfun$1(TypeInferencePass.scala:68)
        at scala.Option.getOrElse(Option.scala:201)
        at io.joern.javasrc2cpg.passes.TypeInferencePass.getReplacementMethod(TypeInferencePass.scala:75)
        at io.joern.javasrc2cpg.passes.TypeInferencePass.runOnPart(TypeInferencePass.scala:78)
        at io.joern.javasrc2cpg.passes.TypeInferencePass.runOnPart(TypeInferencePass.scala:77)
        at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore$$anonfun$1(ParallelCpgPass.scala:95)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**To Reproduce**
I am trying to find an open source repository that can duplicate this issue

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: MacOS 13
 - Joern Version: f253a0e1 
 - Java version: 20

**Comment by mpollmeier** [comment]
Hard to say. Can you run again with https://github.com/joernio/joern/tree/michael/issue-3073/debug ? I separated the calls in that one long line, so that we can see where this is coming from. 

```
git fetch
git checkout michael/issue-3073/debug
sbt stage
./joern
```

Other than that, maybe you can bissect the source until it still contains this issue while being sharable here.
