### ISSUE TITLE
Parser error in rubysrc2cpg due to null context 

### ISSUE THREAD

**Issue by tuxology** [joernio/joern#3126]
**Describe the bug**

We are unable to generate CPG for the following code due to empty context in compoundStatement

```
MyClass = Class.new do
end
```

Generated Parse Tree:
![image](https://github.com/joernio/joern/assets/3373857/8683dfec-7823-43ed-acc8-b87e7419a685)

**Error Log**
```
Cannot invoke "io.joern.rubysrc2cpg.parser.RubyParser$StatementsContext.getText()" because "ctxStmt" is null
java.lang.NullPointerException: Cannot invoke "io.joern.rubysrc2cpg.parser.RubyParser$StatementsContext.getText()" because "ctxStmt" is null
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForBlockMethod(AstCreator.scala:1468)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForChainedInvocationPrimaryContext(AstCreator.scala:520)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForPrimaryContext(AstCreator.scala:344)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForExpressionContext(AstCreator.scala:353)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForExpressionOrCommand(AstForStatementsCreator.scala:206)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForExpressionOrCommand$(AstForStatementsCreator.scala:24)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForExpressionOrCommand(AstCreator.scala:23)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.$anonfun$1(AstCreator.scala:237)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.convert.JavaCollectionWrappers$JListWrapper.flatMap(JavaCollectionWrappers.scala:107)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForMultipleRightHandSideContext(AstCreator.scala:237)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForSingleAssignmentExpressionContext(AstCreator.scala:252)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForExpressionContext(AstCreator.scala:368)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForExpressionOrCommand(AstForStatementsCreator.scala:206)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForExpressionOrCommand$(AstForStatementsCreator.scala:24)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForExpressionOrCommand(AstCreator.scala:23)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForStatement(AstForStatementsCreator.scala:198)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForStatement$(AstForStatementsCreator.scala:24)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForStatement(AstCreator.scala:23)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.$anonfun$8(AstForStatementsCreator.scala:166)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.convert.JavaCollectionWrappers$JCollectionWrapper.flatMap(JavaCollectionWrappers.scala:72)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForStatements(AstForStatementsCreator.scala:182)
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForStatements$(AstForStatementsCreator.scala:24)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForStatements(AstCreator.scala:23)
	at io.joern.rubysrc2cpg.astcreation.AstCreator.createAst(AstCreator.scala:118)
	at io.joern.rubysrc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:26)
	at io.joern.rubysrc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:24)
	at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore$$anonfun$1(ParallelCpgPass.scala:95)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**To Reproduce**
 - Enable following test in Ruby https://github.com/joernio/joern/blob/master/joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/TypeDeclAstCreationPassTest.scala#L24 
 - Run test and observe error

**Expected behavior**
CPG gets generated with no errors

**Comment by tuxology** [comment]
Fix for #3077 is dependent on this
