### ISSUE TITLE
[Bug]java.lang.IllegalArgumentException: Unknown ansi-escape at index 718 inside string cannot be parsed into an fansi.Str

### ISSUE THREAD

**Issue by bczhaoa** [joernio/joern#3400]
D:\joern\2.0.33\joern-cli>joern

     ██╗ ██████╗ ███████╗██████╗ ███╗   ██╗
     ██║██╔═══██╗██╔════╝██╔══██╗████╗  ██║
     ██║██║   ██║█████╗  ██████╔╝██╔██╗ ██║
██   ██║██║   ██║██╔══╝  ██╔══██╗██║╚██╗██║
╚█████╔╝╚██████╔╝███████╗██║  ██║██║ ╚████║
 ╚════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝
Version: 2.0.33
Type `help` to begin

joern> importCode(inputPath="D:\\SelectiveUt-Code-Test\\InventoryDMService-br_NCEV1R23C00_Master\\InventoryDMService-br_NCEV1R23C00_Master", projectName="InventoryDMService69")
Using generator for language: NEWC: CCpgGenerator
Creating project `InventoryDMService69` for code at `D:\SelectiveUt-Code-Test\InventoryDMService-br_NCEV1R23C00_Master\InventoryDMService-br_NCEV1R23C00_Master`
=======================================================================================================
Invoking CPG generator in a separate process. Note that the new process will consume additional memory.
If you are importing a large codebase (and/or running into memory issues), please try the following:
1) exit joern
2) invoke the frontend: D:\joern\2.0.33\joern-cli\c2cpg.bat -J-Xmx8136m D:\SelectiveUt-Code-Test\InventoryDMService-br_NCEV1R23C00_Master\InventoryDMService-br_NCEV1R23C00_Master --output D:\joern\2.0.33\joern-cli\workspace\InventoryDMService69\cpg.bin.zip
3) start joern, import the cpg: `importCpg("path/to/cpg")`
=======================================================================================================

moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: D:\joern\2.0.33\joern-cli\workspace\InventoryDMService69\cpg.bin.tmp
Code successfully imported. You can now query it using `cpg`.
For an overview of all imported code, type `workspace`.
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
val res0: io.shiftleft.codepropertygraph.Cpg = Cpg (Graph [510445 nodes])

joern> cpg.method.l
java.lang.IllegalArgumentException: Unknown ansi-escape at index 718 inside string cannot be parsed into an fansi.Str
  at fansi.ErrorMode$Throw$.handle(Fansi.scala:440)
  at fansi.Str$.apply(Fansi.scala:280)
  at fansi.Str$.implicitApply(Fansi.scala:227)
  at replpp.PPrinter$.replpp$PPrinter$$anon$2$$_$rec$$anonfun$1(PPrinter.scala:46)
  at pprint.Result$.fromString(Result.scala:53)

**Comment by max-leuthaeuser** [comment]
@mpollmeier 
Looks like something for you.
(https://github.com/mpollmeier/scala-repl-pp/blob/main/core/src/main/scala/replpp/PPrinter.scala#L46).

But I guess we need a reproducer.
@bczhaoa Is the code you are scanning somewhere available?
