### ISSUE TITLE
[Bug] RubyParser

### ISSUE THREAD

**Issue by rahul-privado** [joernio/joern#3462]
**Describe the bug**
The below code has a parsing failure

**To Reproduce**
The code is below

```
RSpec.describe API::SomeVersion::Something do
   describe '#something' do
    context 'when some condition is met' do
      before do
        allow(SomeModule::SomeConst)
          .to receive(:for)
          .with(somethingelse)
          .and_return(nil)
      end 
    end 
  end 
end
```

It does not parse in the ANTLR preview in IntelliJ. What confirms that this is a parser issue is that we get the below stack when we import this code. So this is not a case of the code successfully parsing but the ANTLR plugin not parsing it.

```
java.lang.NullPointerException: Cannot invoke "io.joern.rubysrc2cpg.parser.RubyParser$ArgumentsContext.argument()" because "ctx" is null
	at io.joern.rubysrc2cpg.astcreation.AstForDeclarationsCreator.astForArguments(AstForDeclarationsCreator.scala:17) ~[io.joern.rubysrc2cpg-2.0.45+4-a5d0c8b0+20230810-1115.jar:2.0.45+4-a5d0c8b0+20230810-1115]
	at io.joern.rubysrc2cpg.astcreation.AstForDeclarationsCreator.astForArguments$(AstForDeclarationsCreator.scala:13) ~[io.joern.rubysrc2cpg-2.0.45+4-a5d0c8b0+20230810-1115.jar:2.0.45+4-a5d0c8b0+20230810-1115]
	at io.joern.rubysrc2cpg.astcreation.AstCreator.astForArguments(AstCreator.scala:24) ~[io.joern.rubysrc2cpg-2.0.45+4-a5d0c8b0+20230810-1115.jar:2.0.45+4-a5d0c8b0+20230810-1115]
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForMemberAccessCommand(AstForStatementsCreator.scala:307) ~[io.joern.rubysrc2cpg-2.0.45+4-a5d0c8b0+20230810-1115.jar:2.0.45+4-a5d0c8b0+20230810-1115]
	at io.joern.rubysrc2cpg.astcreation.AstForStatementsCreator.astForMemberAccessCommand$(AstForStatementsCreator.scala:27) ~[io.joern.rubysrc2cpg-2.0.45+4-a5d0c8b0+20230810-1115.jar:2.0.45+4-a5d0c8b0+20230810-1115]
```

This code has been taken from valid customer code and the names have been changed. So this should be valid Ruby code.

**Expected behavior**
Parsing should succeed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS
 - Joern Version 
 - Java version

**Additional context**

**Comment by xavierpinho** [comment]
The issue is with that line break between `allow` and `.to`. A smaller sample could be 

```ruby
f(0)
    .m1 g(2)
```
Note: If it were on the same line (same meaning), `f(0).m1 g(2)`, it would parse correctly.
