### ISSUE TITLE
[Bug] script run error 'invalid character in unicode escape sequence' on windows

### ISSUE THREAD

**Issue by riusksk** [joernio/joern#3494]
**Describe the bug**
Running a scala script file on windows will result in an error due to a path problem, because the path separator on windows is `\`, which is treated as an escape by joern, resulting in a path error.

so, the windows path needs to be escaped or treated as a raw string

**To Reproduce**
exec the follow cmd, `graph-for-funcs.scala` is [here](https://github.com/bstee615/graph-for-funcs.scala/blob/main/graph-for-funcs.scala):
`joern.bat --script .\graph-for-funcs.scala cpg.bin`

then trigger an error:
`
executing .\graph-for-funcs.scala
-- Error: C:\Users\xxx~1\AppData\Local\Temp\scala-repl-pp-script-with-predef8668210283021329719.sc:231:15
231 |importCpg("C:\Users\xxx\Downloads\cpg.bin")
    |               ^
    |               invalid character in unicode escape sequence
-- Error: C:\Users\xxx~1\AppData\Local\Temp\scala-repl-pp-script-with-predef8668210283021329719.sc:231:20
231 |importCpg("C:\Users\xxx\Downloads\cpg.bin")
    |                    ^
    |                    invalid escape character
-- Error: C:\Users\xxx~1\AppData\Local\Temp\scala-repl-pp-script-with-predef8668210283021329719.sc:231:30
231 |importCpg("C:\Users\xxx\Downloads\cpg.bin")
    |                              ^
    |                              invalid escape character
-- Error: C:\Users\xxx~1\AppData\Local\Temp\scala-repl-pp-script-with-predef8668210283021329719.sc:231:40
231 |importCpg("C:\Users\xxx\Downloads\cpg.bin")
    |                                        ^
    |                                        invalid escape character
4 errors found
error during script execution: Errors encountered during compilation - try `--verbose` for more output
note: line numbers may not be accurate - to help with debugging, the final scriptContent is at C:\Users\xxx~1\AppData\Local\Temp\scala-repl-pp-script-with-predef8668210283021329719.sc
Exception in thread "main" replpp.scripting.ScriptingException: Errors encountered during compilation - try `--verbose` for more output
        at replpp.scripting.ScriptingException$.apply(ScriptingDriver.scala:74)
        at replpp.scripting.ScriptingDriver.compileAndRun$$anonfun$1(ScriptingDriver.scala:49)
        at scala.Option.flatMap(Option.scala:283)
        at replpp.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:61)
        at replpp.scripting.NonForkingScriptRunner$.exec(NonForkingScriptRunner.scala:59)
        at replpp.scripting.NonForkingScriptRunner$.main(NonForkingScriptRunner.scala:24)
        at replpp.scripting.NonForkingScriptRunner.main(NonForkingScriptRunner.scala)`

**Expected behavior**
The graph-for-funcs.scala is executed successfully, and output json file.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Joern Version : 2.0.50
 - Java version: openjdk 17.0.1 2021-10-19

**Comment by riusksk** [comment]
Modify Breadcrumbsjoern/console/src/main/scala/io/joern/console/BridgeBase.scala
may be fixed (not verified due to missing compilation environment):

```
$ diff -u BridgeBase.scala BridgeBase-fix.scala
--- BridgeBase.scala    2023-08-15 10:09:32.956455100 +0800
+++ BridgeBase-fix.scala        2023-08-15 10:19:30.102916200 +0800
@@ -223,11 +223,14 @@

 trait InteractiveShell { this: BridgeBase =>
   protected def startInteractiveShell(config: Config) = {
+    val isWindows = System.getProperty("os.name").toLowerCase().contains("win")
     val replConfig = config.cpgToLoad.map { cpgFile =>
-      "importCpg(\"" + cpgFile + "\")"
+      val modifiedPath = if (isWindows) cpgFile.getPath.replace("\\", "/") else cpgFile.getPath
+      "importCpg(\"" + modifiedPath + "\")"
     } ++ config.forInputPath.map { name =>
+      val modifiedName = if (isWindows) name.replace("\\", "/") else name
       s"""
-         |openForInputPath(\"$name\")
+         |openForInputPath(\"$modifiedName\")
          |""".stripMargin
     }

@@ -278,13 +281,17 @@

   /** For the given config, generate a list of commands to import the CPG
     */
-  private def importCpgCode(config: Config): List[String] = {
-    config.cpgToLoad.map { cpgFile =>
-      "importCpg(\"" + cpgFile + "\")"
-    }.toList ++ config.forInputPath.map { name =>
-      s"""
-         |openForInputPath(\"$name\")
-         |""".stripMargin
+ private def importCpgCode(config: Config): List[String] = {
+  val isWindows = System.getProperty("os.name").toLowerCase().contains("win")
+
+  config.cpgToLoad.map { cpgFile =>
+    val modifiedPath = if (isWindows) cpgFile.getPath.replace("\\", "/") else cpgFile.getPath
+    "importCpg(\"" + modifiedPath + "\")"
+  }.toList ++ config.forInputPath.map { name =>
+    val modifiedName = if (isWindows) name.replace("\\", "/") else name
+    s"""
+       |openForInputPath(\"$modifiedName\")
+       |""".stripMargin
     }
   }
 }
```
