### ISSUE TITLE
[Bug] Script --param parsing error on windows

### ISSUE THREAD

**Issue by riusksk** [joernio/joern#3507]
**Describe the bug**
Script parameter parsing error on windows, resulting in scripts not running correctly.

**To Reproduce**
1. create test.sc script file:
```
@main def exec(cpgFile: String, outFile: String) = {
   loadCpg(cpgFile)
   cpg.method.name #> outFile
}
```
2. run cmd: `joern --script test.sc --param cpgFile=cpg.bin --param outFile=output.log`
```
Error: Option --param failed when given 'outFile'. unable to parse param input outFile
Try --help for more information.
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627)
        at scala.None$.get(Option.scala:626)
        at io.joern.console.BridgeBase.parseConfig(BridgeBase.scala:181)
        at io.joern.console.BridgeBase.parseConfig$(BridgeBase.scala:44)
        at io.joern.joerncli.console.ReplBridge$.parseConfig(ReplBridge.scala:7)
        at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:12)
        at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala)
```

**Expected behavior**
output method name

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Joern Version : 2.0.50
 - Java version: openjdk 17.0.1 2021-10-19

**Additional context**

**Comment by max-leuthaeuser** [comment]
Afaik, on Windows params need to be wrapped in triple quotes (`--param """outFile=output.log"""`).

**Comment by riusksk** [comment]
> Afaik, on Windows params need to be wrapped in triple quotes (`--param """outFile=output.log"""`).

it's ok, thank you
