### ISSUE TITLE
[Bug] Javasrc2cpg crashes

### ISSUE THREAD

**Issue by itsacoderepo** [joernio/joern#3511]
**Describe the bug**
Multiple crashes on importing the follwing code snippet 

```
import foo.bar.common.utils.ZipUtils;
@Metadata()
public final class ZipUtils {
    public static final Companion Companion = new Companion((DefaultConstructorMarker) null);
    @JvmStatic
    public static final void unzip(String str, String str2, Callback callback) {
        Companion.unzip(str, str2, callback);
    }

    @Metadata()
    public static final class Companion {
        public Companion(DefaultConstructorMarker defaultConstructorMarker) {
            this();
        }
    }
}
   ```

**To Reproduce**
1.  Start joern 
2. Import Code:
```
importCode.java.fromString("""
      import foo.bar.common.utils.ZipUtils;
      @Metadata()
      public final class ZipUtils {
          public static final Companion Companion = new Companion((DefaultConstructorMarker) null);
          @JvmStatic
          public static final void unzip(String str, String str2, Callback callback) {
              Companion.unzip(str, str2, callback);
          }
     
          @Metadata()
          public static final class Companion {
              public Companion(DefaultConstructorMarker defaultConstructorMarker) {
                  this();
              }
          }
      }
      """)
```
6. See error
```
Creating project `console1340944282895125967` for code at `/tmp/console1340944282895125967`
=======================================================================================================
Invoking CPG generator in a separate process. Note that the new process will consume additional memory.
If you are importing a large codebase (and/or running into memory issues), please try the following:
1) exit joern
2) invoke the frontend: /home/test/bin/joern/joern-cli/javasrc2cpg -J-Xmx7712m /tmp/console1340944282895125967 --output /home/test/bin/joern/joern-cli/workspace/console1340944282895125967/cpg.bin.zip
3) start joern, import the cpg: `importCpg("path/to/cpg")`
=======================================================================================================

Exception in thread "Writer" java.lang.RuntimeException: Edge with type='REF' with direction='IN' not supported by nodeType='IMPORT'
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:651)
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:630)
	at overflowdb.NodeDb.addEdgeSilentImpl(NodeDb.java:324)
	at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
	at overflowdb.NodeRef.addEdgeSilentImpl(NodeRef.java:168)
	at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
	at overflowdb.BatchedUpdate$DiffGraphApplier.applyChange(BatchedUpdate.java:304)
	at overflowdb.BatchedUpdate$DiffGraphApplier.run(BatchedUpdate.java:249)
	at overflowdb.BatchedUpdate.applyDiff(BatchedUpdate.java:17)
	at io.shiftleft.passes.ConcurrentWriterCpgPass$Writer.run(ParallelCpgPass.scala:151)
	at java.base/java.lang.Thread.run(Thread.java:1623)
java.lang.RuntimeException: Failure in diffgraph application
	at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore(ParallelCpgPass.scala:114)
	at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
	at io.joern.javasrc2cpg.JavaSrc2Cpg.createCpg$$anonfun$1(JavaSrc2Cpg.scala:32)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:15)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:10)
	at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg$$anonfun$1$$anonfun$1(X2Cpg.scala:252)
	at io.joern.x2cpg.X2Cpg$.$anonfun$adapted$1(X2Cpg.scala:253)
	at scala.util.Try$.apply(Try.scala:210)
	at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg$$anonfun$1(X2Cpg.scala:253)
	at scala.util.Try$.apply(Try.scala:210)
	at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg(X2Cpg.scala:259)
	at io.joern.javasrc2cpg.JavaSrc2Cpg.createCpg(JavaSrc2Cpg.scala:37)
	at io.joern.javasrc2cpg.JavaSrc2Cpg.createCpg(JavaSrc2Cpg.scala:28)
	at io.joern.x2cpg.X2CpgFrontend.run$$anonfun$1(X2Cpg.scala:123)
	at io.joern.x2cpg.X2Cpg$.withErrorsToConsole(X2Cpg.scala:266)
	at io.joern.x2cpg.X2CpgFrontend.run(X2Cpg.scala:129)
	at io.joern.x2cpg.X2CpgFrontend.run$(X2Cpg.scala:111)
	at io.joern.javasrc2cpg.JavaSrc2Cpg.run(JavaSrc2Cpg.scala:23)
	at io.joern.javasrc2cpg.Main$.run(Main.scala:125)
	at io.joern.javasrc2cpg.Main$.run(Main.scala:121)
	at io.joern.x2cpg.X2CpgMain.main(X2Cpg.scala:94)
	at io.joern.javasrc2cpg.Main$.main(Main.scala:117)
	at io.joern.javasrc2cpg.Main.main(Main.scala)
Caused by: java.lang.RuntimeException: Edge with type='REF' with direction='IN' not supported by nodeType='IMPORT'
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:651)
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:630)
	at overflowdb.NodeDb.addEdgeSilentImpl(NodeDb.java:324)
	at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
	at overflowdb.NodeRef.addEdgeSilentImpl(NodeRef.java:168)
	at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
	at overflowdb.BatchedUpdate$DiffGraphApplier.applyChange(BatchedUpdate.java:304)
	at overflowdb.BatchedUpdate$DiffGraphApplier.run(BatchedUpdate.java:249)
	at overflowdb.BatchedUpdate.applyDiff(BatchedUpdate.java:17)
	at io.shiftleft.passes.ConcurrentWriterCpgPass$Writer.run(ParallelCpgPass.scala:151)
	at java.base/java.lang.Thread.run(Thread.java:1623)
moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: /home/test/bin/joern/joern-cli/workspace/console1340944282895125967/cpg.bin.tmp
Code successfully imported. You can now query it using `cpg`.
For an overview of all imported code, type `workspace`.
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
2023-08-15 17:18:29.264 ERROR CpgPassBase: Pass io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass failed
java.lang.ClassCastException: null
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:693) ~[?:?]
	at io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:152) ~[io.shiftleft.codepropertygraph_3-1.4.1.jar:1.4.1]
	at io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:74) ~[io.shiftleft.codepropertygraph_3-1.4.1.jar:1.4.1]
	at io.shiftleft.semanticcpg.layers.LayerCreator.runPass(LayerCreator.scala:53) ~[io.joern.semanticcpg-2.0.51.jar:2.0.51]
	at io.joern.dataflowengineoss.layers.dataflows.OssDataFlow.create$$anonfun$1(OssDataFlow.scala:31) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15) ~[org.scala-lang.scala3-library_3-3.3.0.jar:3.3.0]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) ~[org.scala-lang.scala3-library_3-3.3.0.jar:3.3.0]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.dataflowengineoss.layers.dataflows.OssDataFlow.create(OssDataFlow.scala:32) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at io.shiftleft.semanticcpg.layers.LayerCreator.run(LayerCreator.scala:32) ~[io.joern.semanticcpg-2.0.51.jar:2.0.51]
	at io.joern.console.Console.runCreator(Console.scala:437) ~[io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.console.Console._runAnalyzer$$anonfun$1(Console.scala:426) ~[io.joern.console-2.0.51.jar:2.0.51]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15) ~[org.scala-lang.scala3-library_3-3.3.0.jar:3.3.0]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) ~[org.scala-lang.scala3-library_3-3.3.0.jar:3.3.0]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.console.Console._runAnalyzer(Console.scala:427) ~[io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.joerncli.console.JoernConsole.applyDefaultOverlays(JoernConsole.scala:44) ~[io.joern.joern-cli-2.0.51.jar:2.0.51]
	at io.joern.console.cpgcreation.ImportCode.apply$$anonfun$1(ImportCode.scala:147) ~[io.joern.console-2.0.51.jar:2.0.51]
	at scala.Option.map(Option.scala:242) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$apply(ImportCode.scala:148) ~[io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.console.cpgcreation.ImportCode$Frontend.apply(ImportCode.scala:84) ~[io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.console.cpgcreation.ImportCode$SourceBasedFrontend.fromString$$anonfun$1(ImportCode.scala:96) ~[io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.console.cpgcreation.ImportCode.$anonfun$2(ImportCode.scala:110) ~[io.joern.console-2.0.51.jar:2.0.51]
	at scala.util.Try$.apply(Try.scala:210) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$withCodeInTmpFile(ImportCode.scala:111) ~[io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.console.cpgcreation.ImportCode$SourceBasedFrontend.fromString(ImportCode.scala:96) ~[io.joern.console-2.0.51.jar:2.0.51]
	at rs$line$2$.<clinit>(rs$line$2:1) ~[?:?]
	at rs$line$2.res0(rs$line$2) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at replpp.Rendering.$anonfun$4(Rendering.scala:93) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at scala.Option.flatMap(Option.scala:283) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.Rendering.valueOf(Rendering.scala:93) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.Rendering.renderVal(Rendering.scala:135) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.DottyReplDriver.$anonfun$7(DottyReplDriver.scala:365) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15) ~[org.scala-lang.scala3-library_3-3.3.0.jar:3.3.0]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) ~[org.scala-lang.scala3-library_3-3.3.0.jar:3.3.0]
	at scala.collection.immutable.List.foreach(List.scala:333) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.DottyReplDriver.extractAndFormatMembers$1(DottyReplDriver.scala:371) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.DottyReplDriver.renderDefinitions$$anonfun$2(DottyReplDriver.scala:403) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at scala.Option.map(Option.scala:242) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.DottyReplDriver.renderDefinitions(DottyReplDriver.scala:408) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.DottyReplDriver.compile$$anonfun$2(DottyReplDriver.scala:305) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at scala.util.Either.fold(Either.scala:189) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.DottyReplDriver.compile(DottyReplDriver.scala:323) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.DottyReplDriver.interpret(DottyReplDriver.scala:246) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.ReplDriverBase.interpretInput(ReplDriverBase.scala:62) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.ReplDriver.loop$1$$anonfun$1(ReplDriver.scala:47) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at scala.util.Try$.apply(Try.scala:210) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.ReplDriver.loop$1(ReplDriver.scala:48) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.ReplDriver.runUntilQuit$$anonfun$2(ReplDriver.scala:63) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.DottyReplDriver.withRedirectedOutput(DottyReplDriver.scala:188) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.DottyReplDriver.runBody$$anonfun$1(DottyReplDriver.scala:162) ~[com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80) [org.scala-lang.scala3-compiler_3-3.3.0.jar:3.3.0]
	at replpp.DottyReplDriver.runBody(DottyReplDriver.scala:162) [com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.ReplDriver.runUntilQuit(ReplDriver.scala:63) [com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at replpp.InteractiveShell$.run(InteractiveShell.scala:39) [com.michaelpollmeier.scala-repl-pp-core_3-0.1.36.jar:0.1.36]
	at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:237) [io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:224) [io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:7) [io.joern.joern-cli-2.0.51.jar:2.0.51]
	at io.joern.console.BridgeBase.run(BridgeBase.scala:204) [io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.console.BridgeBase.run$(BridgeBase.scala:44) [io.joern.console-2.0.51.jar:2.0.51]
	at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:7) [io.joern.joern-cli-2.0.51.jar:2.0.51]
	at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:12) [io.joern.joern-cli-2.0.51.jar:2.0.51]
	at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala) [io.joern.joern-cli-2.0.51.jar:2.0.51]
Caused by: java.lang.ClassCastException: class io.shiftleft.codepropertygraph.generated.nodes.Import cannot be cast to class io.shiftleft.codepropertygraph.generated.nodes.Declaration (io.shiftleft.codepropertygraph.generated.nodes.Import and io.shiftleft.codepropertygraph.generated.nodes.Declaration are in unnamed module of loader java.net.URLClassLoader @183fc2fa)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.immutable.List.prependedAll(List.scala:152) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1288) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1288) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.AbstractIterator.toList(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at overflowdb.traversal.TraversalSugarExt$.l$extension(Traversal.scala:24) ~[io.shiftleft.overflowdb-traversal_3-1.177.jar:1.177]
	at io.joern.dataflowengineoss.package$.identifierToFirstUsages(package.scala:13) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.$anonfun$3(DdgGenerator.scala:174) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.Iterator$$anon$8.hasNext(Iterator.scala:562) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addEdgesToCapturedIdentifiersAndParameters$1(DdgGenerator.scala:190) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addReachingDefEdges(DdgGenerator.scala:215) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:33) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:23) ~[io.joern.dataflowengineoss-2.0.51.jar:2.0.51]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:147) ~[io.shiftleft.codepropertygraph_3-1.4.1.jar:1.4.1]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:146) ~[io.shiftleft.codepropertygraph_3-1.4.1.jar:1.4.1]
	at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934) ~[?:?]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
io.joern.console.ConsoleException: unable to generate cpg from given String
Caused by: java.lang.ClassCastException: java.lang.ClassCastException: class io.shiftleft.codepropertygraph.generated.nodes.Import cannot be cast to class io.shiftleft.codepropertygraph.generated.nodes.Declaration (io.shiftleft.codepropertygraph.generated.nodes.Import and io.shiftleft.codepropertygraph.generated.nodes.Declaration are in unnamed module of loader java.net.URLClassLoader @183fc2fa)
  at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
  at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
  at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
  at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
  at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
  at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:693)
  at io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:152)
  at io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:74)
  at io.shiftleft.semanticcpg.layers.LayerCreator.runPass(LayerCreator.scala:53)
  at io.joern.dataflowengineoss.layers.dataflows.OssDataFlow.create$$anonfun$1(OssDataFlow.scala:31)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
  at io.joern.dataflowengineoss.layers.dataflows.OssDataFlow.create(OssDataFlow.scala:32)
  at io.shiftleft.semanticcpg.layers.LayerCreator.run(LayerCreator.scala:32)
  at io.joern.console.Console.runCreator(Console.scala:437)
  at io.joern.console.Console._runAnalyzer$$anonfun$1(Console.scala:426)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
  at io.joern.console.Console._runAnalyzer(Console.scala:427)
  at io.joern.joerncli.console.JoernConsole.applyDefaultOverlays(JoernConsole.scala:44)
  at io.joern.console.cpgcreation.ImportCode.apply$$anonfun$1(ImportCode.scala:147)
  at scala.Option.map(Option.scala:242)
  at io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$apply(ImportCode.scala:148)
  at io.joern.console.cpgcreation.ImportCode$Frontend.apply(ImportCode.scala:84)
  at io.joern.console.cpgcreation.ImportCode$SourceBasedFrontend.fromString$$anonfun$1(ImportCode.scala:96)
  at io.joern.console.cpgcreation.ImportCode.$anonfun$2(ImportCode.scala:110)
  at scala.util.Try$.apply(Try.scala:210)
  at io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$withCodeInTmpFile(ImportCode.scala:111)
  at io.joern.console.cpgcreation.ImportCode$SourceBasedFrontend.fromString(ImportCode.scala:96)
  ... 39 elided
Caused by: java.lang.ClassCastException: class io.shiftleft.codepropertygraph.generated.nodes.Import cannot be cast to class io.shiftleft.codepropertygraph.generated.nodes.Declaration (io.shiftleft.codepropertygraph.generated.nodes.Import and io.shiftleft.codepropertygraph.generated.nodes.Declaration are in unnamed module of loader java.net.URLClassLoader @183fc2fa)
  at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
  at scala.collection.immutable.List.prependedAll(List.scala:152)
  at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1288)
  at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1288)
  at scala.collection.AbstractIterator.toList(Iterator.scala:1300)
  at overflowdb.traversal.TraversalSugarExt$.l$extension(Traversal.scala:24)
  at io.joern.dataflowengineoss.package$.identifierToFirstUsages(package.scala:13)
  at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.$anonfun$3(DdgGenerator.scala:174)
  at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
  at scala.collection.Iterator$$anon$8.hasNext(Iterator.scala:562)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
  at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addEdgesToCapturedIdentifiersAndParameters$1(DdgGenerator.scala:190)
  at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addReachingDefEdges(DdgGenerator.scala:215)
  at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:33)
  at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:23)
  at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:147)
  at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:146)
  at java.base/java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220)
  at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
  at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
  at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
  at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
**Expected behavior**
No crashes

**Desktop (please complete the following information):**
 - joern "2.0.51"

**Comment by johannescoetzee** [comment]
The issue here was that the code snippet was invalid java code produced by a decompiler and this triggered a crash that wasn't caught correctly. This has since been fixed:

```
joern> importCode.java.fromString("""
     |       import foo.bar.common.utils.ZipUtils;
     |       @Metadata()
     |       public final class ZipUtils {
     |           public static final Companion Companion = new Companion((DefaultConstructorMarker) null);
     |           @JvmStatic
     |           public static final void unzip(String str, String str2, Callback callback) {
     |               Companion.unzip(str, str2, callback);
     |           }
     |      
     |           @Metadata()
     |           public static final class Companion {
     |               public Companion(DefaultConstructorMarker defaultConstructorMarker) {
     |                   this();
     |               }
     |           }
     |       }
     |       """)

...

moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: ...
Code successfully imported. You can now query it using `cpg`.
For an overview of all imported code, type `workspace`.
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
val res0: io.shiftleft.codepropertygraph.Cpg = Cpg (Graph [165 nodes])
```
