### ISSUE TITLE
[Q] How can i  import a local jar to joern dependencies?

### ISSUE THREAD

**Issue by bczhaoa** [joernio/joern#3573]
i can't find how import a local jar to joern dependencies by doc : https://docs.joern.io/shell/
i try this, but error. 
![image](https://github.com/joernio/joern/assets/96362132/16f0ddcd-02d7-4d73-bcea-dd3a3426f907)
D:\bigdata\joern\2.0.41\joern-cli>joern --dep lib/JoernPlusParser-0.0.1.jar
Exception in thread "main" java.lang.AssertionError: error while trying to parse the following dependency coordinate: lib/JoernPlusParser-0.0.1.jar
at replpp.Dependencies$$anon$1.applyOrElse(Dependencies.scala:55)
at replpp.Dependencies$$anon$1.applyOrElse(Dependencies.scala:54)
at scala.util.Failure.recover(Try.scala:233)
at replpp.Dependencies$.parseDependency(Dependencies.scala:55)
at replpp.Dependencies$.parseDependencies$$anonfun$1(Dependencies.scala:44)
at scala.collection.immutable.List.map(List.scala:246)
at scala.collection.immutable.List.map(List.scala:79)
at replpp.Dependencies$.parseDependencies(Dependencies.scala:44)
at replpp.Dependencies$.resolve$$anonfun$1(Dependencies.scala:18)
at scala.util.Success.flatMap(Try.scala:258)
at replpp.Dependencies$.resolve(Dependencies.scala:28)
at replpp.package$.dependencyArtifacts(package.scala:68)
at replpp.package$.classpath(package.scala:45)
at replpp.package$.compilerArgs(package.scala:35)
at replpp.InteractiveShell$.run(InteractiveShell.scala:14)
at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:237)
at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:224)
at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:7)
at io.joern.console.BridgeBase.run(BridgeBase.scala:204)
at io.joern.console.BridgeBase.run$(BridgeBase.scala:44)
at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:7)
at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:12)
at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala)
Caused by: scala.MatchError: [Ljava.lang.String;@763cf5b9 (of class [Ljava.lang.String;)
at coursier.parse.DependencyParser$.javaOrScalaDependencyParams(DependencyParser.scala:176)
at coursier.parse.DependencyParser$.dependencyParams(DependencyParser.scala:356)
at coursier.parse.DependencyParser$.dependency(DependencyParser.scala:32)
at coursier.parse.DependencyParser$.dependency(DependencyParser.scala:25)
at replpp.Dependencies$.parseDependency$$anonfun$1(Dependencies.scala:49)
at scala.util.Try$.apply(Try.scala:210)
at replpp.Dependencies$.parseDependency(Dependencies.scala:54)
... 19 more

**Comment by bczhaoa** [comment]
![image](https://github.com/joernio/joern/assets/96362132/17d5fe84-0b08-4712-83af-9f623f5934f3)

**Comment by bczhaoa** [comment]
![image](https://github.com/joernio/joern/assets/96362132/79596946-81ad-4a50-84bc-e0897879035f)

**Comment by bczhaoa** [comment]
D:\bigdata\joern\2.0.41\joern-cli>joern --dep lib/JoernPlusParser-0.0.1.jar
Exception in thread "main" java.lang.AssertionError: error while trying to parse the following dependency coordinate: `lib/JoernPlusParser-0.0.1.jar`
        at replpp.Dependencies$$anon$1.applyOrElse(Dependencies.scala:55)
        at replpp.Dependencies$$anon$1.applyOrElse(Dependencies.scala:54)
        at scala.util.Failure.recover(Try.scala:233)
        at replpp.Dependencies$.parseDependency(Dependencies.scala:55)
        at replpp.Dependencies$.parseDependencies$$anonfun$1(Dependencies.scala:44)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at replpp.Dependencies$.parseDependencies(Dependencies.scala:44)
        at replpp.Dependencies$.resolve$$anonfun$1(Dependencies.scala:18)
        at scala.util.Success.flatMap(Try.scala:258)
        at replpp.Dependencies$.resolve(Dependencies.scala:28)
        at replpp.package$.dependencyArtifacts(package.scala:68)
        at replpp.package$.classpath(package.scala:45)
        at replpp.package$.compilerArgs(package.scala:35)
        at replpp.InteractiveShell$.run(InteractiveShell.scala:14)
        at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:237)
        at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:224)
        at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:7)
        at io.joern.console.BridgeBase.run(BridgeBase.scala:204)
        at io.joern.console.BridgeBase.run$(BridgeBase.scala:44)
        at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:7)
        at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:12)
        at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala)
Caused by: scala.MatchError: [Ljava.lang.String;@763cf5b9 (of class [Ljava.lang.String;)
        at coursier.parse.DependencyParser$.javaOrScalaDependencyParams(DependencyParser.scala:176)
        at coursier.parse.DependencyParser$.dependencyParams(DependencyParser.scala:356)
        at coursier.parse.DependencyParser$.dependency(DependencyParser.scala:32)
        at coursier.parse.DependencyParser$.dependency(DependencyParser.scala:25)
        at replpp.Dependencies$.parseDependency$$anonfun$1(Dependencies.scala:49)
        at scala.util.Try$.apply(Try.scala:210)
        at replpp.Dependencies$.parseDependency(Dependencies.scala:54)
        ... 19 more
