### ISSUE TITLE
[Bug] c2cpg hangs for a repo with stackoverflowerror

### ISSUE THREAD

**Issue by prabhu** [joernio/joern#3609]
**Describe the bug**

https://github.com/Nheko-Reborn/mtxclient

```
~/bin/joern/joern-cli/c2cpg.sh -o /tmp/cpg.bin /mnt/work/sandbox/mtxclient

java.lang.StackOverflowError
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPDependentEvaluation.findEnclosingTemplate(CPPDependentEvaluation.java:81)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalBinding.<init>(EvalBinding.java:88)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalID.create(EvalID.java:311)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTIdExpression.getEvaluation(CPPASTIdExpression.java:144)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.LookupData.setFunctionArguments(LookupData.java:529)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.createLookupData(CPPSemantics.java:768)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.resolveBinding(CPPSemantics.java:351)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.resolveBinding(CPPVisitor.java:1514)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.createBinding(CPPVisitor.java:346)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTName.createIntermediateBinding(CPPASTName.java:67)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTNameBase.resolveBinding(CPPASTNameBase.java:111)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTRangeBasedForStatement.getImplicitNames(CPPASTRangeBasedForStatement.java:201)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.getAutoInitClauseForRangeBasedFor(CPPVisitor.java:2454)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.getInitializerClause(CPPVisitor.java:2012)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.createType(CPPVisitor.java:2019)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.VariableHelpers.createType(VariableHelpers.java:126)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPVariable.getType(CPPVariable.java:142)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalBinding.computeType(EvalBinding.java:319)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalBinding.getType(EvalBinding.java:298)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTIdExpression.getExpressionType(CPPASTIdExpression.java:153)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.getAutoInitClauseForRangeBasedFor(CPPVisitor.java:2448)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.createAutoType(CPPVisitor.java:2521)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.createType(CPPVisitor.java:2310)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.createType(CPPVisitor.java:2278)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.VariableHelpers.createType(VariableHelpers.java:117)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPVariable.getType(CPPVariable.java:142)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalBinding.computeType(EvalBinding.java:319)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalBinding.getType(EvalBinding.java:298)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.LookupData.getFunctionArgumentTypes(LookupData.java:539)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.getAssociatedScopes(CPPSemantics.java:811)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.doArgumentDependentLookup(CPPSemantics.java:688)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.resolveBinding(CPPSemantics.java:362)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.resolveBinding(CPPVisitor.java:1514)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.createBinding(CPPVisitor.java:346)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTName.createIntermediateBinding(CPPASTName.java:67)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTNameBase.resolveBinding(CPPASTNameBase.java:111)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTRangeBasedForStatement.getImplicitNames(CPPASTRangeBasedForStatement.java:201)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.getAutoInitClauseForRangeBasedFor(CPPVisitor.java:2454)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.getInitializerClause(CPPVisitor.java:2012)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPVisitor.createType(CPPVisitor.java:2019)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.VariableHelpers.createType(VariableHelpers.java:126)
```

The errors seem to differ across repeated runs, indicating multiple problematic files.

**Expected behavior**
Possibly an Eclipse CDT error.
Parsing could continue without hanging

**Screenshots**

**Desktop (please complete the following information):**
 - OS ubuntu
 - Joern Version latest
 - Java version 19

**Additional context**

**Comment by max-leuthaeuser** [comment]
Looks like a CDT issue.
Could you try it with header auto discovery?

**Comment by prabhu** [comment]
Wow! Thank you.
