### ISSUE TITLE
[GO] - Error while creating receiver node

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3667]
```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662) ~[scala-library-2.13.10.jar:?]
	at scala.collection.immutable.Nil$.head(List.scala:661) ~[scala-library-2.13.10.jar:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.processReceiverAst(AstForMethodCallExpressionCreator.scala:131) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.callMethodFullNameTypeFullNameAndSignature(AstForMethodCallExpressionCreator.scala:122) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.preReqForCallNode(AstForMethodCallExpressionCreator.scala:55) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.astForCallExpression(AstForMethodCallExpressionCreator.scala:16) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.astForCallExpression$(AstForMethodCallExpressionCreator.scala:12) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstCreator.astForCallExpression(AstCreator.scala:19) ~[classes/:?]
```

**Comment by pandurangpatil** [comment]
This ticket is related to $IndexExp handling or method being called on an array element as a receiver.

```
var test = persons[10].GetFullName()
```
