### ISSUE TITLE
[GO] - Exception in thread "Writer" java.lang.RuntimeException: Edge with type='CONDITION' with direction='IN' not supported by nodeType='LOCAL'

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3678]
```
java.lang.RuntimeException: Failure in diffgraph application
	at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore(ParallelCpgPass.scala:114)
	at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
	at io.joern.gosrc2cpg.GoSrc2Cpg.createCpg$$anonfun$1$$anonfun$1(GoSrc2Cpg.scala:31)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at better.files.Dispose.apply(Dispose.scala:75)
	at better.files.Dispose.foreach(Dispose.scala:91)
	at better.files.File$.usingTemporaryDirectory(File.scala:1320)
	at io.joern.gosrc2cpg.GoSrc2Cpg.createCpg$$anonfun$1(GoSrc2Cpg.scala:33)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:15)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:10)
	at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg$$anonfun$1$$anonfun$1(X2Cpg.scala:262)
	at io.joern.x2cpg.X2Cpg$.$anonfun$adapted$1(X2Cpg.scala:263)
	at scala.util.Try$.apply(Try.scala:210)
	at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg$$anonfun$1(X2Cpg.scala:263)
	at scala.util.Try$.apply(Try.scala:210)
	at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg(X2Cpg.scala:269)
	at io.joern.gosrc2cpg.GoSrc2Cpg.createCpg(GoSrc2Cpg.scala:34)
	at io.joern.gosrc2cpg.GoSrc2Cpg.createCpg(GoSrc2Cpg.scala:21)
	at io.joern.x2cpg.X2CpgFrontend.run$$anonfun$1(X2Cpg.scala:130)
	at io.joern.x2cpg.X2Cpg$.withErrorsToConsole(X2Cpg.scala:276)
	at io.joern.x2cpg.X2CpgFrontend.run(X2Cpg.scala:136)
	at io.joern.x2cpg.X2CpgFrontend.run$(X2Cpg.scala:118)
	at io.joern.gosrc2cpg.GoSrc2Cpg.run(GoSrc2Cpg.scala:18)
	at io.joern.gosrc2cpg.Main$.run(Main.scala:26)
	at io.joern.gosrc2cpg.Main$.run(Main.scala:24)
	at io.joern.x2cpg.X2CpgMain.main(X2Cpg.scala:101)
	at io.joern.gosrc2cpg.Main.main(Main.scala)
Caused by: java.lang.RuntimeException: Edge with type='CONDITION' with direction='IN' not supported by nodeType='LOCAL'
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:651)
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:630)
	at overflowdb.NodeDb.addEdgeSilentImpl(NodeDb.java:324)
	at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
	at overflowdb.NodeRef.addEdgeSilentImpl(NodeRef.java:168)
	at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
	at overflowdb.BatchedUpdate$DiffGraphApplier.applyChange(BatchedUpdate.java:304)
	at overflowdb.BatchedUpdate$DiffGraphApplier.run(BatchedUpdate.java:249)
	at overflowdb.BatchedUpdate.applyDiff(BatchedUpdate.java:17)
	at io.shiftleft.passes.ConcurrentWriterCpgPass$Writer.run(ParallelCpgPass.scala:151)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by pandurangpatil** [comment]
Sample to reproduce the issue

```
package main

import (
	"fmt"
)

func main() {
	var j interface{} // Define an empty interface

	// Assign different values of different types to the interface
	j = 42              // an int
	j = "Hello, world"  // a string
	j = []int{1, 2, 3} // a slice of integers

	switch v := j.(type) {
	case int:
		fmt.Println("j is an int:", v)
	case string:
		fmt.Println("j is a string:", v)
	case []int:
		fmt.Println("j is a slice of ints:", v)
	default:
		fmt.Println("j has an unknown type")
	}
}

```
