### ISSUE TITLE
[Ruby] - Loss in flows after joern version 2.0.92

### ISSUE THREAD

**Issue by khemrajrathore** [joernio/joern#3693]
Probable PR's which are leading to this delta - 
https://github.com/joernio/joern/commit/a4898788cb8411632937cbef2e0b314b2dee6aa6
https://github.com/joernio/joern/commit/2cd6e283130271659730c8557476e3056dd690ab
https://github.com/joernio/joern/commit/4ef5cdc23ffecf7fc279bd6ca34c21c03251a364

**Comment by DavidBakerEffendi** [comment]
I'm sort of joining with half context but are the examples of valid flows and repos we can test against?

During the fix we should then put these into the unit tests to prevent this from recurring.

**Comment by khemrajrathore** [comment]
@DavidBakerEffendi For the repo - https://github.com/odinsride/olubalance/tree/master, till joern version `2.0.92` it is working fine, but for version `2.0.93` when parsing getting the error 
```
Exception in thread "Writer" java.lang.RuntimeException: Edge with type='ARGUMENT' with direction='IN' not supported by nodeType='METHOD'
        at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:651)
        at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:630)
        at overflowdb.NodeDb.addEdgeSilentImpl(NodeDb.java:324)
        at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
        at overflowdb.NodeRef.addEdgeSilentImpl(NodeRef.java:168)
        at overflowdb.Node.addEdgeSilentInternal(Node.java:37)
        at overflowdb.BatchedUpdate$DiffGraphApplier.applyChange(BatchedUpdate.java:304)
        at overflowdb.BatchedUpdate$DiffGraphApplier.run(BatchedUpdate.java:249)
        at overflowdb.BatchedUpdate.applyDiff(BatchedUpdate.java:17)
        at io.shiftleft.passes.ConcurrentWriterCpgPass$Writer.run(ParallelCpgPass.scala:151)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

similar getting error for the repo - https://github.com/pay-rails/pay/tree/master as well

**Comment by pandurangpatil** [comment]
keeping it open to verify the changes

**Comment by khemrajrathore** [comment]
@DavidBakerEffendi with joern version `2.0.105` the error has disappeared from the repo `olubalance`, but still exists for another repo `pay` `https://github.com/pay-rails/pay/tree/master `

**Comment by DavidBakerEffendi** [comment]
@khemrajrathore Here is a follow-up for that https://github.com/joernio/joern/pull/3714
