### ISSUE TITLE
[Bug] [Kotlin] Schema violation observed in dataflow query

### ISSUE THREAD

**Issue by tuxology** [joernio/joern#3707]
**Describe the bug**
Dataflow query fails indicating a schema violation in sample repo: https://github.com/aritra-tech/Medify 
```
java.util.concurrent.ExecutionException: overflowdb.SchemaViolationException: IN edge with label AST to an adjacent METHOD is mandatory, but not defined for this METHOD_PARAMETER_IN node with id=21766
```

We do find multiple instances of correct dataflow along with this error. 

**To Reproduce**
1. importCode("Medify")
```
joern> var source = cpg.identifier.name("user")
joern> var sink = cpg.call.name("updateChildren").argument
joern> sink.reachableByFlows(source).p
2023-10-01 18:18:32.201 WARN Engine: SolveTask failed with exception:
java.util.concurrent.ExecutionException: overflowdb.SchemaViolationException: IN edge with label AST to an adjacent METHOD is mandatory, but not defined for this METHOD_PARAMETER_IN node with id=21766
        at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:605) ~[?:?]
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
        at io.joern.dataflowengineoss.queryengine.Engine.runUntilAllTasksAreSolved$1$$anonfun$1(Engine.scala:99) ~[io.joern.dataflowengineoss-2.0.103.jar:2.0.103]
        at scala.util.Try$.apply(Try.scala:210) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at io.joern.dataflowengineoss.queryengine.Engine.runUntilAllTasksAreSolved$1(Engine.scala:100) ~[io.joern.dataflowengineoss-2.0.103.jar:2.0.103]
        at io.joern.dataflowengineoss.queryengine.Engine.solveTasks(Engine.scala:114) ~[io.joern.dataflowengineoss-2.0.103.jar:2.0.103]
        at io.joern.dataflowengineoss.queryengine.Engine.backwards(Engine.scala:53) ~[io.joern.dataflowengineoss-2.0.103.jar:2.0.103]
        at io.joern.dataflowengineoss.language.ExtendedCfgNode$.io$joern$dataflowengineoss$language$ExtendedCfgNode$$$reachableByInternal$extension(ExtendedCfgNode.scala:81) ~[io.joern.dataflowengineoss-2.0.103.jar:2.0.103]
        at io.joern.dataflowengineoss.language.ExtendedCfgNode$.reachableByFlows$extension(ExtendedCfgNode.scala:45) ~[io.joern.dataflowengineoss-2.0.103.jar:2.0.103]
        at rs$line$27$.<clinit>(rs$line$27:1) ~[?:?]
        at rs$line$27.res22(rs$line$27) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at replpp.Rendering.$anonfun$4(Rendering.scala:98) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at scala.Option.flatMap(Option.scala:283) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at replpp.Rendering.valueOf(Rendering.scala:99) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.Rendering.renderVal(Rendering.scala:142) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.DottyReplDriver.$anonfun$7(DottyReplDriver.scala:364) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
        at scala.collection.immutable.List.foreach(List.scala:333) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at replpp.DottyReplDriver.extractAndFormatMembers$1(DottyReplDriver.scala:370) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.DottyReplDriver.renderDefinitions$$anonfun$2(DottyReplDriver.scala:402) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at scala.Option.map(Option.scala:242) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at replpp.DottyReplDriver.renderDefinitions(DottyReplDriver.scala:407) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.DottyReplDriver.compile$$anonfun$2(DottyReplDriver.scala:304) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at scala.util.Either.fold(Either.scala:189) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at replpp.DottyReplDriver.compile(DottyReplDriver.scala:322) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.DottyReplDriver.interpret(DottyReplDriver.scala:245) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.ReplDriverBase.interpretInput(ReplDriverBase.scala:65) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.ReplDriver.loop$1$$anonfun$1(ReplDriver.scala:35) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at scala.util.Try$.apply(Try.scala:210) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at replpp.ReplDriver.loop$1(ReplDriver.scala:36) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.ReplDriver.runUntilQuit$$anonfun$2(ReplDriver.scala:52) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.DottyReplDriver.withRedirectedOutput(DottyReplDriver.scala:187) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.DottyReplDriver.runBody$$anonfun$1(DottyReplDriver.scala:161) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80) [org.scala-lang.scala3-compiler_3-3.3.1.jar:3.3.1]
        at replpp.DottyReplDriver.runBody(DottyReplDriver.scala:161) [com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.ReplDriver.runUntilQuit(ReplDriver.scala:53) [com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at replpp.InteractiveShell$.run(InteractiveShell.scala:39) [com.michaelpollmeier.scala-repl-pp_3-0.1.70.jar:0.1.70]
        at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:237) [io.joern.console-2.0.103.jar:2.0.103]
        at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:224) [io.joern.console-2.0.103.jar:2.0.103]
        at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:7) [io.joern.joern-cli-2.0.103.jar:2.0.103]
        at io.joern.console.BridgeBase.run(BridgeBase.scala:204) [io.joern.console-2.0.103.jar:2.0.103]
        at io.joern.console.BridgeBase.run$(BridgeBase.scala:44) [io.joern.console-2.0.103.jar:2.0.103]
        at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:7) [io.joern.joern-cli-2.0.103.jar:2.0.103]
        at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:12) [io.joern.joern-cli-2.0.103.jar:2.0.103]
        at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala) [io.joern.joern-cli-2.0.103.jar:2.0.103]
```

**Expected behavior**
No errors should be present

**Desktop (please complete the following information):**
 - OS: WSL (Ubuntu 20.04)
 - Joern Version: 2.0.103
 - Java version

**Comment by tuxology** [comment]
Closing this because this is not reproducible anymore in v2.0.117
