### ISSUE TITLE
[Bug] jimple2cpg failure

### ISSUE THREAD

**Issue by tyousyuka** [joernio/joern#3724]
apk: [http://file-share.ulthon.com/index/share/65239797727e9](url)
pwd: e2306f

used command:
/home/App-Sec/joern-cli/jimple2cpg -J-Xmx30688m /home/App-Sec/jar/fill.up.the.frigde.organization.games.verName1.101.verCode1101.jar --output /home/App-Sec/bin/fill.up.the.frigde.organization.games.verName1.101.verCode1101.bin

error:
java.lang.StackOverflowError
        at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:131)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:76)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at soot.jimple.internal.JTableSwitchStmt.toString(JTableSwitchStmt.java:87)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)

**Comment by DavidBakerEffendi** [comment]
The bug seems to be internal to Soot, but I will add something to catch this error and emit an `Unknown` node if it happens.
