### ISSUE TITLE
[Bug] java.lang.ArrayIndexOutOfBoundsException thrown on importCode

### ISSUE THREAD

**Issue by shadowsock5** [joernio/joern#3767]
**Describe the bug**
java.lang.ArrayIndexOutOfBoundsException thrown on importCode

Please keep the conversation English! Make it easy for us and share your input code or a minified example. 

**To Reproduce**
I unzipped these classes from jar files.
There are 9942 class files, occupying 40M of space.
```
$ find /d/pentest-projects/yyyy/zzzz-only  -name *.class|wc -l
9942
```
```
joern> importCode("D:\\pentest-projects\\yyyy\\zzzz-only")
Using generator for language: JAVA: JavaCpgGenerator
Creating project `zzzz-only` for code at `D:\pentest-projects\yyyy\zzzz`
=======================================================================================================
Invoking CPG generator in a separate process. Note that the new process will consume additional memory.
If you are importing a large codebase (and/or running into memory issues), please try the following:
1) exit joern
2) invoke the frontend: D:\repos\joern-cli\jimple2cpg.bat -J-Xmx20480m D:\pentest-projects\yyyy\zzzz-only --output C:\Users\xxxx\workspace\zzzz-only\cpg.bin.zip
3) start joern, import the cpg: `importCpg("path/to/cpg")`
=======================================================================================================

java.lang.ArrayIndexOutOfBoundsException: Index 34 out of bounds for length 10
        at org.objectweb.asm.ClassReader.readLabel(ClassReader.java:2679)
        at org.objectweb.asm.ClassReader.createLabel(ClassReader.java:2695)
        at org.objectweb.asm.ClassReader.readTypeAnnotations(ClassReader.java:2760)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1928)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at soot.asm.AsmClassSource.resolve(AsmClassSource.java:68)
        at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:274)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
        at soot.SootResolver.bringToSignatures(SootResolver.java:313)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:198)
        at soot.SootResolver.resolveClass(SootResolver.java:155)
        at soot.Scene.loadClass(Scene.java:1016)
        at soot.Scene.loadClassAndSupport(Scene.java:1003)
        at io.joern.jimple2cpg.Jimple2Cpg.sootLoad$$anonfun$2(Jimple2Cpg.scala:81)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at io.joern.jimple2cpg.Jimple2Cpg.sootLoad(Jimple2Cpg.scala:81)
        at io.joern.jimple2cpg.Jimple2Cpg.cpgApplyPasses(Jimple2Cpg.scala:104)
        at io.joern.jimple2cpg.Jimple2Cpg.createCpg$$anonfun$1$$anonfun$1(Jimple2Cpg.scala:126)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at better.files.Dispose.apply(Dispose.scala:75)
        at io.joern.jimple2cpg.Jimple2Cpg.createCpg$$anonfun$1(Jimple2Cpg.scala:126)
        at scala.runtime.function.JProcedure2.apply(JProcedure2.java:15)
        at scala.runtime.function.JProcedure2.apply(JProcedure2.java:10)
        at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg$$anonfun$1$$anonfun$1(X2Cpg.scala:262)
        at io.joern.x2cpg.X2Cpg$.$anonfun$adapted$1(X2Cpg.scala:263)
        at scala.util.Try$.apply(Try.scala:210)
        at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg$$anonfun$1(X2Cpg.scala:263)
        at scala.util.Try$.apply(Try.scala:210)
        at io.joern.x2cpg.X2Cpg$.withNewEmptyCpg(X2Cpg.scala:269)
        at io.joern.jimple2cpg.Jimple2Cpg.createCpg(Jimple2Cpg.scala:127)
        at io.joern.jimple2cpg.Jimple2Cpg.createCpg(Jimple2Cpg.scala:122)
        at io.joern.x2cpg.X2CpgFrontend.run$$anonfun$1(X2Cpg.scala:130)
        at io.joern.x2cpg.X2Cpg$.withErrorsToConsole(X2Cpg.scala:276)
        at io.joern.x2cpg.X2CpgFrontend.run(X2Cpg.scala:136)
        at io.joern.x2cpg.X2CpgFrontend.run$(X2Cpg.scala:118)
        at io.joern.jimple2cpg.Jimple2Cpg.run(Jimple2Cpg.scala:25)
        at io.joern.jimple2cpg.Main$.run(Main.scala:73)
        at io.joern.jimple2cpg.Main$.run(Main.scala:72)
        at io.joern.x2cpg.X2CpgMain.main(X2Cpg.scala:101)
        at io.joern.jimple2cpg.Main.main(Main.scala)
moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: C:\Users\xxxx\workspace\zzzz-only\cpg.bin.tmp
Code successfully imported. You can now query it using `cpg`.
For an overview of all imported code, type `workspace`.
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
val res0: io.shiftleft.codepropertygraph.Cpg = Cpg (Graph [4 nodes])
```

**Expected behavior**
There would be more than 4 nodes and more exceptions are thrown.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Joern 2.0.83
 - Java 11

**Additional context**

**Comment by DavidBakerEffendi** [comment]
Seems to be a bug in Soot, the dependency for this frontend. I suppose we should migrate to SootUp sooner rather than later.
