### ISSUE TITLE
[Bug] Unable to export joern CPG in .dot format from Java file with the joern-export command

### ISSUE THREAD

**Issue by Ant0in3bzh** [joernio/joern#3892]
**Describe the bug**
Hello, I tried to export cpg.dot from java file. I first parse the file, everything is fine, but when I run the joern-export command I encounter a problem. This may not be possible ?

**To Reproduce**
1. Create a simple Hello_World.java test file : 
```java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}

```
3. Then analyze the file with the command:
```bash
debian@debian:~/code/joern$ joern-parse --language java HelloWorld.java
Parsing code at: HelloWorld.java - language: `java`
[+] Running language frontend
=======================================================================================================
Invoking CPG generator in a separate process. Note that the new process will consume additional memory.
If you are importing a large codebase (and/or running into memory issues), please try the following:
1) exit joern
2) invoke the frontend: /opt/joern/joern-cli/jimple2cpg -J-Xmx4000m HelloWorld.java --output cpg.bin
3) start joern, import the cpg: `importCpg("path/to/cpg")`
=======================================================================================================

[+] Applying default overlays
Successfully wrote graph to: /home/debian/code/joern/cpg.bin
To load the graph, type `joern /home/debian/code/joern/cpg.bin`
```
It's a success.

5. And I tried to export cpg files in dot format with the command:

```bash
debian@debian:~/code/joern$ joern-export -v --repr=cpg --format=dot cpg.bin
# Executing command line:
java
-XX:+UseG1GC
-XX:CompressedClassSpaceSize=128m
-Dlog4j.configurationFile=/opt/joern/joern-cli/conf/log4j2.xml
-cp
/opt/joern/joern-cli/lib/*
io.joern.joerncli.JoernExport
--repr=cpg
--format=dot
cpg.bin

Exception in thread "main" java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:758)
	at scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:753)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1300)
	at scala.collection.IterableOnceOps.reduce(IterableOnce.scala:727)
	at scala.collection.IterableOnceOps.reduce$(IterableOnce.scala:727)
	at scala.collection.AbstractIterator.reduce(Iterator.scala:1300)
	at io.joern.joerncli.JoernExport$.exportWithOdbFormat(JoernExport.scala:157)
	at io.joern.joerncli.JoernExport$.exportCpg(JoernExport.scala:107)
	at io.joern.joerncli.JoernExport$.main$$anonfun$1$$anonfun$1(JoernExport.scala:67)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.util.Using$.resource(Using.scala:261)
	at io.joern.joerncli.JoernExport$.main$$anonfun$1(JoernExport.scala:68)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.Option.foreach(Option.scala:437)
	at io.joern.joerncli.JoernExport$.main(JoernExport.scala:68)
	at io.joern.joerncli.JoernExport.main(JoernExport.scala)
```
An error occured.

7. Check if the results are created in the out folder : 

```bash
debian@debian:~/code/joern$ ls out/
debian@debian:~/code/joern$ 
```

No result.

**Expected behavior**
Severeal files containing dot files in /out folder.

**Desktop: **
 - OS : Debian 12
 - Joern Version 2.0.173 , tryed also with older version but without success
 - Java version JDK 19 as sayed in Read-Me [joern_requirement](https://github.com/joernio/joern#requirements), also tryed with java JDK21, but without sucess.

**Additional context**
The question was asked in Joern.io Discord. @DavidBakerEffendi 
My Joern works well with **C++** files. I can do **joern-parse** and **joern-export** in dot files. Maybe other hands to do this, I also tried to do it inside Joern, I tried it but without success too.

**Comment by Ant0in3bzh** [comment]
Hi, after cloning your new branch, I still have the same issue, maybe I did something while running : 
`joern-parse --language java HelloWorld.java`
This command returns sucess, and after : 
`joern-export -v --repr=cpg --format=dot cpg.bin`
```bash
# Executing command line:
java
-XX:+UseG1GC
-XX:CompressedClassSpaceSize=128m
-Dlog4j.configurationFile=/opt/joern/joern-cli/conf/log4j2.xml
-cp
/opt/joern/joern-cli/lib/*
io.joern.joerncli.JoernExport
--repr=cpg
--format=dot
cpg.bin

Exception in thread "main" java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:758)
	at scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:753)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1300)
	at scala.collection.IterableOnceOps.reduce(IterableOnce.scala:727)
	at scala.collection.IterableOnceOps.reduce$(IterableOnce.scala:727)
	at scala.collection.AbstractIterator.reduce(Iterator.scala:1300)
	at io.joern.joerncli.JoernExport$.exportWithOdbFormat(JoernExport.scala:157)
	at io.joern.joerncli.JoernExport$.exportCpg(JoernExport.scala:107)
	at io.joern.joerncli.JoernExport$.main$$anonfun$1$$anonfun$1(JoernExport.scala:67)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.util.Using$.resource(Using.scala:261)
	at io.joern.joerncli.JoernExport$.main$$anonfun$1(JoernExport.scala:68)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.Option.foreach(Option.scala:437)
	at io.joern.joerncli.JoernExport$.main(JoernExport.scala:68)
	at io.joern.joerncli.JoernExport.main(JoernExport.scala)
```

**Comment by DavidBakerEffendi** [comment]
@Ant0in3bzh Just to quickly check, have you run `sbt stage` on the new branch to re-generate the executables? Then to double-check, use the `./joern-parse` and `./joern-export` at the base of the directory. 

I've confirmed no error is given. The core issue is that the generated CPG appears to be empty.

**Comment by Ant0in3bzh** [comment]
Okay, great, it’s work!

```bash
sudo joern-export -v --repr=cpg --format=dot cpg.bin
# Executing command line:
java
-XX:+UseG1GC
-XX:CompressedClassSpaceSize=128m
-Dlog4j.configurationFile=/opt/joern/joern-cli/conf/log4j2.xml
-cp
/opt/joern/joern-cli/lib/*
io.joern.joerncli.JoernExport
--repr=cpg
--format=dot
cpg.bin

exported 35 nodes, 107 edges into /home/debian/code/joern/test_issue_java/joern/out
```

I tried with the old version of Joern to see if your changes were relevant and that it was not a simple careless error on my part. But I had the same problem specifying the **javasrc** attribute.

This merge request therefore resolves the problem. Thank you for this quick response ! 👍
