### ISSUE TITLE
[Bug][Jssrc2cpg] ReachingDefPass failed

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#3901]
[eslint-plugin-react.zip](https://github.com/joernio/joern/files/13594005/eslint-plugin-react.zip)

```

moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: C:\Users\admin\Downloads\joern-cli\joern-cli\workspace\eslint-plugin-react\cpg.bin.tmp
Code successfully imported. You can now query it using `cpg`.
For an overview of all imported code, type `workspace`.
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
2023-12-07 10:08:27.242 ERROR CpgPassBase: Pass io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass failed
overflowdb.SchemaViolationException: OUT edge with label REF to an adjacent METHOD is mandatory, but not defined for this METHOD_REF node with id=30852
        at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:869) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.25.jar:1.4.25]
        at io.shiftleft.codepropertygraph.generated.nodes.MethodRef.referencedMethod(MethodRef.scala:399) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.25.jar:1.4.25]
        at io.shiftleft.codepropertygraph.generated.traversal.MethodRefTraversalExtGen$.referencedMethod$extension$$anonfun$1(MethodRef.scala:14) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.25.jar:1.4.25]
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:584) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:480) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:480) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.mutable.Growable.addAll(Growable.scala:61) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.mutable.ArrayBuilder.addAll(ArrayBuilder.scala:66) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.toArray(IterableOnce.scala:1319) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.toArray$(IterableOnce.scala:1313) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.Array$.from(Array.scala:74) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:282) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:273) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.ClassTagIterableFactory$AnyIterableDelegate.from(Factory.scala:671) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableFactory$ToFactory.fromSpecific(Factory.scala:274) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.to(IterableOnce.scala:1283) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.to$(IterableOnce.scala:1283) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.AbstractIterator.to(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at overflowdb.traversal.TraversalSugarExt$.sortBy$extension(Traversal.scala:111) ~[io.shiftleft.overflowdb-traversal_3-1.181.jar:1.181]
        at io.joern.dataflowengineoss.package$.identifiersFromCapturedScopes(package.scala:18) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at io.joern.dataflowengineoss.package$.identifierToFirstUsages$$anonfun$1(package.scala:13) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.immutable.List.prependedAll(List.scala:152) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1288) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1288) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.AbstractIterator.toList(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at overflowdb.traversal.TraversalSugarExt$.l$extension(Traversal.scala:24) ~[io.shiftleft.overflowdb-traversal_3-1.181.jar:1.181]
        at io.joern.dataflowengineoss.package$.identifierToFirstUsages(package.scala:13) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.$anonfun$3(DdgGenerator.scala:174) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.immutable.List.prependedAll(List.scala:155) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1288) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1288) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.AbstractIterator.toList(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at overflowdb.traversal.TraversalSugarExt$.l$extension(Traversal.scala:24) ~[io.shiftleft.overflowdb-traversal_3-1.181.jar:1.181]
        at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addEdgesToCapturedIdentifiersAndParameters$1(DdgGenerator.scala:175) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addReachingDefEdges(DdgGenerator.scala:214) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:33) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:23) ~[io.joern.dataflowengineoss-2.0.151.jar:2.0.151]
        at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:147) ~[io.shiftleft.codepropertygraph_3-1.4.25.jar:1.4.25]
        at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:146) ~[io.shiftleft.codepropertygraph_3-1.4.25.jar:1.4.25]
        at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960) ~[?:?]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934) ~[?:?]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$19.next(Iterator.scala:973) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$19.next(Iterator.scala:971) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at scala.collection.Iterator$$anon$6.next(Iterator.scala:492) ~[org.scala-lang.scala-library-2.13.10.jar:?]
        at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:864) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.25.jar:1.4.25]
        ... 59 more
overflowdb.SchemaViolationException: OUT edge with label REF to an adjacent METHOD is mandatory, but not defined for this METHOD_REF node with id=30852
  at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:869)
  at io.shiftleft.codepropertygraph.generated.nodes.MethodRef.referencedMethod(MethodRef.scala:399)
  at io.shiftleft.codepropertygraph.generated.traversal.MethodRefTraversalExtGen$.referencedMethod$extension$$anonfun$1(MethodRef.scala:14)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
  at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
  at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:480)
  at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:480)
  at scala.collection.mutable.Growable.addAll(Growable.scala:61)
  at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
  at scala.collection.mutable.ArrayBuilder.addAll(ArrayBuilder.scala:66)
  at scala.collection.IterableOnceOps.toArray(IterableOnce.scala:1319)
  at scala.collection.IterableOnceOps.toArray$(IterableOnce.scala:1313)
  at scala.collection.AbstractIterator.toArray(Iterator.scala:1300)
  at scala.Array$.from(Array.scala:74)
  at scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:282)
  at scala.collection.immutable.ArraySeq$.from(ArraySeq.scala:273)
  at scala.collection.ClassTagIterableFactory$AnyIterableDelegate.from(Factory.scala:671)
  at scala.collection.IterableFactory$ToFactory.fromSpecific(Factory.scala:274)
  at scala.collection.IterableOnceOps.to(IterableOnce.scala:1283)
  at scala.collection.IterableOnceOps.to$(IterableOnce.scala:1283)
  at scala.collection.AbstractIterator.to(Iterator.scala:1300)
  at overflowdb.traversal.TraversalSugarExt$.sortBy$extension(Traversal.scala:111)
  at io.joern.dataflowengineoss.package$.identifiersFromCapturedScopes(package.scala:18)
  at io.joern.dataflowengineoss.package$.identifierToFirstUsages$$anonfun$1(package.scala:13)
  at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
  at scala.collection.immutable.List.prependedAll(List.scala:152)
  at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1288)
  at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1288)
  at scala.collection.AbstractIterator.toList(Iterator.scala:1300)
  at overflowdb.traversal.TraversalSugarExt$.l$extension(Traversal.scala:24)
  at io.joern.dataflowengineoss.package$.identifierToFirstUsages(package.scala:13)
  at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.$anonfun$3(DdgGenerator.scala:174)
  at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
  at scala.collection.immutable.List.prependedAll(List.scala:155)
  at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1288)
  at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1288)
  at scala.collection.AbstractIterator.toList(Iterator.scala:1300)
  at overflowdb.traversal.TraversalSugarExt$.l$extension(Traversal.scala:24)
  at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addEdgesToCapturedIdentifiersAndParameters$1(DdgGenerator.scala:175)
  at io.joern.dataflowengineoss.passes.reachingdef.DdgGenerator.addReachingDefEdges(DdgGenerator.scala:214)
  at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:33)
  at io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass.runOnPart(ReachingDefPass.scala:23)
  at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:147)
  at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:146)
  at java.base/java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220)
  at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
  at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
  at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
  at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.NoSuchElementException: next on empty iterator
  at scala.collection.Iterator$$anon$19.next(Iterator.scala:973)
  at scala.collection.Iterator$$anon$19.next(Iterator.scala:971)
  at scala.collection.Iterator$$anon$6.next(Iterator.scala:492)
  at io.shiftleft.codepropertygraph.generated.nodes.MethodRefDb.referencedMethod(MethodRef.scala:864)
  ... 59 more
```
**Desktop (please complete the following information):**
 - Win 11
 - Joern 2.0.181

**Comment by max-leuthaeuser** [comment]
I don't know whats wrong here but importing that project into joern hangs forever at the TypeNodePass. @johannescoetzee Could you take a look?
