### ISSUE TITLE
[Bug][Jssrc2cpg] InvalidPathException

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#3903]
[acorn.zip](https://github.com/joernio/joern/files/13594099/acorn.zip)
```
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
java.nio.file.InvalidPathException: Illegal char <"> at index 74: C:\Users\admin\Downloads\acorn\acornjs-acorn-34e9854\bin\\nicodeVersion + "/Binary_Property/ID_Start/code-points.js
  at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
  at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
  at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
  at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
  at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
  at java.base/java.nio.file.Path.of(Path.java:147)
  at java.base/java.nio.file.Paths.get(Paths.java:69)
  at better.files.File$.apply(File.scala:1355)
  at io.joern.jssrc2cpg.passes.JavaScriptImportResolverPass.optionalResolveImport(JavaScriptImportResolverPass.scala:39)
  at io.joern.x2cpg.passes.frontend.XImportResolverPass.runOnPart$$anonfun$2$$anonfun$1$$anonfun$1(XImportResolverPass.scala:33)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.Option.foreach(Option.scala:437)
  at io.joern.x2cpg.passes.frontend.XImportResolverPass.runOnPart$$anonfun$2$$anonfun$1(XImportResolverPass.scala:34)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.Option.foreach(Option.scala:437)
  at io.joern.x2cpg.passes.frontend.XImportResolverPass.runOnPart$$anonfun$2(XImportResolverPass.scala:34)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
  at io.joern.x2cpg.passes.frontend.XImportResolverPass.runOnPart(XImportResolverPass.scala:34)
  at io.joern.x2cpg.passes.frontend.XImportResolverPass.runOnPart(XImportResolverPass.scala:27)
  at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore$$anonfun$1(ParallelCpgPass.scala:95)
  at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
  at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
**Desktop (please complete the following information):**
 - Win 11
 - Joern 2.0.181

**Comment by max-leuthaeuser** [comment]
@DavidBakerEffendi 
Looks like a JavaScriptImportResolverPass problem. Could you have a look?
