### ISSUE TITLE
[Bug] JavaTypeRecovery ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#3948]
When running `joern-parse spring-framework-6.1.1/` and subsequently loading the CPG on the joern shell using

```
./joern cpg.bin
```

I get the following:

```
joern git:(master) ✗ ./joern /home/fabs/git/joern/cpg.bin
Creating project `cpg.bin` for CPG at `/home/fabs/git/joern/cpg.bin`
Project with name cpg.bin already exists - overwriting
Creating working copy of CPG to be safe
Loading base CPG from: /home/fabs/git/joern/workspace/cpg.bin/cpg.bin.tmp
Overlay dataflowOss already exists - skipping
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
2023-12-12 22:18:42.071 ERROR CpgPassBase: Pass io.joern.javasrc2cpg.passes.JavaTypeRecovery failed
java.lang.ArrayIndexOutOfBoundsException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:693) ~[?:?]
	at io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:161) ~[io.shiftleft.codepropertygraph_3-1.4.32.jar:1.4.32]
	at io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:76) ~[io.shiftleft.codepropertygraph_3-1.4.32.jar:1.4.32]
	at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:128) ~[io.shiftleft.codepropertygraph_3-1.4.32.jar:1.4.32]
	at io.joern.console.cpgcreation.JavaSrcCpgGenerator.applyPostProcessingPasses$$anonfun$2(JavaSrcCpgGenerator.scala:27) ~[io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
	at scala.collection.immutable.List.foreach(List.scala:333) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.console.cpgcreation.JavaSrcCpgGenerator.applyPostProcessingPasses(JavaSrcCpgGenerator.scala:27) ~[io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.console.Console.applyPostProcessingPasses(Console.scala:403) ~[io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.console.Console.importCpg$$anonfun$2(Console.scala:374) ~[io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at scala.Option.foreach(Option.scala:437) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.console.Console.importCpg(Console.scala:374) ~[io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at rs$line$1$.<clinit>(rs$line$1:230) ~[?:?]
	at rs$line$1.opts(rs$line$1) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at replpp.Rendering.$anonfun$4(Rendering.scala:98) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at scala.Option.flatMap(Option.scala:283) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.Rendering.valueOf(Rendering.scala:99) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.Rendering.renderVal(Rendering.scala:142) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.$anonfun$7(DottyReplDriver.scala:364) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
	at scala.collection.immutable.List.foreach(List.scala:333) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.DottyReplDriver.extractAndFormatMembers$1(DottyReplDriver.scala:370) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.renderDefinitions$$anonfun$2(DottyReplDriver.scala:402) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at scala.Option.map(Option.scala:242) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.DottyReplDriver.renderDefinitions(DottyReplDriver.scala:407) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.compile$$anonfun$2(DottyReplDriver.scala:304) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at scala.util.Either.fold(Either.scala:189) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.DottyReplDriver.compile(DottyReplDriver.scala:322) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.interpret(DottyReplDriver.scala:245) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.runQuietly$$anonfun$1(DottyReplDriver.scala:158) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.withRedirectedOutput(DottyReplDriver.scala:187) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.runBody$$anonfun$1(DottyReplDriver.scala:161) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80) [org.scala-lang.scala3-compiler_3-3.3.1.jar:3.3.1]
	at replpp.DottyReplDriver.runBody(DottyReplDriver.scala:161) [com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.DottyReplDriver.runQuietly(DottyReplDriver.scala:159) [com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.InteractiveShell$.run(InteractiveShell.scala:28) [com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:237) [io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:224) [io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:7) [io.joern.joern-cli-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.console.BridgeBase.run(BridgeBase.scala:204) [io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.console.BridgeBase.run$(BridgeBase.scala:44) [io.joern.console-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:7) [io.joern.joern-cli-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:12) [io.joern.joern-cli-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala) [io.joern.joern-cli-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at overflowdb.misc.ArrayIter.hasNext(ArrayIter.scala:6) ~[io.shiftleft.overflowdb-core_3-1.181.jar:1.181]
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:477) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.Iterator$$anon$6.next(Iterator.scala:488) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.shiftleft.codepropertygraph.generated.nodes.MemberDb.typeDecl(Member.scala:308) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.32.jar:1.4.32]
	at io.shiftleft.codepropertygraph.generated.nodes.Member.typeDecl(Member.scala:166) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.32.jar:1.4.32]
	at io.shiftleft.codepropertygraph.generated.traversal.MemberTraversalExtGen$.typeDecl$extension$$anonfun$1(Member.scala:14) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.32.jar:1.4.32]
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:478) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.mutable.Growable.addAll(Growable.scala:61) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:396) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.immutable.Set$.from(Set.scala:353) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.toSet(IterableOnce.scala:1295) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.toSet$(IterableOnce.scala:1295) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.AbstractIterator.toSet(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.getFieldParents(XTypeRecovery.scala:535) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.getSymbolFromCall(XTypeRecovery.scala:731) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.assignTypesToCall(XTypeRecovery.scala:695) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.visitCallAssignedToCall(XTypeRecovery.scala:678) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.visitAssignmentArguments(XTypeRecovery.scala:419) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.visitAssignments(XTypeRecovery.scala:409) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.run$$anonfun$2(XTypeRecovery.scala:354) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.run(XTypeRecovery.scala:354) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.XTypeRecovery.runOnPart(XTypeRecovery.scala:167) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.joern.x2cpg.passes.frontend.XTypeRecovery.runOnPart(XTypeRecovery.scala:166) ~[io.joern.x2cpg-2.0.190+3-f1dca758.jar:2.0.190+3-f1dca758]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:156) ~[io.shiftleft.codepropertygraph_3-1.4.32.jar:1.4.32]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:155) ~[io.shiftleft.codepropertygraph_3-1.4.32.jar:1.4.32]
	at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934) ~[?:?]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by DavidBakerEffendi** [comment]
@bbrehm Do you have any idea what could cause this? I've experienced a similar thing when using ConcurrentWriterParallelCpgPass but fixed it when moving to ForkJoinParallelCpgPass, but there seems to be some database related issue?

**Comment by fabsx00** [comment]
Will attempt to move this to `ForkJoinParrallelCpgPass` and see if that makes a difference.

**Comment by fabsx00** [comment]
This already is a `ForkJoinParrallelCpgPass`.

**Comment by DavidBakerEffendi** [comment]
After chatting with @fabsx00 offline, we've observed this behaviour before in general with ODB when memory is close to maxing out. Seems to be more of an ODB issue. Since ODBv2 is nearly out, we shelve this issue.
