### ISSUE TITLE
[Java]convert cpg to json ,help!

### ISSUE THREAD

**Issue by 1201wen** [joernio/joern#4086]
The functionality I want to implement is to generate cpg from the source java file and convert it to json format, here is the code I used:
```
def generate_cpg(java_file_path):
    # 生成 CPG
    shell_str = "sh " + joern_cli_path + "/joern-parse " + java_file_path
    subprocess.call(shell_str, shell=True)
def convert_cpg_to_json(java_file_path):
   subprocess.call(
        ["sh", joern_cli_path + "/joern", "--script", "cpg2json.sc",
          "--param", "outFile=" + json_full_path])
```
The script is as follows：
```
@main def exec(outFile: String) = {
   loadCpg("/home/wen/GAST/preproccess/cpg.bin")
   cpg.all.toJsonPretty #> outFile
}
```
Some java files have the following error at runtime:
```
[INFO ] Start of pass: io.joern.javasrc2cpg.passes.JavaTypeRecovery
[ERROR] Pass io.joern.javasrc2cpg.passes.JavaTypeRecovery failed
java.lang.NullPointerException: null
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:693) ~[?:?]
	at io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:161) ~[io.shiftleft.codepropertygraph_3-1.4.33.jar:1.4.33]
	at io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:76) ~[io.shiftleft.codepropertygraph_3-1.4.33.jar:1.4.33]
	at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:128) ~[io.shiftleft.codepropertygraph_3-1.4.33.jar:1.4.33]
	at io.joern.console.cpgcreation.JavaSrcCpgGenerator.applyPostProcessingPasses$$anonfun$2(JavaSrcCpgGenerator.scala:27) ~[io.joern.console-2.0.219.jar:2.0.219]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) ~[org.scala-lang.scala3-library_3-3.3.1.jar:3.3.1]
	at scala.collection.immutable.List.foreach(List.scala:333) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.console.cpgcreation.JavaSrcCpgGenerator.applyPostProcessingPasses(JavaSrcCpgGenerator.scala:27) ~[io.joern.console-2.0.219.jar:2.0.219]
	at io.joern.console.Console.applyPostProcessingPasses(Console.scala:403) ~[io.joern.console-2.0.219.jar:2.0.219]
	at io.joern.console.Console.importCpg$$anonfun$2(Console.scala:374) ~[io.joern.console-2.0.219.jar:2.0.219]
	at scala.Option.foreach(Option.scala:437) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.console.Console.importCpg(Console.scala:374) ~[io.joern.console-2.0.219.jar:2.0.219]
	at io.joern.joerncli.console.JoernConsole.loadCpg(JoernConsole.scala:39) ~[io.joern.joern-cli-2.0.219.jar:2.0.219]
	at ScalaReplPP$.exec(scala-repl-pp-script-with-predef9940735533303739772.sc:238) ~[?:?]
	at ScalaReplPP$.$anonfun$1(scala-repl-pp-script-with-predef9940735533303739772.sc:245) ~[?:?]
	at replpp.shaded.mainargs.Invoker$.$anonfun$2(Invoker.scala:68) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Result.flatMap(Result.scala:13) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Result.flatMap$(Result.scala:7) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Result$Success.flatMap(Result.scala:23) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Invoker$.invoke0(Invoker.scala:68) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Invoker$.invoke(Invoker.scala:77) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Invoker$.invokeLocal$1(Invoker.scala:89) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Invoker$.groupArgs$1$$anonfun$2(Invoker.scala:103) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Result.flatMap(Result.scala:13) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Result.flatMap$(Result.scala:7) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Result$Success.flatMap(Result.scala:23) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Invoker$.groupArgs$1(Invoker.scala:103) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.Invoker$.runMains(Invoker.scala:108) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.ParserForMethods.runRaw0(Parser.scala:170) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.ParserForMethods.runEither(Parser.scala:108) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.ParserForMethods.runEither(Parser.scala:151) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at replpp.shaded.mainargs.ParserForMethods.runOrExit(Parser.scala:56) ~[com.michaelpollmeier.scala-repl-pp-shaded-libs_3-0.1.76.jar:0.1.76]
	at ScalaReplPP$.main(scala-repl-pp-script-with-predef9940735533303739772.sc:245) ~[?:?]
	at ScalaReplPP.main(scala-repl-pp-script-with-predef9940735533303739772.sc) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at replpp.scripting.ScriptingDriver.compileAndRun$$anonfun$1(ScriptingDriver.scala:55) ~[com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at scala.Option.flatMap(Option.scala:283) [org.scala-lang.scala-library-2.13.10.jar:?]
	at replpp.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:61) [com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.scripting.NonForkingScriptRunner$.exec(NonForkingScriptRunner.scala:58) [com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.scripting.NonForkingScriptRunner$.main(NonForkingScriptRunner.scala:23) [com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
	at replpp.scripting.NonForkingScriptRunner.main(NonForkingScriptRunner.scala) [com.michaelpollmeier.scala-repl-pp_3-0.1.76.jar:0.1.76]
Caused by: java.lang.NullPointerException: Cannot invoke "overflowdb.AdjacentNodes.getOffset(int)" because "adjacentNodesTmp" is null
	at overflowdb.NodeDb.startIndex(NodeDb.java:678) ~[io.shiftleft.overflowdb-core_3-1.181.jar:1.181]
	at overflowdb.NodeDb.createAdjacentNodeScalaIteratorByOffSet(NodeDb.java:609) ~[io.shiftleft.overflowdb-core_3-1.181.jar:1.181]
	at io.shiftleft.codepropertygraph.generated.nodes.CallDb.isCallForImportOut(Call.scala:1009) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.33.jar:1.4.33]
	at io.shiftleft.codepropertygraph.generated.nodes.CallDb._importViaIsCallForImportOut(Call.scala:1011) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.33.jar:1.4.33]
	at io.shiftleft.codepropertygraph.generated.nodes.Call._importViaIsCallForImportOut(Call.scala:408) ~[io.shiftleft.codepropertygraph-domain-classes_3-1.4.33.jar:1.4.33]
	at io.shiftleft.semanticcpg.language.callgraphextension.CallTraversal$.referencedImports$extension$$anonfun$1(CallTraversal.scala:16) ~[io.joern.semanticcpg-2.0.219.jar:2.0.219]
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.10.jar:?]
	at io.joern.x2cpg.passes.frontend.RecoverForXCompilationUnit.run(XTypeRecovery.scala:349) ~[io.joern.x2cpg-2.0.219.jar:2.0.219]
	at io.joern.x2cpg.passes.frontend.XTypeRecovery.runOnPart(XTypeRecovery.scala:168) ~[io.joern.x2cpg-2.0.219.jar:2.0.219]
	at io.joern.x2cpg.passes.frontend.XTypeRecovery.runOnPart(XTypeRecovery.scala:167) ~[io.joern.x2cpg-2.0.219.jar:2.0.219]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:156) ~[io.shiftleft.codepropertygraph_3-1.4.33.jar:1.4.33]
	at io.shiftleft.passes.NewStyleCpgPassBase$$anon$2.accept(CpgPass.scala:155) ~[io.shiftleft.codepropertygraph_3-1.4.33.jar:1.4.33]
	at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934) ~[?:?]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
[INFO ] Pass io.joern.javasrc2cpg.passes.JavaTypeRecovery completed in 124 ms (0% on mutations). -1 + 0 changes committed from 0 parts.
```
I hope I can ignore such errors and convert normally. Is this idea possible?In addition, I have to deal with a large number of java files, whether the speed can be improved？I need help!thank you!

**Comment by DavidBakerEffendi** [comment]
Hi @1201wen, this stack trace is familiar with situations where memory is constrained. The type recovery is not super necessary in Java, so you can disable it with `--frontend-args --type-prop-iterations 0`

**Comment by 1201wen** [comment]
Thank you very much for your reply. I need to deal with a lot of Java source files. Is there any way to speed up joern processing?

**Comment by 1201wen** [comment]
> Hi @1201wen, this stack trace is familiar with situations where memory is constrained. The type recovery is not super necessary in Java, so you can disable it with `--frontend-args --type-prop-iterations 0`
Thank you very much for your reply. I need to deal with a lot of Java source files. Is there any way to speed up joern processing?

**Comment by 1201wen** [comment]
Thank you very much for your reply. I need to deal with a lot of Java source files. Is there any way to speed up joern processing?

**Comment by DavidBakerEffendi** [comment]
You can disable certain unrelated post-processing passes depending on your needs. What components of the CPG do you need? i.e. what is your end task? If confidential, feel free to email me dbe@sun.ac.za (university/research) or dave@whirlylabs.com (company/for-profit)

**Comment by DavidBakerEffendi** [comment]
Complete offline
