### ISSUE TITLE
"java.nio.charset.MalformedInputException: Input length = 1" occurs when execute "joern.bat" in powershell on Windows 10

### ISSUE THREAD

**Issue by MoonBirdLin** [joernio/joern#4259]
When starting joern using joern.bat, I just got a "java.nio.charset.MalformedInputException" Exception in powershell/cmd/cygwin/mingw.
`
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
        at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:73)
        at scala.collection.immutable.List.prependedAll(List.scala:155)
        at scala.collection.immutable.List$.from(List.scala:684)
        at scala.collection.immutable.List$.from(List.scala:681)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.Seq$.from(Seq.scala:42)
        at scala.collection.IterableOnceOps.toSeq(IterableOnce.scala:1300)
        at scala.collection.IterableOnceOps.toSeq$(IterableOnce.scala:1300)
        at scala.collection.AbstractIterator.toSeq(Iterator.scala:1300)
        at replpp.util.package$.linesFromFile$$anonfun$1(package.scala:23)
        at scala.util.Using$.resource(Using.scala:261)
        at replpp.util.package$.linesFromFile(package.scala:23)
        at replpp.UsingDirectives$.findImportedFilesRecursively(UsingDirectives.scala:18)
        at replpp.package$.allPredefLines$$anonfun$1(package.scala:63)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at replpp.package$.allPredefLines(package.scala:70)
        at replpp.package$.allPredefCode(package.scala:52)
        at replpp.InteractiveShell$.run(InteractiveShell.scala:10)
        at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:243)
        at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:230)
        at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:6)
        at io.joern.console.BridgeBase.run(BridgeBase.scala:210)
        at io.joern.console.BridgeBase.run$(BridgeBase.scala:43)
        at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:6)
        at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:11)
        at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala)
`
![image](https://github.com/joernio/joern/assets/67228106/eb800328-26f7-47e2-a963-e06d6f7ebe61)

**Comment by MoonBirdLin** [comment]
I referred to [issue#1118](https://github.com/joernio/joern/issues/1118) to build joern using "sbt stage".
And I have try to change the charset as utf-8 with command "$OutputEncoding = [System.Text.Encoding]::UTF8" in powershell.
![image](https://github.com/joernio/joern/assets/67228106/0157adfa-96df-45a2-9d4c-9d1aef209688)

**Comment by MoonBirdLin** [comment]
Sorry, I found I should use jdk-19 for 2.0.284.
