### ISSUE TITLE
[Cpp importCode] java.lang.NullPointerException: Cannot invoke "org.eclipse.cdt.core.dom.ast.IASTNode.getClass()" because "node" is null

### ISSUE THREAD

**Issue by hzlujunyi** [joernio/joern#4491]
The version of jdk is `java version "19.0.2" 2023-01-17`
The version of joern-cli is `2.0.343`

Here is the output of the exception when I try to importCode for a project(cpp):

```java.lang.NullPointerException: Cannot invoke "org.eclipse.cdt.core.dom.ast.IASTNode.getClass()" because "node" is null
        at io.joern.c2cpg.astcreation.AstCreatorHelper.notHandledText(AstCreatorHelper.scala:218)
        at io.joern.c2cpg.astcreation.AstCreatorHelper.notHandledYet(AstCreatorHelper.scala:226)
        at io.joern.c2cpg.astcreation.AstCreatorHelper.notHandledYet$(AstCreatorHelper.scala:37)
        at io.joern.c2cpg.astcreation.AstCreator.notHandledYet(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstCreatorHelper.astForNode(AstCreatorHelper.scala:480)
        at io.joern.c2cpg.astcreation.AstCreatorHelper.astForNode$(AstCreatorHelper.scala:37)
        at io.joern.c2cpg.astcreation.AstCreator.astForNode(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration(AstForTypesCreator.scala:206)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration$(AstForTypesCreator.scala:12)
        at io.joern.c2cpg.astcreation.AstCreator.astsForDeclaration(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.astForCatchHandler(AstForStatementsCreator.scala:136)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.$anonfun$5(AstForStatementsCreator.scala:128)
        at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:934)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.astForTryStatement(AstForStatementsCreator.scala:129)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.astsForStatement(AstForStatementsCreator.scala:157)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.astsForStatement$(AstForStatementsCreator.scala:18)
        at io.joern.c2cpg.astcreation.AstCreator.astsForStatement(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.$anonfun$1(AstForStatementsCreator.scala:31)
        at scala.collection.ArrayOps$.flatMap$extension(ArrayOps.scala:969)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.astForBlockStatement(AstForStatementsCreator.scala:34)
        at io.joern.c2cpg.astcreation.AstForStatementsCreator.astForBlockStatement$(AstForStatementsCreator.scala:18)
        at io.joern.c2cpg.astcreation.AstCreator.astForBlockStatement(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstForFunctionsCreator.astForMethodBody(AstForFunctionsCreator.scala:243)
        at io.joern.c2cpg.astcreation.AstForFunctionsCreator.astForFunctionDefinition(AstForFunctionsCreator.scala:188)
        at io.joern.c2cpg.astcreation.AstForFunctionsCreator.astForFunctionDefinition$(AstForFunctionsCreator.scala:19)
        at io.joern.c2cpg.astcreation.AstCreator.astForFunctionDefinition(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration(AstForTypesCreator.scala:195)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration$(AstForTypesCreator.scala:12)
        at io.joern.c2cpg.astcreation.AstCreator.astsForDeclaration(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.$anonfun$2(AstForTypesCreator.scala:45)
        at scala.collection.ArrayOps$.flatMap$extension(ArrayOps.scala:969)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astForNamespaceDefinition(AstForTypesCreator.scala:47)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration(AstForTypesCreator.scala:197)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration$(AstForTypesCreator.scala:12)
        at io.joern.c2cpg.astcreation.AstCreator.astsForDeclaration(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.$anonfun$2(AstForTypesCreator.scala:45)
        at scala.collection.ArrayOps$.flatMap$extension(ArrayOps.scala:969)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astForNamespaceDefinition(AstForTypesCreator.scala:47)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration(AstForTypesCreator.scala:197)
        at io.joern.c2cpg.astcreation.AstForTypesCreator.astsForDeclaration$(AstForTypesCreator.scala:12)
        at io.joern.c2cpg.astcreation.AstCreator.astsForDeclaration(AstCreator.scala:20)
        at io.joern.c2cpg.astcreation.AstCreator.$anonfun$2(AstCreator.scala:87)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at io.joern.c2cpg.astcreation.AstCreator.astInFakeMethod(AstCreator.scala:87)
        at io.joern.c2cpg.astcreation.AstCreator.astForTranslationUnit(AstCreator.scala:62)
        at io.joern.c2cpg.astcreation.AstCreator.createAst(AstCreator.scala:53)
        at io.joern.c2cpg.passes.AstCreationPass.$anonfun$2(AstCreationPass.scala:65)
        at io.joern.x2cpg.utils.TimeUtils$.time(TimeUtils.scala:15)
        at io.joern.c2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:73)
        at io.joern.c2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:55)
        at io.shiftleft.passes.ConcurrentWriterCpgPass.createApplySerializeAndStore$$anonfun$1(ParallelCpgPass.scala:95)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)```

**Comment by max-leuthaeuser** [comment]
Could you please provide me the scanned code to further debug this?

**Comment by hzlujunyi** [comment]
> Could you please provide me the scanned code to further debug this?

Thanks. Please wait a moment for me to locate the specific code：）

**Comment by hzlujunyi** [comment]
> Could you please provide me the scanned code to further debug this?

I‘ve found the smallest snippet. Here it is:

```cpp
void main() {
    try {
    } catch (const std::exception &e) {
    } catch (...) {
    }
}
```

**Comment by max-leuthaeuser** [comment]
Thanks, will have a look soon-ish.

**Comment by hzlujunyi** [comment]
> Thanks, will have a look soon-ish.

Is it available in today's release?
