### ISSUE TITLE
Batch processing is broken

### ISSUE THREAD

**Issue by m1cm1c** [joernio/joern#451]
Joern does not seem to offer a way of batch processing. Only ever traversing a single CPG every time Joern is launched via a script does not seem like a good option because of Joern's long startup time. If, however, batch processing of many CPGs is performed within a single Joern script, Joern crashes.

With the default settings, Joern crashes after approximately 2480 CPGs. It gets really slow when processing the last few and then crashes with an out of memory error:
```
Creating working copy of CPG to be safe
Loading base CPG from: /tmp/tmp.exFI3IV3rT/workspace/cpg.bin.zip2478/cpg.bin.tmp
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
Exception in thread "overflowdb-reference-manager" java.lang.OutOfMemoryError: Java heap space
```
The exact number of CPGs it processes before crashing varies slightly (+/- 4), even when the same CPGs are processed in the exact same order.

With `export _JAVA_OPTS="-Xmx20G"`, about 2490 CPGs can be processed before it stops. It never uses even half of the 20 GB of memory, though.

When Joern runs into this problem, it uses the CPU as much as when processing but does not process any more CPGs. It doesn't seem to do anything then. It never seems to crash when given a large amount of memory (I waited for half an hour before killing it; with it not processing a single CPG during that time).

**Comment by m1cm1c** [comment]
I just noticed after submitting this issue that if you leave Joern running for a few more minutes after it crashes, you get a stack trace. A minute after the stack trace is printed, the process terminates on its own.

More complete final output:
```
Creating working copy of CPG to be safe
Loading base CPG from: /tmp/tmp.exFI3IV3rT/workspace/cpg.bin.zip2478/cpg.bin.tmp
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
Exception in thread "overflowdb-reference-manager" java.lang.OutOfMemoryError: Java heap space
Exception in thread "main" java.lang.AssertionError: script errored: 
        at io.shiftleft.console.BridgeBase.runScript(BridgeBase.scala:165)
        at io.shiftleft.console.BridgeBase.runAmmonite(BridgeBase.scala:96)
        at io.shiftleft.console.BridgeBase.runAmmonite$(BridgeBase.scala:87)
        at io.shiftleft.joern.console.AmmoniteBridge$.runAmmonite(AmmoniteBridge.scala:5)
        at io.shiftleft.joern.console.AmmoniteBridge$.delayedEndpoint$io$shiftleft$joern$console$AmmoniteBridge$1(AmmoniteBridge.scala:7)
        at io.shiftleft.joern.console.AmmoniteBridge$delayedInit$body.apply(AmmoniteBridge.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:75)
        at scala.App.$anonfun$main$1$adapted(App.scala:75)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
        at scala.App.main(App.scala:75)
        at scala.App.main$(App.scala:73)
        at io.shiftleft.joern.console.AmmoniteBridge$.main(AmmoniteBridge.scala:5)
        at io.shiftleft.joern.console.AmmoniteBridge.main(AmmoniteBridge.scala)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by ursachec** [comment]
thank you for the contribution, this issue is too vague to be helpful at the moment. please consider reopening it if you have a minimal example showing exactly what is wrong where

**Comment by cyw3** [comment]
I get the same error:
```bash
Exception in thread "Writer" java.lang.OutOfMemoryError: Java heap space
 	at gnu.trove.map.hash.TLongIntHashMap.rehash(TLongIntHashMap.java:181)
 	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:417)
 	at gnu.trove.map.hash.TLongIntHashMap.doPut(TLongIntHashMap.java:222)
	at gnu.trove.map.hash.TLongIntHashMap.put(TLongIntHashMap.java:198)
 	at overflowdb.util.NodesList.add(NodesList.java:47)
	at overflowdb.Graph.addNodeInternal(Graph.java:157)
 	at overflowdb.Graph.addNode(Graph.java:131)
 	at overflowdb.BatchedUpdate$DiffGraphApplier.mapDetached(BatchedUpdate.java:264)
 	at overflowdb.BatchedUpdate$DiffGraphApplier.applyChange(BatchedUpdate.java:291)
 	at overflowdb.BatchedUpdate$DiffGraphApplier.run(BatchedUpdate.java:249)
 	at overflowdb.BatchedUpdate.applyDiff(BatchedUpdate.java:17)
 	at io.shiftleft.passes.ConcurrentWriterCpgPass$Writer.run(ParallelCpgPass.scala:318)
 	at java.base/java.lang.Thread.run(Thread.java:829)
```

And Joern use 15.3g memory and executed for more than 7 hours.

**Comment by mpollmeier** [comment]
Cithout more context, the only thing that's apparent is that the data you try to hold doesn't fit into memory. Thus, either increase `Xmx` or reduce the input data 🤷🏻
