### ISSUE TITLE
[Bug] PHP dependency download semver parse error

### ISSUE THREAD

**Issue by tuxology** [joernio/joern#4513]
**Describe the bug**
We are facing issues in downloading certain dependencies which have suffix such as `rc-1`, `beta1` etc. in the composer file. Here is a sample log below. 

```
2024-05-01 18:25:56.777 ERROR io.joern.php2cpg.utils.DependencyDownloader DependencyDownloader.scala:66: Unable to handle package information `slim/slim`, skipping...`
java.lang.Error: semver parse error: 3.0-beta1
        at com.github.sh4869.semver_parser.SemVer$.apply(SemVer.scala:67) ~[com.github.sh4869.semver-parser-scala_3-0.0.6.jar:0.0.6]
        at io.joern.php2cpg.utils.DependencyDownloader$package$.$init$$$anonfun$4(DependencyDownloader.scala:218) ~[io.joern.php2cpg_3-2.0.350.jar:2.0.350]
        at upickle.core.Types$$anon$1.mapNonNullsFunction(Types.scala:25) ~[com.lihaoyi.upickle-core_3-3.3.0.jar:3.3.0]
        at upickle.core.Visitor$MapReader.mapFunction(Visitor.scala:192) ~[com.lihaoyi.upickle-core_3-3.3.0.jar:3.3.0]
        at upickle.core.Visitor$MapReader.visitString(Visitor.scala:203) ~[com.lihaoyi.upickle-core_3-3.3.0.jar:3.3.0]
        at ujson.ByteParser.visitString(ByteParser.scala:644) ~[com.lihaoyi.ujson_3-3.3.0.jar:3.3.0]
        at ujson.ByteParser.parseStringValue(ByteParser.scala:613) ~[com.lihaoyi.ujson_3-3.3.0.jar:3.3.0]
```

**Expected behavior**
Dependency gets downloaded and type information is added in the CPG

**Comment by DavidBakerEffendi** [comment]
Looks very similar to examples here: https://github.com/sh4869/semver-parser-scala
I guess the parsing is a bit too rigid, but packagist does give a "version_normalized" field I could parse instead
