### ISSUE TITLE
[Bug] server mode throws error about "replpp.server.WebServiceWithWebSocket$basicAuth" not implemented

### ISSUE THREAD

**Issue by BrianMehrman** [joernio/joern#5195]
Hi there, I am trying to get the server mode started so I can query a CPG from a python script.

There is a possibility that I have not setup something correctly.

I have tried a precompiled version, then tried to debug the problem locally with no success.

I when I trying the server mode using a simple test post requests I get an error.

```bash
curl http://localhost:8080/query-sync -X POST -d '{"query": "val bar = foo + 1"}'
```

This request returns the following error.

```logs
java.lang.AbstractMethodError: Receiver class replpp.server.WebServiceWithWebSocket$basicAuth does not define or inherit an implementation of the resolved method abstract wrapFunction(Lcask/model/Request;Lscala/Function2;)Lcask/router/Result; of interface cask.router.Decorator.
        at cask.router.Decorator$.invoke(Decorators.scala:47)
        at cask.main.Main$DefaultHandler.handleRequest(Main.scala:123)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:395)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:861)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

1.  Install Joern
2. Start Joern in server mode
3. Run command `curl http://localhost:8080/query-sync -X POST -d '{"query": "val bar = foo + 1"}'`
5. See error

**Expected behavior**
From the Joern server documentation i expect to see this output

```
$ joern-remote 'val foo = 42'
> val foo: Int = 42
```

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia 15.1.1 (Apple M4 Max(
 - Joern Version: v4.0.195
 - Java version: openjdk 21.0.5 2024-10-15 LTS

**Additional context**

Upon trying to get the Dev Container working I did have to migrate the Centos7 image to Ubuntu, however I have not seen any side effects from this change. The CLI still works. 

Please let me know if you need any further information.

**Comment by Codefiring** [comment]
I have occured the same problem.
I am not familiar with scala. I can only find the server mode is implemented in the git repo [scala-repl-pp](url(https://github.com/mpollmeier/scala-repl-pp))

**Comment by mpollmeier** [comment]
thanks for reporting, I'll take a look

**Comment by heedongy** [comment]
I have also occured the same problem.
Although I’m not entirely sure, it seems to be caused by some libraryDependencies version upgrades (Scala 3.5.2 update).
(https://github.com/joernio/joern/commit/8fa3240488d728066fd0f36e586fd10430c05b86)

I solved it temporarily by rolling back to scala-3.4.2 and reverting the libraryDependencies to their previous versions.

Hope this helps!

**Comment by mpollmeier** [comment]
This is caused by an api change in cask... working on a fix

**Comment by mpollmeier** [comment]
fix: https://github.com/joernio/joern/pull/5211

**Comment by BrianMehrman** [comment]
Thank you so much for your quick response and fix.
