### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by yum7777** [joernio/joern#536]
Hi

i got error

```
C:\joern-scan.bat  scalac.c
Detailed logs at: /tmp/joern-scan-log.txt
Exception in thread "main" java.io.FileNotFoundException: \tmp\joern-scan-log.txt 
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)
        at io.shiftleft.console.BridgeBase.runPlugin(BridgeBase.scala:238)
        at io.shiftleft.console.BridgeBase.runAmmonite(BridgeBase.scala:168)
        at io.shiftleft.console.BridgeBase.runAmmonite$(BridgeBase.scala:153)
        at io.shiftleft.joern.JoernScan$.runAmmonite(JoernScan.scala:31)
        at io.shiftleft.joern.JoernScan$.runScanner(JoernScan.scala:105)
        at io.shiftleft.joern.JoernScan$.$anonfun$new$11(JoernScan.scala:82)
        at io.shiftleft.joern.JoernScan$.$anonfun$new$11$adapted(JoernScan.scala:81)
        at scala.Option.foreach(Option.scala:437)
        at io.shiftleft.joern.JoernScan$.delayedEndpoint$io$shiftleft$joern$JoernScan$1(JoernScan.scala:81)
        at io.shiftleft.joern.JoernScan$delayedInit$body.apply(JoernScan.scala:31)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at io.shiftleft.joern.JoernScan$.main(JoernScan.scala:31)
        at io.shiftleft.joern.JoernScan.main(JoernScan.scala)

```

**Comment by yum7777** [comment]
i think error point path..

```
Exception in thread "main" java.io.FileNotFoundException: \tmp\joern-scan-log.txt 
```

**Comment by itsacoderepo** [comment]
Seems outdated, closing for now. Please, re-open if the error remains.
