### ISSUE TITLE
"Cannot run program ./plume" when using importCode

### ISSUE THREAD

**Issue by piergiorgioladisa** [joernio/joern#601]
**Issue**

I have installed Joern on macOS by following the [documentation](https://docs.joern.io/installation).
When running Joern using the installed binary, I am able to enter in the CLI interface of joern, then running the command `importCode.java("/path/to/jar")` I get an Exception:

```
Exception in thread "main" java.io.IOException: Cannot run program "./plume": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:85)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:117)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:144)
	at io.shiftleft.joern.JoernParse$.generateCpg(JoernParse.scala:64)
	at io.shiftleft.joern.JoernParse$.$anonfun$run$2(JoernParse.scala:29)
	at scala.util.Either.flatMap(Either.scala:352)
	at io.shiftleft.joern.JoernParse$.$anonfun$run$1(JoernParse.scala:28)
	at scala.util.Either.flatMap(Either.scala:352)
	at io.shiftleft.joern.JoernParse$.run(JoernParse.scala:27)
	at io.shiftleft.joern.JoernParse$.delayedEndpoint$io$shiftleft$joern$JoernParse$1(JoernParse.scala:17)
	at io.shiftleft.joern.JoernParse$delayedInit$body.apply(JoernParse.scala:8)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.shiftleft.joern.JoernParse$.main(JoernParse.scala:8)
	at io.shiftleft.joern.JoernParse.main(JoernParse.scala)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more
```

On the other hand, running Joern from the git-cloned folder, the exception is not raised and the call to plume works.

**Comment by DavidBakerEffendi** [comment]
Will look into this

**Comment by DavidBakerEffendi** [comment]
Struggling to reproduce on my M1 Mac or Linux but we do get:
```
Error loading CPG
overflowdb.storage.BackwardsCompatibilityError: storage metadata does not contain version number, this must be an old format.
res2: Option[io.shiftleft.codepropertygraph.Cpg] = None
```
So hopefully fixing this should fix your issue too.

**Comment by piergiorgioladisa** [comment]
In fact, what I was noticing while doing some tests by calling `importCode.java` was:

- Running the installed version of Joern I got the issue `Cannot run program "./plume": error=2, No such file or directory`
- Running the built version of joern from the git-cloned repo i got the same error you mentioned.

Manually generating the CPG using Plume, then using `importCpg` doesn't generate errors. I hope this could help.

**Comment by DavidBakerEffendi** [comment]
Thanks - yes let me have a look at how Plume is being called perhaps the issue lies there. The `overflowdb.storage.BackwardsCompatibilityError` may also indicate an empty CPG which might be that Plume is not being executed correctly.

**Comment by DavidBakerEffendi** [comment]
Ok found the bug - this is fixed in: https://github.com/joernio/joern/pull/604

**Comment by mpollmeier** [comment]
This got auto-closed when merging the other PR. It works fine for me, but @piergiorgioladisa please double-check.

**Comment by piergiorgioladisa** [comment]
The initial problem has been fixed, meaning that now I am able to don't get the error `Cannot run ./plume` but now I get, both from the installed and not version:

```
Error loading CPG
overflowdb.storage.BackwardsCompatibilityError: storage metadata does not contain version number, this must be an old format.
res0: Option[io.shiftleft.codepropertygraph.Cpg] = None
```

I have also set the `JAVA_HOME` variable to use Java 11 version (that if I am not wrong is required by Plume). 

Do you get the same error too?

**Comment by mpollmeier** [comment]
I had that exact issue before https://github.com/joernio/joern/pull/604 was merged. Maybe the auto-release plugin wasn't finished yet and you downloaded the previous release - v1.1.214 works fine, I just tested this again. 

And yes, you need java >= 11.

**Comment by piergiorgioladisa** [comment]
It's strange. I have tried the following:

- Run joern from the cloned repository, updated to the last release and I get `Exception in thread "main" java.lang.UnsupportedClassVersionError: overflowdb/Config has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
- Run `sudo ./joern-install.sh --reinstall`, then run joern and I get `Exception in thread "main" java.io.IOException: Cannot run program "./plume": error=2, No such file or directory`

**Comment by DavidBakerEffendi** [comment]
@piergiorgioladisa Plume is soon going to be replaced with the more streamlined [jimple2cpg](https://github.com/joernio/jimple2cpg). Just got released today so perhaps you can try generate CPGs with that until it becomes part of Joern more officially?

**Comment by piergiorgioladisa** [comment]
@DavidBakerEffendi thank you so much for the suggestion, I will for sure experiment with the new tool.
Actually the issue has arisen because before I was producing the CPG using directly Plume, then importing the `cpg.bin` file using the `importCpg` command in Joern. Then I discovered the command `importCode.java` and I thought that it would have been much easier for my scenario (using Python scripts to automate the pipeline and scans for CPGs), since it would have sufficed to modify my `.sc` script for Joern to directly import a JAR and run my queries rather than having a cumbersome pipeline:

```
PLUME -- cpg.bin --> JOERN ---> scan
```

The `importCpg` command works fine. Was just `importCode.java` that gave me this issue.

**Comment by DavidBakerEffendi** [comment]
Ok great sounds like everything is working now.

**Comment by DavidBakerEffendi** [comment]
@piergiorgioladisa jimple2cpg now in: https://github.com/joernio/joern/pull/607/
