### ISSUE TITLE
"java.lang.IllegalStateException: SrcDir does not exist or is not a directory" when using "joern-parse" on Java code

### ISSUE THREAD

**Issue by 41241241241** [joernio/joern#768]
Hello, from my understanding Joern does support analysis of Java source code. I am trying to use the following command on a .java file:

`joern-parse HelloWorld.java --out cpg.bin`

On a simple "HelloWorld.java" file:

```
public class HelloWorld {
    public static void main(String[] args) {
        // Prints "Hello, World" to the terminal window.
        System.out.println("Hello, World");
    }
}
```

But the output states a "java.lang.IllegalStateException" error, although stating "successfully wrote graph" (which is empty when I try to dump it as AST, CPG, etc, whether using "joern-export" or in the joern interactive shell as an empty List):

```
Parsing code at: HelloWorld.java - language: `JAVASRC`
[+] Running language frontend
2021-11-20 00:32:51.571 WARN CpgPass: Exception in parallel CPG pass io.joern.javasrc2cpg.passes.AstCreationPass:
java.lang.IllegalStateException: SrcDir does not exist or is not a directory: HelloWorld.java
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:111) ~[com.github.javaparser.javaparser-symbol-solver-core-3.22.1.jar:?]
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:91) ~[com.github.javaparser.javaparser-symbol-solver-core-3.22.1.jar:?]
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:79) ~[com.github.javaparser.javaparser-symbol-solver-core-3.22.1.jar:?]
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:71) ~[com.github.javaparser.javaparser-symbol-solver-core-3.22.1.jar:?]
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:75) ~[com.github.javaparser.javaparser-symbol-solver-core-3.22.1.jar:?]
        at io.joern.javasrc2cpg.passes.AstCreationPass.typeSolver(AstCreationPass.scala:52) ~[io.joern.javasrc2cpg-1.1.348.jar:1.1.348]
        at io.joern.javasrc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:32) ~[io.joern.javasrc2cpg-1.1.348.jar:1.1.348]
        at io.joern.javasrc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:23) ~[io.joern.javasrc2cpg-1.1.348.jar:1.1.348]
        at io.shiftleft.passes.ParallelCpgPass.$anonfun$enqueueInParallel$2(ParallelCpgPass.scala:59) ~[io.shiftleft.codepropertygraph_2.13-1.3.433.jar:1.3.433]
        at io.shiftleft.passes.ParallelCpgPass.$anonfun$enqueueInParallel$2$adapted(ParallelCpgPass.scala:54) ~[io.shiftleft.codepropertygraph_2.13-1.3.433.jar:1.3.433]
        at io.shiftleft.passes.ParallelIteratorExecutor.$anonfun$map$2(ParallelIteratorExecutor.scala:11) ~[io.shiftleft.codepropertygraph_2.13-1.3.433.jar:1.3.433]
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672) ~[org.scala-lang.scala-library-2.13.6.jar:?]
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431) ~[org.scala-lang.scala-library-2.13.6.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[+] Applying default overlays
Successfully wrote graph to: cpg.bin
To load the graph, type `joern cpg.bin`
```

I also tested "joern-parse" using the [code and steps in the documentation for C](https://docs.joern.io/c-syntaxtree/), which did work and produce ASTs as expected. I am wondering if I forgot to install something for Joern to support Java, or missing something else in my commands. Any help would be greatly appreciated.

Also, some of my specs are: 
Ubuntu 18.04
Java openjdk 11.0.11
Joern v1.1.348 (Latest release at writing)

**Comment by max-leuthaeuser** [comment]
Simply put `HelloWorld.java` into a folder. Lets say `/path/to/some/folder` and run: `importCode("/path/to/some/folder", "HelloWorldProject")`.

**Comment by DavidBakerEffendi** [comment]
Closing since, as of version 1.1.775, `importCode("./HelloWorld.java")` succeeds in creating the CPG.
