### ISSUE TITLE
JavaSrc: Exception in ossdataflow

### ISSUE THREAD

**Issue by itsacoderepo** [joernio/joern#818]
`run.ossoverflow` is throwing an an exception, using the java source front end. 

```
joern> run.ossdataflow
Exception in thread "Writer" java.lang.RuntimeException: Edge with type='REACHING_DEF' with direction='OUT' not supported by nodeType='TYPE_REF'
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:637)
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:616)
	at overflowdb.NodeDb.addEdge(NodeDb.java:303)
	at overflowdb.NodeRef.addEdge(NodeRef.java:160)
	at overflowdb.SemiEdge.$minus$minus$greater(SyntacticSugar.scala:59)
	at io.shiftleft.passes.DiffGraph$Applier.odbAddEdge(DiffGraph.scala:411)
	at io.shiftleft.passes.DiffGraph$Applier.addEdge(DiffGraph.scala:403)
	at io.shiftleft.passes.DiffGraph$Applier.$anonfun$run$1(DiffGraph.scala:355)
	at io.shiftleft.passes.DiffGraph$Applier.$anonfun$run$1$adapted(DiffGraph.scala:351)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1296)
	at io.shiftleft.passes.DiffGraph$Applier.run(DiffGraph.scala:351)
	at io.shiftleft.passes.DiffGraph$Applier$.applyDiff(DiffGraph.scala:438)
	at io.shiftleft.passes.ParallelCpgPass$Writer.run(ParallelCpgPass.scala:116)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Reproduction steps: 
 1. Clone a java project 
    `git clone https://github.com/apache/dolphinscheduler.git`
 2. Import in joern
    `importCode.java("dolphinscheduler")`
 3. Run ossdataflow
    `run.ossdataflow`

**Comment by johannescoetzee** [comment]
Fixed by https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1558 in conjunction with https://github.com/joernio/joern/pull/822
