### ISSUE TITLE
`run.scan` - no queries selected by default

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#853]
When calling `run.scan`, no queries are run. I assume that's because the tags are not set to contain the default tag.
```
joern> run.scan 
No queries matching current filter selection
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
res28: io.shiftleft.codepropertygraph.Cpg = io.shiftleft.codepropertygraph.Cpg@671ba0dc
```

**Comment by ursachec** [comment]
The issue seems to have been caused by the fact that you ran Joern without a querydb installed. Added an error message for this situation so that it doesn't cause any confusions in the future https://github.com/joernio/joern/pull/862. `run.scan` works now:
```
joern> run.scan 
2022-01-06 00:11:49.334 WARN Engine: Attempting to determine flows from empty list of sources.
2022-01-06 00:11:49.334 WARN Engine: Attempting to determine flows to empty list of sinks.
Result: 8.0 : Dangerous function gets() used: /home/claudiu/src/x42/c/X42.c:16:insecure_gets
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
res3: io.shiftleft.codepropertygraph.Cpg = io.shiftleft.codepropertygraph.Cpg@460222eb
```

**Comment by ursachec** [comment]
release still pending, SonaType errored out on the job

```
2022-01-05 23:12:18.658Z error [Sonatype] 
wvlet.airframe.control.Retry$MaxRetryException: Reached the max retry count 243/243: [404: Not Found] Request failed: {"errors":[{"id":"*","msg":"No activity for repository: iojoern-1213"}]}
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:298)
	at wvlet.airframe.control.Retry$RetryContext.run(Retry.scala:253)
	at xerial.sbt.sonatype.SonatypeClient.waitForStageCompletion(SonatypeClient.scala:188)
	at xerial.sbt.sonatype.SonatypeClient.promoteStage(SonatypeClient.scala:225)
	at xerial.sbt.sonatype.SonatypeService.promoteStage(SonatypeService.scala:184)
	at xerial.sbt.sonatype.SonatypeService.closeAndPromote(SonatypeService.scala:198)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$2(Sonatype.scala:182)
	at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:437)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:177)
	at scala.Option.getOrElse(Option.scala:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: wvlet.airframe.http.HttpClientException: [404: Not Found] Request failed: {"errors":[{"id":"*","msg":"No activity for repository: iojoern-1213"}]}
	at wvlet.airframe.http.HttpClientException$.requestFailure(HttpClientException.scala:69)
	at wvlet.airframe.http.HttpClientException$.classifyHttpResponse(HttpClientException.scala:113)
	at wvlet.airframe.http.HttpClient$.$anonfun$defaultHttpClientRetry$1(HttpClient.scala:382)
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:272)
	at wvlet.airframe.control.Retry$RetryContext.runWithContext(Retry.scala:257)
	at wvlet.airframe.http.client.URLConnectionClient.send(URLConnectionClient.scala:64)
	at wvlet.airframe.http.client.URLConnectionClient.get(URLConnectionClient.scala:165)
	at xerial.sbt.sonatype.SonatypeClient.activitiesOf(SonatypeClient.scala:255)
	at xerial.sbt.sonatype.SonatypeClient.$anonfun$waitForStageCompletion$3(SonatypeClient.scala:189)
	at scala.util.Try$.apply(Try.scala:213)
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:268)
```

**Comment by ursachec** [comment]
feature added to Joern `v1.1.418`
